### ISSUE TITLE
Chrome PWA hangs

### ISSUE THREAD

**Issue by ghost** [koekeishiya/yabai#204] opened 2019-08-08 11:02 UTC
## Steps to Reproduce

1. Install some PWA in Google Chrome (e.g. Twitter, Unsplash)
2. Open a PWA installed the step below

## Expected Behavior

PWA opens.

## Actual Behavior

Google Chrome hangs.

**Comment by dominiklohmann** [comment] 2019-08-08 11:22
I can confirm this issue. When yabai is not running, Chrome spawns a dialog window with properties as shown in the screenshot. With yabai running, the window never gets shown and Chrome hangs completely. 

The dialog window shows its actions on the touch bar as well, but nothing happens if you press either of the touch bar buttons.

![image](https://user-images.githubusercontent.com/4488655/62699242-5d8edc80-b9df-11e9-97c9-91e353a84ffd.png)

Note that as a workaround, you can always . set the space to floating mode and install the PWA, then set it back to bsp mode.

**Comment by sei40kr** [comment] 2019-08-09 00:20
@dominiklohmann 
In my case, I could install PWA, but it hangs when opened while yabai running.

**Comment by jbharat** [comment] 2019-09-25 05:25
Closed #263 we can track it here.

Pasted from #263 
I use google calendar and there is no mac app for google calendar. But chrome provides a way to create your own chrome apps. Open calendar in browser, go to More Tools and create shortcut. Give a name and select open as window. Now you can open the calendar app you just created.

When yabai is running opening chrome apps hangs chrome.
[yabai-chromeapp.log](https://github.com/koekeishiya/yabai/files/3650677/yabai-chromeapp.log)


Stopping yabai service and opening the same chrome app works perfectly.

yabai: v2.0.1 (sa installed)
OS: 64bit Mac OS X 10.14.6
Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by pardom** [comment] 2019-10-03 15:34
I'm also experiencing this problem and was seeing it with chunkwm as well. It wasn't apparent that yabai/chunk were causing the bug until I found this issue.

**Comment by punitsoni** [comment] 2020-03-30 20:58
I also see this issue on macOS catalina. I see that I can install a shortcut to chrome app but when trying to start an app, all chrome processes just hang and entire system goes very sluggish. Even getting to "force-stop" menu is painful at this time. 

I use chrome apps extensively in my workflow.  Has anyone found a workaround for this issue?
Is it possible to open chrome in "app-like" mode with minimal window decorations?

**Comment by koekeishiya** [comment] 2020-04-15 09:40
So I decided to take a look at this so I install some pwa and observe Chrome crashes. Then I stop yabai and launch it just to get try and get a clue about what is happening, and the first thing I see after launching the pwa is: 
<img width="233" alt="Screenshot 2020-04-15 at 11 38 13" src="https://user-images.githubusercontent.com/6175959/79322947-d39ff780-7f0d-11ea-8b2b-76bd50789d24.png">

aand I think that was it for me.

**Comment by koekeishiya** [comment] 2020-04-27 07:36
Looked a bit at this again and from what I can see there is nothing wrong in yabai. We receive and process the *application launched* events etc. properly. This is a bug with that Chrome developers will have to look at. Good luck with that..

**Comment by punitsoni** [comment] 2020-04-27 08:24
For me, if I stop yabai, the crop PWAs work properly as expected. However, when yabai is active they just get stuck. I tried this with multiple apps with different developers. All have same behavior.

**Comment by koekeishiya** [comment] 2020-05-22 12:38
This is an issue within Chrome that the developers will have to fix. There is nothing I can do about this from yabai's pov.

**Comment by palashkaria** [comment] 2020-08-10 21:41
@koekeishiya any idea if this issue was raised in the Chrome/chromium bug tracker? 

There's similar stuff happening with Microsoft Edge for Yabai, & with Brave Browser for other WMs  like amethyst (see this: https://github.com/brave/brave-browser/issues/9006#issuecomment-671117230)

The odd thing is - Brave PWAs work fine with Yabai, Edge PWAs don't. On the other hand, Amethyst crashes Brave PWAs & works fine with Edge. Quite odd..

**Comment by koekeishiya** [comment] 2020-08-12 19:16
I don't have the patience at this time to try and deal with these types of issues anymore,  but here is an outline of what yabai is doing that seemingly causes the PWA to Crash in Chrome:

1. yabai is, at all times, monitoring the launch of processes on the system.
2. We detect that a PWA/Chrome instance is launched, and observe for changes to the process' [activation policy](https://developer.apple.com/documentation/appkit/nsapplication/activationpolicy) and [launch status](https://developer.apple.com/documentation/appkit/nsrunningapplication/1532002-finishedlaunching?language=objc).
3. After validating the status using the above fields, we decide that this is an application that we should track/manage, and call the following function to retrieve a handle: `AXUIElementCreateApplication(..)`
4. If successful, try to retrieve a list of the currently active windows using the standard `AXUIElementCopyAttribute()` function, and subscribe to events like window moved, destroyed etc.
5. We never get here because the PWA hangs in either of the above calls for whatever reason. I assume they are thread issues and the PWA application simply gets deadlocked. I can't tell for sure, because the sampling output above is literally unreadable due to the PWA infrastructure.

**Comment by punitsoni** [comment] 2020-08-12 19:39
One thing I noticed recently. If chrome is completely closed and the first thing you open is a PWA (from applications menu shortcut). It works. After this you can open regular chrome window and it does not crash.

So, the problem is only in case of starting a PWA while another chrome window is present.

**Comment by punitsoni** [comment] 2020-08-12 19:43
Is it possible to keep this issue open? Even if you cannot fix this right now, if it is open someone can attempt to fix it if its visible.

**Comment by koekeishiya** [comment] 2020-08-12 19:49
Sure, I'll re-open it for visibility purposes as you mentioned, but I am a 100% certain that this is an issue outside of our control and at the end of the day the Chromium devs is going to have to be the ones to resolve this issue. See my previous comment for how to reproduce the issues from literally any software that uses the macOS accessibility APIs.

**Comment by punitsoni** [comment] 2020-08-12 19:55
> See my previous comment for how to reproduce the issues from literally any software that uses the macOS accessibility APIs.

I could not find this comment. If it is possible to reproduce this issue outside Chrome, then it cannot be fixed by chrome developers right?

**Comment by brightpuddle** [comment] 2021-03-21 21:22
@dominiklohmann
Do you know if there's a way to ignore PWA windows early enough in the recognition process to prevent this? For example, maybe a rule or service that prevents firing off the window recognition functions that are triggering the hang?

I've tried experimenting with rules and services, but not familiar enough with the Objective C or how these functions work to know what I don't know.

**Comment by h4wwk3ye** [comment] 2021-08-21 17:07
Hi, now brave has also changed the way pwa behave like other chromium browsers ([https://github.com/brave/brave-browser/issues/7205](https://github.com/brave/brave-browser/issues/7205)). Is there a way to make pwa work with yabai. I tried [https://github.com/filips123/FirefoxPWA] but it was too much of a hassle.

**Comment by andryandrew** [comment] 2021-10-14 16:43
I second this, it seems other similar extensions (AltTab, BetterSnapTool) now work with chromium-based PWAs, while `yabai` doesn't on my machine

**Comment by vramdal** [comment] 2021-10-20 09:01
FWIW, this has been reported against Chromium as https://bugs.chromium.org/p/chromium/issues/detail?id=1129837

**Comment by jtuckerk** [comment] 2021-10-31 19:21
In the meantime I've found [Chromeless](https://webcatalog.io/chromeless/) it seems to require a separate login for every app which is slightly annoying, but otherwise it accomplishes the same thing as chrome apps. I havent tried creating custom apps yet, but it looks straight forward.

**Comment by NylonDiamond** [comment] 2021-12-09 05:39
www.sodastream.com is another site that will cause a crash :)

**Comment by oneself** [comment] 2022-03-03 12:24
I can't say that I completely understand the idea that Chrome needs to fix this issue. Chrome is used by billions of users worldwide and works fine (mostly). When Yabai runs, Chrome crashes; when Yabai isn't running, Chrome doesn't crash. Regardless of who's technically at fault, it seems clear that Yabai needs to change to make Chrome work, not the other way around. I love using Yabai, and I have to use Chrome, and given Chrome's popularity, I imagine that I am not alone.

**Comment by koekeishiya** [comment] 2022-03-03 12:51
>  Chrome is used by billions of users worldwide and works fine (mostly). When Yabai runs, Chrome crashes; when Yabai isn't running, Chrome doesn't crash. Regardless of who's technically at fault, it seems clear that Yabai needs to change to make Chrome work, not the other way around. 

Generally I agree with this statement. Unfortunately we live in the real world with real constraints; I can't turn water into wine.
Neither Chrome nor macOS gives me the information that I need to be able to disambiguate between PWA's and a normal browser instance from what I have discovered so far, and the Crash is happening inside the PWA infrastructure.

Lets not forget that one piece of software here is written and maintained by 1 guy in his spare time as a hobby, while the other is a professional piece of software used by millions of people, supported by one of the largest and richest tech companies in history. 

I have outlined steps to reproduce the issue and where to begin tracing/debugging in my comment above, for those that are interested in looking at the issue. I have wasted countless hours on this and it is not worth more of my time. Feel free to prove me wrong if you'd like.

**Comment by dev-msp** [comment] 2022-03-12 16:11
The Chrome bug report is now visible again (asked a friend for a hand). By default, crash reports are hidden since logs can contain sensitive info.

Also uploaded a sample there since the one linked in this thread won't currently load for me.

**Comment by rsynnest** [comment] 2022-03-15 18:12
Just to add another datapoint, for me Chrome was hanging 4-5 times/day while running Yabai, without any Chrome Apps/PWAs installed. I do have some Chrome extensions installed (SurfingKeys, 1Password), but not much. After turning off Yabai Chrome has not hanged a single time in the past 2 weeks.

This bug affected many previous versions, but my current affected versions are:
```
MacOS 11.6.2
Yabai 3.3.10 HEAD
Chrome 99.0.4844.51
```

**Comment by ianks** [comment] 2022-03-16 18:36
> Just to add another datapoint, for me Chrome was hanging 4-5 times/day while running Yabai, without any Chrome Apps/PWAs installed. I do have some Chrome extensions installed (SurfingKeys, 1Password), but not much. After turning off Yabai Chrome has not hanged a single time in the past 2 weeks.
> 
> This bug affected many previous versions, but my current affected versions are:
> 
> ```
> MacOS 11.6.2
> Yabai 3.3.10 HEAD
> Chrome 99.0.4844.51
> ```

Same,  no chrome apps but have 1password.

**Comment by emptyflask** [comment] 2022-03-24 21:01
Interestingly, I'm not seeing this crash anymore, using:
```
MacOS 12.2.1 (M1)
Yabai 4.0.0
Chrome 99.0.4844.83
```
When I last tested with Chrome 98.0.4758.109 (everything else the same), that sodastream website would crash the browser. I haven't used it extensively yet, though.

**Comment by brightpuddle** [comment] 2022-03-25 14:56
@emptyflask 

I'm on 12.3 (Intel), Yabai 4.0.0, and 99.0.4844.83, and the issue is still present. You had me excited for a moment.

You'd have to open it as a PWA, i.e. going to PWA-enabled website within Chrome won't trigger the issue. Go to Google Maps and the PWA icon will appear in the location bar, or choose Open in Google Maps from the menu.

If it turns out that it really did suddenly resolve for you, it would be really great to understand more about your conditions. I've been waffling between the otherwise perfection of yabai and other, lesser solutions for years because of this one issue.

**Comment by dev-msp** [comment] 2022-04-22 17:24
Per the [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1298082#c45) that's tracking the overarching bug, there is a fix for this in the latest canary release.

**Comment by brightpuddle** [comment] 2022-04-23 01:51
I just tested the Canary 103.0.5019.0 release with the YouTube Music and Google Photos PWAs and no issues.

Now we either run Canary or just wait until it trickles down into a normal release.

**Comment by jtuckerk** [comment] 2022-04-23 17:39
Can confirm! The canary release no longer hangs when using chrome apps and yabai

**Comment by vramdal** [comment] 2022-07-13 22:40
It seems the fix has made its way into Chrome's Stable channel, so this issue can be closed.

**Comment by farzadmf** [comment] 2022-07-14 12:12
Unfortunately, I still have the problem with what I call "Javascript-heavy" Websites (Chrome version `103.0.5060.114`)

**Comment by teelahti** [comment] 2022-07-15 12:47
I can confirm this is now fixed for me after the latest Chrome update.

**Closed** 2022-08-04 13:15 UTC
Labels: bug, can't fix, external

**Comment by tijmenvangulik** [comment] 2023-10-21 08:12
I still have this problem in Version 118.0.5993.88 (Official Build) (arm64) . It hangs when ever I update my website https://ergometer-space.org/.  Brave and edge running on the same machine do not have this problem.
