### ISSUE TITLE
Windows app reordering on spaces even with multiple screens

### ISSUE THREAD

**Issue by deimosfr** [koekeishiya/yabai#270] opened 2019-10-04 07:44 UTC
Hi,

I'm using a laptop with 2 screens attached. I'd like to dedicate some apps to spaces and spaces to screens. That's why I did this configuration:
```
yabai -m rule --add app="Chrome" space=3
yabai -m rule --add app="Calendar" space=4
yabai -m rule --add app="Station" space=4
yabai -m rule --add app="Slack" space=5
```

I've also disabled this: http://osxdaily.com/2011/11/12/stop-spaces-rearranging-mac-os-x/

But when I plug screens on the laptop or unplug, it creates new spaces and move some windows to it. Is there anyway to avoid this or at least a solution to move back to what I'd like ?

Thanks

**Comment by dominiklohmann** [comment] 2019-10-04 09:12
See #238 for more info on this.

**Comment by dominiklohmann** [comment] 2019-10-09 08:23
Closing this as a duplicate of #238.

**Closed by dominiklohmann** 2019-10-09 08:23 UTC
Labels: duplicate, question
