### ISSUE TITLE
Improve behaviour when destroying spaces

### ISSUE THREAD

**Issue by ghyatzo** [koekeishiya/yabai#299] opened 2019-11-01 18:20 UTC
As of now if I destroy a space via `yabai -m  space destroy` after destroying the focus moves on the first space automatically,

Is there a setting I missed to change such behaviour? If it's not there it would be really good to have the ability to remain in the space immediately before   as in:

(the space with '*' is the currently active one)
Current behaviour:

    Before:
    Space1     Space2    Space3*

    After yabai -m space destroy:
    Space1*    Space2 

the focus jumps to space1

Desired behaviour:
    Before:
    Space1    Space2    Space3*

    After:
    Space1    Space2*

I have the focus on the next available space, in this case Space2

**Comment by koekeishiya** [comment] 2019-11-06 13:58
You can do this at a user-level already. Simply change focus to the space you want to remain at first, then destroy the space: `yabai -m space --focus prev; yabai -m space recent --destroy`

**Comment by xiamaz** [comment] 2019-11-08 10:03
This doesn't work for me, focus will return to the first space after focusing the last space initially.

This command works, but I would consider it a bad hack for achieving similar behavior: `yabai -m space --destroy; yabai -m space --focus $(yabai -m query --spaces | jq '.[-1].index');`

**Comment by koekeishiya** [comment] 2019-11-08 10:13
> This doesn't work for me, focus will return to the first space after focusing the last space initially.

This is something macOS does because it does not actually support destroying the active space. You can verify that by opening mission control and noticing that the X is not showing for the active space.

If switching  focusing first and then destroying an arbitrary inactive space does not work, then that is a bug.

**Comment by ghyatzo** [comment] 2019-11-08 12:14
> This is something macOS does because it does not actually support destroying the active space. You can verify that by opening mission control and noticing that the X is not showing for the active space.

Uhmm this is not true, i can actually destroy the active space and the x shows on every space i put my cursor on in mission control. And if i do, the active space becomes the immediately previous one.

**Comment by dominiklohmann** [comment] 2019-11-08 12:17
You cannot destroy the active space on any display in Mission Control.

<img width="1440" alt="Screen Shot 2019-11-08 at 13 16 28 (2)" src="https://user-images.githubusercontent.com/4488655/68476073-10164b80-022a-11ea-9fcb-bf0d33aecd50.png">

**Comment by ghyatzo** [comment] 2019-11-08 12:30
Don't know what to tell you, i can... 

![DSC_0114](https://user-images.githubusercontent.com/8601724/68476724-d1819080-022b-11ea-81a3-9b40d3b303d1.JPG)
Can't take a screenshot since as soon as i push the cmd button the x disappears. I have to hover over it a little bit for it to appear.

**Comment by koekeishiya** [comment] 2019-11-08 12:35
I am unable to do that on my mac running Mojave at least. Regardless of whether this is natively supported in mission control or not, the way yabai is able to destroy spaces this behaviour is caused by Apple code, and is in no way something that is performed by yabai on purpose. 

As I said above though

> You can do this at a user-level already. Simply change focus to the space you want to remain at first, then destroy the space: yabai -m space --focus prev; yabai -m space recent --destroy

I tested this and it works just fine for me.

**Comment by dominiklohmann** [comment] 2019-11-08 12:37
A better way to do this would probably be this:

```sh
(yabai -m space --focus prev || yabai -m space --focus next) \
    && yabai -m space recent --destroy
```

**Comment by ghyatzo** [comment] 2019-11-08 12:42
> I am unable to do that on my mac running Mojave at least.
I run Catalina, probably they added it recently.

I guess that dominik solution is complete and a pretty inexpensive, compared to hacking the code.

**Comment by dominiklohmann** [comment] 2019-11-08 13:05
There's actually a slight bug with what I wrote above, because `yabai -m space --focus prev/next` works across display boundaries. This can be fixed quite easily be fixed with a query:

```sh
yabai -m space --focus "$(yabai -m query --spaces --display \
    | jq 'nth(index(map(select(.focused == 1))) + 1).index
        // (reverse | nth(index(map(select(.focused == 1))) + 1).index) 
        // 0')" \
    && yabai -m space recent --destroy
```

**Closed** 2019-11-09 12:04 UTC
Labels: help wanted, question

**Comment by ostwilkens** [comment] 2022-03-13 10:16
I had race condition problems with the earlier samples. This works consistently for me:
```bash
lalt - w : \
    index="$(yabai -m query --spaces | jq '.[] | select(."has-focus").index')" && \
    if [ $index -gt 1 ]; then newindex=$(expr $index - 1); else newindex=$(expr $index + 1); fi && \
    yabai -m space --focus "${newindex}" && \
    yabai -m space "${index}" --destroy
```
