### ISSUE TITLE
Feature request: tabbed layout support

### ISSUE THREAD

**Issue by zypangpang** [koekeishiya/yabai#583] opened 2020-06-18 03:38 UTC
I am a heavy i3 user on Linux and i3 has the tabbed layout, i.e. all windows are maximized and you can cycle through these maximized windows with a shortcut. To my best knowledge, I did not find similar layout or function in yabai. 
So any plan to support it if it has no such function, otherwise can anyone tell me how to use it?
Thanks in advance.

**Comment by dominiklohmann** [comment] 2020-06-18 06:46
Duplicate of #203 
Duplicate of #304

**Comment by yangnom** [comment] 2020-06-21 15:18
This is not quite all the way there, but a way to get something similar to your desired layout going is to fullscreen all the windows you want in one desktop
`alt - f : yabai -m window --toggle zoom-fullscreen`

and then cycle through them using this bit
```
# cycle through windows
shift + ctrl + alt + cmd - 0x29 : yabai -m query --spaces \
  | jq -re ".[] | select(.visible == 1).index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre "add | sort_by(.display, .frame.x, .frame.y, .id) | reverse | nth(index(map(select(.focused == 1))) - 1).id" \
  | xargs -I{} yabai -m window --focus {}
```

I have it attached to my `;` for ease-of-use and I should say that extraordinarily-useful bit of code was writtien by @dominiklohmann to whom I am eternally grateful.

**Comment by zypangpang** [comment] 2020-06-22 08:33
Thanks @yangnom.  The workaround I use now is that first float all windows and then use HyperSwitch to cycle through. Floating is a little better than zoom-fullscreen because the window layout with zoom-fullscreen is reset whenever you open a new window.

**Comment by koekeishiya** [comment] 2020-06-27 22:45
Closing as duplicate of #203

**Closed by koekeishiya** 2020-06-27 22:45 UTC
