### ISSUE TITLE
Windows are not tiling naturally when moving across multiple monitors

### ISSUE THREAD

**Issue by raphaelmosaic** [koekeishiya/yabai#1316] opened 2022-07-04 19:20 UTC
I am using the following commands to move my windows (together with focus) across multiple monitors:
 
```
alt - up : yabai -m window --warp north || $(yabai -m window --display north; yabai -m display --focus north)
alt - left : yabai -m window --warp west || $(yabai -m window --display west; yabai -m display --focus west)
alt - down : yabai -m window --warp south || $(yabai -m window --display south; yabai -m display --focus south)
alt - right : yabai -m window --warp east || $(yabai -m window --display east; yabai -m display --focus east)
```

But there is one thing which really bothers me with that: 
- When I am moving a window from the left monitor to the right monitor it is always tiling & splitting to the right side of the monitor. 
- But when I am moving a window from the right monitor to the left monitor it is first tiling to the right side of the new monitor (just like it feels **natural** and like it is on BSWPM by default.

Question / Issue:
**Is there any setting to change this behaviour - so that when moving windows across monitors they are always tiling closest to where they come from?**

https://user-images.githubusercontent.com/98910367/177207427-0f54491f-7968-46f9-a042-763ac0ec717e.mp4

**Comment by koekeishiya** [comment] 2022-08-18 14:07
Duplicate of #1096 I think.

**Closed** 2024-03-12 22:15 UTC
Labels: duplicate
