### ISSUE TITLE
Drag window to another screen is not visible anymore

### ISSUE THREAD

**Issue by rdewolff** [koekeishiya/yabai#506] opened 2020-05-04 15:46 UTC
The title says it all, when I use the shortcut to drag a window, if I move it to another screen, my windows is not visible and hard to recover.

Is this a known issue ? Any fix or workaround ?

**Comment by koekeishiya** [comment] 2020-05-09 15:56
Hmm I was not actually aware of this behaviour. We are using a private macOS API to move windows around, and the call is literally just `MoveWindow(id, x, y);`. I have an idea of what is missing, but I need to do some digging around for this. There isn't a workaround that i know off.

@dominiklohmann mentioned a native way in macOS do achieve the similar move-window functionality here https://github.com/koekeishiya/yabai/issues/402#issuecomment-582471340
I have not tested this.

**Comment by dominiklohmann** [comment] 2020-05-09 16:15
> @dominiklohmann mentioned a native way in macOS do achieve the similar move-window functionality here [#402 (comment)](https://github.com/koekeishiya/yabai/issues/402#issuecomment-582471340)
> I have not tested this.

I actually prefer this way, because it's a lot smoother and I tend to use <kbd>ctrl</kbd> + <kbd>cmd</kbd> as my modifier keys for yabai mostly anyways, but be aware that the keyboard shortcut for this cannot be changed and that other than yabai this actually raises the window.

**Comment by rdewolff** [comment] 2020-05-09 17:04
Have you been able to reproduce the error? What can I do to help?

**Comment by koekeishiya** [comment] 2020-05-09 17:11
I can reproduce the issue yeah. So to resolve this we basically need to reverse engineer the NSWindow code in the AppKit framework to see what happens internally when a window is positioned. I think I have a lead, but I have not yet attempted to dig into it.

**Comment by rdewolff** [comment] 2020-05-09 17:12
Okay that's out of my knowledge :P

**Comment by koekeishiya** [comment] 2020-05-09 17:51
Fixed on master. Requires the scripting addition to be reinstalled due to a necessary change.

**Closed** 2020-05-09 18:24 UTC
Labels: bug
