### ISSUE TITLE
Yabai is causing Adobe Illustrator less responsive

### ISSUE THREAD

**Issue by xcession** [koekeishiya/yabai#425] opened 2020-02-25 19:08 UTC
Today, while I'm working with Adobe Illustrator. I notice Illustrator is less responsive, for example when I selecting an object. It took like 1 seconds after I click to have an object selected.
Stop yabai service make eveything back to normal.

macOS Catalina 10.15.3

**Comment by koekeishiya** [comment] 2020-03-01 16:04
Not sure if this can be considered a bug. This sounds like a performance problem related to the accessibility API, which I think is outside of my control.

**Comment by xcession** [comment] 2020-03-04 10:51
If I remember correctly, this is not happen before (But I'm not sure when. :( When it was chunkwm or after it change to yabai... not so sure).

**Comment by koekeishiya** [comment] 2020-03-04 11:33
chunkwm didn't have mouse integration the way yabai does, so that is why this was not an issue back then. I suspect the cause of what you experience is happening [here](https://github.com/koekeishiya/yabai/blob/master/src/event.c#L974) or in one of the preceeding calls to the accessibility API.

Are there free or trial versions available for Adobe Illustrator? If so, I can try to see if I can investigate this issue and try to figure out a way to work around that.

**Comment by xcession** [comment] 2020-03-04 14:35
Thanks for point this one out. Maybe an option to disable mouse event handler?

Also, there are free trial available to at Adobe website.

**Comment by 13tales** [comment] 2020-03-06 12:37
I have this problem too. It's _incredibly_ annoying. When you click to select an object, but keep moving the mouse, Illustrator registers it as a click + drag, and yanks your painstakingly positioned object out of position 😐 Toggling management off for the Illustrator window seems to help a little, but stopping yabai is the biggest fix.
This feels like it started pretty recently; I don't remember initially having issues with Illustrator and Yabai.

**Comment by 13tales** [comment] 2020-03-06 12:44
Just came across this https://github.com/koekeishiya/yabai/issues/376; it describes the issue I'm having in Illustrator.

**Comment by hrvstr** [comment] 2020-04-10 11:24
I noticed this too. This also happens with Adobe InDesign. When selecting an object Illustrator will freeze briefly and yabai CPU usage will ramp up to 30-40%. This only started recently and was working fine with earlier versions of yabai. I'll try to downgrade to a couple versions to see if this will fix it.

**Comment by hrvstr** [comment] 2020-04-14 09:28
Seems to be fixed with yabai-v2.4.2. I don't notice any lags when selecting elements in InDesign or Illustrator.

**Comment by koekeishiya** [comment] 2020-04-14 16:17
Should be fixed on latest master.

**Closed** 2020-04-14 21:18 UTC
Labels: addressed not released, performance
