### ISSUE TITLE
Tiles not updating for Skim PDF Viewer

### ISSUE THREAD

**Issue by ryanyz10** [koekeishiya/yabai#479] opened 2020-04-17 04:06 UTC
I'm not sure if this is a Skim issue or a yabai issue so I'll leave it here first. When I combine Skim windows into a tabbed window, the tiles don't update:
![Screen Shot 2020-04-16 at 10 57 11 PM](https://user-images.githubusercontent.com/6510606/79531049-c9c5e380-8036-11ea-80d7-5e79a256eac3.png)

I have to switch to a different space and then switch back for the tiling to update.

**Comment by koekeishiya** [comment] 2020-04-17 07:25
Seems like this is kinda related to #68

**Comment by koekeishiya** [comment] 2020-05-09 16:28
Closing this as a duplicate of #68. If it is in fact not a duplicate of that, it is because macOS does not send us a *element destroyed notification* and so I don't consider it a bug in yabai at that point.

**Closed by koekeishiya** 2020-05-09 16:28 UTC
