### ISSUE TITLE
Warning: Calling plist_options is deprecated! Use service.require_root instead.

### ISSUE THREAD

**Issue by txl263** [koekeishiya/yabai#1644] opened 2023-02-23 07:23 UTC
`#brew services start yabai
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the koekeishiya/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/yabai.rb:42`

OS: macOS 12.6.2 21G320 x86_64

**Comment by carlosvigil** [comment] 2023-02-23 14:19
Came to see if there was an update for this. Getting the same error, not sure when it started cause i've been ignoring it

**Comment by JaJaon** [comment] 2023-02-23 23:41
Any idea if this is something that might break the functionality of Yabai or SKHD?

**Comment by morningfin** [comment] 2023-02-24 20:12
I received the same warning, for both Yabai and SKHD

**Comment by shrugalic** [comment] 2023-02-28 09:42
Duplicate of https://github.com/koekeishiya/yabai/issues/1619, which mentions there's already a PR to fix it: https://github.com/koekeishiya/homebrew-formulae/pull/25

**Comment by jorpilo** [comment] 2023-03-07 01:18
We have replaced the PR by https://github.com/koekeishiya/homebrew-formulae/pull/31
Ready to be merged but not sure who needs to merge it

**Closed** 2023-03-07 09:16 UTC
