### ISSUE TITLE
[BUG] MacOS Sonoma - delayed keyboard input when magic mouse is connected

### ISSUE THREAD

**Issue by wojciech-kulik** [koekeishiya/yabai#1877] opened 2023-10-03 23:40 UTC
I'm experiencing a very weird behavior on macOS Sonoma.

When my magic mouse is connected and I'm typing, sometimes the keyboard input is delayed until I click somewhere else. This issue doesn't occur when my mouse is turned off.

It happens in multiple applications. The one on the video is my app [Snippety](https://snippety.app). Initially, I thought it's a bug in my app, but then it turned out that it's a problem related to Yabai and it also happens in other apps like Xcode (I'm using VIM mode, not sure if it matters). I'm not exactly sure what triggers this problem. In Xcode it happens just in the code editor and in my app it happens in combo boxes in this specific place. When I turn off Yabai or my mouse, everything is fine again.

I'm using a MacBook Pro with M1 Pro. 

Here is the video presenting the problem:
https://www.dropbox.com/scl/fi/mwjcinpmqn5dd6nrbqfa5/yabai_bug.mov?rlkey=hu68gcr6tv7nk18zvr58vjb83&dl=0

**Comment by wojciech-kulik** [comment] 2023-10-06 10:48
I would appreciate any help or maybe workaround to this issue. I work every day in Xcode which makes Yabai unusable to me because the code editor is getting crazy :((.

**Comment by jordan-da** [comment] 2023-10-09 15:10
Out of curiosity, do you have `window_border_blur` enabled?  I have noticed significant input delays when upgrading to Sonoma, but they stopped when I removed `yabai -m config window_border_blur off` from my `yabairc` file.

**Comment by jordan-da** [comment] 2023-10-09 15:15
Well as an additional datapoint, I can't disable SIP either because this is a work computer.  I am also noticing unexpected behaviour when turning `yabai -m config window_border on`... when all alacritty windows now have a blurred backgrounds. When I remove this setting from my `yabairc` file, this behavior stops.

**Comment by playduck** [comment] 2023-10-13 17:19
I have SIP disabled on my personal laptop. I've also noticed considerable slowdown when switching windows (especially apparent when `auto_raise` is turned on). 

The slowdown seems to come only when borders are enabled. 
Setting `yabai -m config window_border off` immediately remedies this.
I've also experienced the blurred window bug (some windows sometimes get completely blurred when they come into focus). 
This one is fixed by turning `yabai -m config window_border_blur off`.

I'm using Sonoma 14.0 (SIP off, sa loaded)

**Comment by wojciech-kulik** [comment] 2023-10-22 21:48
Looks like I have to delete this app and look for some alternative because it's unusable with this bug.

**Comment by wojciech-kulik** [comment] 2023-10-24 00:34
Meh, I had to fix it on my own.

`mouse_handler.c` is buggy. I replaced `kCGAnnotatedSessionEventTap` with `kCGSessionEventTap`. It fixed the problem.

Now resizing using mouse is less reliable, but I don't care about this feature. I use keyboard.

**Comment by koekeishiya** [comment] 2024-01-03 16:48
This sounds like something that should be reported to Apple?

**Comment by wojciech-kulik** [comment] 2024-01-14 08:59
Or it's a misuse of `kCGAnnotatedSessionEventTap`. As documentation says:
> Specifies that an event tap is placed at the point where session events have been annotated to flow to an application.

So if it's incorrectly used (i.e. forwarding the event is delayed by Yabai or something like that) the app won't receive it properly.

I tested it also with disabled SIP and it looks like it happens only when SIP is enabled.

**Comment by koekeishiya** [comment] 2024-01-14 11:46
SIP is irrelevant here.

This is a public Apple API that has been available since Mac OSX Tiger. https://developer.apple.com/documentation/coregraphics/1454426-cgeventtapcreate?language=objcc

**Comment by koekeishiya** [comment] 2024-01-14 12:21
Yes, which is why I said you should report the bug to Apple.

**Comment by wojciech-kulik** [comment] 2024-01-14 12:24
Their fix cycle takes around 1-2 years if you are lucky and if you provide a reproducible minimum sample, so I guess it would be more beneficial for users to try finding some workaround or replacing `kCGAnnotatedSessionEventTap` / `kCGSessionEventTap` but I leave it up to maintainers :).

**Comment by koekeishiya** [comment] 2024-01-14 12:32
I mean I am very much aware of how long Apple takes to resolve bugs, but this is literally a 1 man project (me), and I do not have the time to dedicate to investigate all these random weird quirks anymore. If someone finds a fix to this problem that does not cause a regresssion with https://github.com/koekeishiya/yabai/pull/1378#issuecomment-1233172944 feel free to submit a PR.

**Comment by wojciech-kulik** [comment] 2024-01-14 12:46
I thought more people is maintaining this project, but if it's only you, I completely got it :).

**Comment by koekeishiya** [comment] 2024-03-13 14:38
Fixed on master.

**Comment by koekeishiya** [comment] 2024-03-13 16:20
Fixed in v7.0.0.

**Closed by koekeishiya** 2024-03-13 16:20 UTC
Labels: bug, addressed not released
