### ISSUE TITLE
Sequoia 15.0.1 desktop switching fails

### ISSUE THREAD

**Issue by chris-sanders** [koekeishiya/yabai#2455] opened 2024-10-15 15:36 UTC
I'm aware 15.0 is what's listed as supported, I let an auto-upgrade go through with 15.0.1 recently and yabai has started to fail in two specific ways.

1. I can no longer switch desktops. Via hotkeys
2. I can not move windows to other desktops. Instead of moving to another desktop the window gets pushed to the background on the same desktop.

Is there any information from a debugging perspective I could provide that would help identify what changed in 15.0.1? Or do I just need to wait for the project to address changes in the new update?

**Comment by matth3w-lauz** [comment] 2024-10-21 02:43
me2, I am experiencing an issue with your `issue 2`: `yabai -m window --space 1;` I think this issue emerge after I updated my macbook to 15.0/15.0.1

**Comment by Bug-president** [comment] 2024-10-23 02:28
Thirded. Key commands are recorded and cursor follows the selected desktop, but desktop fails to switch. Started happening on switch to 15.0.1.

**Comment by Quoding** [comment] 2024-10-23 13:28
Folks on the skhd repo talked about similar issues: https://github.com/koekeishiya/skhd/issues/371

However, I doubt the observed behavior is linked to the [change introduced by Sequoia 15.0.1](https://developer.apple.com/forums/thread/763878?answerId=804374022#804374022), since even when respecting the new requirements for shortcuts, yabai does not successfully move windows.

**Comment by shabarin** [comment] 2024-10-24 08:29
I can confirm this as well:

> I can not move windows to other desktops. Instead of moving to another desktop the window gets pushed to the background on the same desktop.

with the one exception: I actually _can_ move window to a new space but only if that is another *active* space on a different display.

**Comment by chris-sanders** [comment] 2024-10-24 21:03
Actually you're right, same results here I hadn't tried using a different monitor.

**Comment by martin-tomes** [comment] 2024-10-29 17:12
As a workaround you can just run the skhd as a background process: 
```
skhd &
```

to make it permanent (or till fixed) you can crate a login shell script with the command above to run skhd after login

**Comment by chris-sanders** [comment] 2024-10-30 17:49
@martin-tomes can you clarify what you mean this doesn't help for me.

I've:
* disabled and uninstalled the skhd service
* ran `skhd &` to run it as a background process

While this asked me to approve my terminal, it didn't fix anything for me.
* I can move a window between monintors
* I can not move a window to a desktop that is not in focus
* I can not change the focused desktop

Are you saying you can move a window to an unfocused desktop and you can change the focus to a new desktop?

**Comment by blancpain** [comment] 2024-11-01 07:33
Following the instructions on partially disabling SIP fixed the issue for me. However, I feel somewhat uneasy about disabling SIP—are there plans to enable moving windows without having to disable SIP?

**Comment by koekeishiya** [comment] 2024-11-01 11:17
Fixed in v7.1.5.

No, you need SIP disabled and scripting addition installed to move windows from Sequoia, because Apple added restrictions to their (private) API.

**Closed by koekeishiya** 2024-11-01 11:17 UTC

**Comment by chris-sanders** [comment] 2024-11-01 18:43
Great thanks I've got it working again!
For anyone going through this process as well, don't forget if you followed the directions in the wiki you've put a `sha256` on your visudo for running `yabai --load-sa` I had to update that which looked like the scripting addon not being installed, but it was really just failing to get started.

**Comment by fabiohj7** [comment] 2024-11-05 03:55
Running:
- Yabai: v7.1.5.
- skhd: v0.3.9.
- MacOS Sequoia 15.1 | M1

I configured the scripting addition and disabled SIP but my shortcut keep putting my window to the background.

Is there a way that you could better explain the solution to this problem?
