### ISSUE TITLE
Resizing like in chunkwm

### ISSUE THREAD

**Issue by karbecker** [koekeishiya/yabai#200] opened 2019-08-07 19:54 UTC
Hi, yabai is really cool, thanks for all the hard work that went into it!

I’m wondering how to achieve the same resizing with keys I had working in chunkwm like so:

```
shift + alt - a : chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge west; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge east
shift + alt - s : chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge south; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge north
shift + alt - w : chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge north; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge south
shift + alt - d : chunkc tiling::window --use-temporary-ratio 0.05 --adjust-window-edge east; chunkc tiling::window --use-temporary-ratio -0.05 --adjust-window-edge west
```

Thanks for your help, I tried something like

```
shift + alt - w : yabai -m window --resize top:0:-10; yabai -m window --resize bottom:0:10
shift + alt - s : yabai -m window --resize top:0:10; yabai -m window --resize bottom:0:-10
```

but that does not work as expected with all windows wherever they are located on the display.

**Comment by dominiklohmann** [comment] 2019-08-07 20:30
This is a tough problem to solve. Assuming you have three windows side by side, which window should be resized?

The below came up in a previous thread about this and behaves just like i3 and similar to chunkwm, which is basically what you were suggesting.

```sh
ctrl + cmd - h : yabai -m window --resize left:-20:0 ; yabai -m window --resize right:-20:0
ctrl + cmd - j : yabai -m window --resize bottom:0:20 ; yabai -m window --resize top:0:20
ctrl + cmd - k : yabai -m window --resize top:0:-20 ; yabai -m window --resize bottom:0:-20
ctrl + cmd - l : yabai -m window --resize right:20:0 ; yabai -m window --resize left:20:0
```

Personally I use the below and find it to be a lot more convenient. E.g. when moving to the left using <kbd>ctrl</kbd> + <kbd>cmd</kbd> + <kbd>h</kbd>, I try to shrink the westwards windows right border, and if that fails because no westward window exists, I instead resize the focused windows right border). 

This still does not cover all situations, but I do think it feels a lot more natural.

```sh
ctrl + cmd - h : yabai -m window west --resize right:-20:0 2> /dev/null || yabai -m window --resize right:-20:0
ctrl + cmd - j : yabai -m window north --resize bottom:0:20 2> /dev/null || yabai -m window --resize bottom:0:20
ctrl + cmd - k : yabai -m window south --resize top:0:-20 2> /dev/null || yabai -m window --resize top:0:-20
ctrl + cmd - l : yabai -m window east --resize left:20:0 2> /dev/null || yabai -m window --resize left:20:0
```

Also you can just use the mouse to resize splits with yabai: just resize the window and the splits will be adapted.

**Comment by karbecker** [comment] 2019-08-07 20:35
Thanks! I knew about the mouse feature, but your second suggestion works fine for me when I use the keyboard!

**Closed** 2019-08-09 17:21 UTC

**Comment by JeanMertz** [comment] 2020-04-03 09:57
@dominiklohmann I wanted to try your suggested commands:

```
ctrl + cmd - h : yabai -m window west --resize right:-20:0 2> /dev/null || yabai -m window --resize right:-20:0
ctrl + cmd - j : yabai -m window north --resize bottom:0:20 2> /dev/null || yabai -m window --resize bottom:0:20
ctrl + cmd - k : yabai -m window south --resize top:0:-20 2> /dev/null || yabai -m window --resize top:0:-20
ctrl + cmd - l : yabai -m window east --resize left:20:0 2> /dev/null || yabai -m window --resize left:20:0
```

If I have three windows with equal size side-by-side, if I use `ctrl + cmd - h` on the middle window, the left window shrinks as expected, and the middle window expands to the left as expected, _however_, the right-most window also _slightly_ increases in size towards the left, and the middle window slightly moves its right-most border to the left.

Is this expected behaviour?

![Screen Recording 2020-04-03 at 11 51 40](https://user-images.githubusercontent.com/383250/78348398-3d311500-75a2-11ea-8b16-eaa3b48df902.gif)

**Comment by JeanMertz** [comment] 2020-04-03 10:03
Update to the above issue:

This does _not_ happen if I resize the middle window to the right:

![Screen Recording 2020-04-03 at 12 01 19](https://user-images.githubusercontent.com/383250/78348945-217a3e80-75a3-11ea-9fcd-ef156cc2b9c0.gif)

**Comment by dominiklohmann** [comment] 2020-04-03 10:14
This is the intended behavior. You need to think of it in terms of the underlying tree structure.

You'll likely get better results if you just resize windows using the mouse. All other windows will be adjusted accordingly.

**Comment by qizidog** [comment] 2023-07-28 07:34
Take a look at these keybindings, it's more intuitive, take less cost and mute noise.

```bash
shift + alt - h : yabai -m window --resize right:-20:0 2> /dev/null || yabai -m window --resize left:-20:0 2> /dev/null
shift + alt - j : yabai -m window --resize bottom:0:20 2> /dev/null || yabai -m window --resize top:0:20 2> /dev/null
shift + alt - k : yabai -m window --resize bottom:0:-20 2> /dev/null || yabai -m window --resize top:0:-20 2> /dev/null
shift + alt - l : yabai -m window --resize right:20:0 2> /dev/null || yabai -m window --resize left:20:0 2> /dev/null
```

**Comment by TuralAsgar** [comment] 2024-05-09 07:05
@qizidog Thanks a ton.
I was looking for something like that.
It works like a clock.

**Comment by Chamal1120** [comment] 2025-11-07 06:05
> Take a look at these keybindings, it's more intuitive, take less cost and mute noise.
> 
> shift + alt - h : yabai -m window --resize right:-20:0 2> /dev/null || yabai -m window --resize left:-20:0 2> /dev/null
> shift + alt - j : yabai -m window --resize bottom:0:20 2> /dev/null || yabai -m window --resize top:0:20 2> /dev/null
> shift + alt - k : yabai -m window --resize bottom:0:-20 2> /dev/null || yabai -m window --resize top:0:-20 2> /dev/null
> shift + alt - l : yabai -m window --resize right:20:0 2> /dev/null || yabai -m window --resize left:20:0 2> /dev/null

This is just what I wanted. Thanks!
