### ISSUE TITLE
Hangs when opacity is used

### ISSUE THREAD

**Issue by kingspp** [koekeishiya/yabai#327] opened 2019-11-30 04:32 UTC
**Environment:**
 
OS: MacOS Catalina 10.15.1
Yabai: v2.1.3
csrutil status: disabled

**Configuration:**

```bash
./yabairc
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
```

**Results in :**

![image](https://user-images.githubusercontent.com/6322488/69895514-40b84500-12ff-11ea-864e-3157009905d0.png)

**Comment by dominiklohmann** [comment] 2019-11-30 08:03
Duplicate of #277

**Closed by dominiklohmann** 2019-11-30 08:03 UTC
Labels: duplicate
