### ISSUE TITLE
Smartly disable focus follows mouse while select types of dialogs or panes are open

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#407] opened 2020-02-10 14:04 UTC
From a user point of view, it does not make sense that moving the mouse towards an open Notification Center can close the Notification Center.

Similarly, when a context menu is open (e.g., from the menu bar or a right click), yabai should smartly disable focus follows mouse. I often find myself having to repeat clicking on things because I forgot to hold down <kbd>fn</kbd>.

**Comment by koekeishiya** [comment] 2020-02-12 09:55
I like this idea, but it might be tricky to pull off. In my experience not all dialogs and/or panes properly report that they were destroyed. I don't remember a particular way to reproduce that, unfortunately.

**Comment by AlaaSaadAbdo** [comment] 2020-06-14 22:56
I believe this is solved here. https://github.com/koekeishiya/yabai/issues/535#issuecomment-642732172

Correct me if I'm wrong. but after this I don't have any issues with select menus.

**Comment by dominiklohmann** [comment] 2020-06-15 13:09
That is partially true – it is fixed for the notification center. However, this is still an issue with menu bar dropdowns and context menus, so I'll leave this open for the time being.

**Comment by koekeishiya** [comment] 2020-06-15 13:29
This still closes the Notification Center for me (and I would also expect that to happen).
There has not been any changes that to alleviate this issue, yet.

**Comment by dominiklohmann** [comment] 2020-06-15 13:31
It changed for ffm=autofocus for windows of the same application, which was my test case. For that it fixed, if it was ever broken for that case.

**Comment by koekeishiya** [comment] 2021-01-13 17:35
I've been thinking about this for quite some time and I think the combination of the following changes should improve the experience of focus-follows-mouse (autoraise) quite a bit:

1. If a menu is opened, disable focus-follows-mouse until the menu closes. This should in theory be doable by subscribing to the menu-opened and menu-closed notifications. 
2. If the currently focused window is going to be fully occluded by the window that is the target of the ffm autoraise action, we bail and ignore it, as you probably would want to interact with the popup window or whatever it is.

**Comment by dominiklohmann** [comment] 2021-01-14 12:03
Sounds good to me. Only additional thing would be the NotificationCenter, which should always disable FFM while open.

**Comment by koekeishiya** [comment] 2021-05-06 18:06
Implemented 1 and 2 from my previous comment on `the-future` branch. 

Note that the new behaviour does not detect menus created by right-clicking on the Dock, as the Dock Is not eligible for menu-opened/closed notifications for some reason. There is also no way to detect menu-opened/closed system-wide:
```
application_observe: notification kAXMenuOpenedNotification failed with error kAXErrorNotificationUnsupported for Dock
application_observe: notification kAXMenuClosedNotification failed with error kAXErrorNotificationUnsupported for Dock
```

I am unable to reproduce the issue with the Notification Center closing on macOS Big Sur, so that I cannot work/comment on.

**Closed** 2022-03-16 22:42 UTC
Labels: enhancement
