### ISSUE TITLE
Updating yabai causes duplicate permission entries for Accessibility

### ISSUE THREAD

**Issue by OfficialCRUGG** [koekeishiya/yabai#1968] opened 2023-11-13 14:18 UTC
Hey there.
Every time I upgrade yabai using `brew upgrade yabai`, it re-requests Accessibility permissions, which is fine in itself, but it also creates a new, separate entry for itself which could become quite a bit much over time, since the previous ones aren't removed. Yes, I can manually remove them, but I still wouldn't consider this to be ideal.
![image](https://github.com/koekeishiya/yabai/assets/25248999/d3f30035-a4fb-4fef-8e83-bf29f6027c6f)

**Comment by gldtn** [comment] 2023-11-18 02:51
I also keep getting thisa nd I never was able to get yabai logo to show up :/

**Comment by Blakeinstein** [comment] 2024-01-09 16:46
Sorry for the necro, I still have this issue and it's getting out of hand now

<img width="465" alt="image" src="https://github.com/koekeishiya/yabai/assets/42214598/48bdd7cf-5f06-4b8d-99ae-5ddc0679ad18">

Anyway I can clear the old entries?

**Comment by jaron-l** [comment] 2024-01-10 22:36
This is a duplicate of #1924

**Comment by PhrantiK** [comment] 2024-01-14 15:03
> Anyway I can clear the old entries?

Highlight the old yabai entries and press -

<img width="470" alt="Screenshot 2024-01-14 09 59 48" src="https://github.com/koekeishiya/yabai/assets/45719263/0072042a-735c-4c99-8791-d74b57e65e81">

**Comment by koekeishiya** [comment] 2024-02-13 09:44
See this comment https://github.com/koekeishiya/yabai/issues/2086#issuecomment-1939670967

> I guess this is happening because macOS stores the absolutepath when saving permissions, because yabai is a single binary application and not an app bundle. When homebrew upgrades yabai it places it in a folder specific to the version, so every brew upgrade causes the binary to be stored at a different path, effectively resetting the permissions.

>You can remove permissions directly inside the macOS settings/permissions window. Just remove stale entry when upgrading. I'm not aware of any workaround as long as you install using homebrew, due to the above situation.

>I never experience this personally because I of course build from source manually, and the target binary never changes its location -- therefore simply codesigning the new binary with the same certificate as the previous binary is enough for macOS to retain permissions.

**Closed by koekeishiya** 2024-02-13 09:44 UTC
