### ISSUE TITLE
macOS Catalina 15.6 extra float space

### ISSUE THREAD

**Issue by SmithJson** [koekeishiya/yabai#652] opened 2020-09-01 05:18 UTC
Hello, when I use Yabai-related menu bar plugins again, I find that the number of desktops is always one more. At first, I thought it was a plug-in problem. Then I looked at their source code, they all used `$/usr/local/bin/yabai -m query --spaces` to get the number of spaces, and then I ran this command and found that it does have extra float window.

screenshot
![image](https://user-images.githubusercontent.com/40036121/91797272-bc5f6d80-ec54-11ea-80c9-1bdfbe377adc.png)

**Comment by dominiklohmann** [comment] 2020-09-01 08:27
Can you reproduce this after a reboot?

**Comment by SmithJson** [comment] 2020-09-01 09:11
> Can you reproduce this after a reboot?

Yes, a restart will also appear

**Comment by koekeishiya** [comment] 2020-09-03 16:02
The query output you read is the result of a macOS API; something wonky is going on with your setup. 
Try to destroy and recreate all spaces (on all connected displays).

**Comment by SmithJson** [comment] 2020-09-04 04:31
> The query output you read is the result of a macOS API; something wonky is going on with your setup.
> Try to destroy and recreate all spaces (on all connected displays).

Thank you for your reply, but I don't know how to destroy the hidden spaces. I can only query how to destroy the spaces displayed in the spaces bar. Can you tell me how to do this?

**Comment by dominiklohmann** [comment] 2020-09-04 08:25
If you have the scripting addition installed, you can run `yabai -m space <index> --destroy`.

With the information from your screenshot that'd be `yabai -m space 3 --destroy`.

**Comment by SmithJson** [comment] 2020-09-04 09:08
> If you have the scripting addition installed, you can run `yabai -m space <index> --destroy`.
> 
> With the information from your screenshot that'd be `yabai -m space 3 --destroy`.

![image](https://user-images.githubusercontent.com/40036121/92222106-0eacc280-eed1-11ea-9712-cf891159f5fa.png)  Doesn't seem to work

**Comment by koekeishiya** [comment] 2020-11-16 15:58
Closing as it is not an issue with yabai. Not sure what else you can try though.

**Closed by koekeishiya** 2020-11-16 15:58 UTC
Labels: question

**Comment by wenjie1991** [comment] 2021-01-14 19:39
I have the same issue. When I try to delete the "ghost" space, it complained `cannot destroy a macOS fullscreen space`.
My OS version is macOS Catalina 15.7.
![image](https://user-images.githubusercontent.com/6602710/104640061-6d1c5580-56a8-11eb-9c3e-c9b4122fcbf8.png)

**Comment by koekeishiya** [comment] 2021-01-14 20:05
This problem is caused by the dashboard space functionality that used to be implemented in macOS. Dashboard was removed in Catalina or Big Sur and this is a bug on their part. Im not really sure how to fix it, but you can read my comments in this issue: https://github.com/koekeishiya/yabai/issues/721

**Comment by wenjie1991** [comment] 2021-01-14 20:20
Thanks @koekeishiya!
It works, The problem has been solved by:
1. Remove the `~/Library/Preferences/com.apple.spaces.plist` file.
2. Log out and log in again.

**Comment by SmithJson** [comment] 2021-01-15 03:01
> This problem is caused by the dashboard space functionality that used to be implemented in macOS. Dashboard was removed in Catalina or Big Sur and this is a bug on their part. Im not really sure how to fix it, but you can read my comments in this issue: #721

Thanks  @wenjie1991  @koekeishiya ，I'm at work now. I'm trying to use my own computer when I get off work.

**Comment by command-z-z** [comment] 2023-01-23 17:59
I also meet this issue . it's caused by an old app called dashboard before majave version but is removed after.

Now, you can enter the following command to force the dashboard to close
`defaults write com.apple.dashboard mcx-disabled -boolean YES && killall Dock`
it works for me.
