### ISSUE TITLE
Launch yabai failed: Bootstrap failed: 5: Input/output error

### ISSUE THREAD

**Issue by TYZRPVX** [koekeishiya/yabai#986] opened 2021-08-17 00:36 UTC
OS: macOS Big Sur 11.5.2
Platform: Intel
SIP: disabled

After I run `brew services start yabai`, return an error 
```
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/tyzrpvx/Library/LaunchAgents/homebrew.mxcl.yabai.plist` exited with 5.
```

**Comment by srgooglo** [comment] 2021-08-25 11:10
Same thing happened to me, it seems to be some problem with the permissions.

I got it to work with a simple
`sudo chmod -R 777 /usr/local/var/log/yabai`

**Comment by Inc0n** [comment] 2021-09-03 09:56
The above solution didn't work for me, I had home-brew installed at /opt, and use that path to chmod on /opt/homebrew/var/log/yabai.

This worked for me, `softwareupdate --install-rosetta`, and potentially be a duplicate of https://github.com/koekeishiya/yabai/issues/982.

**Comment by jingxiangmo** [comment] 2022-03-13 21:31
Hi, I'm having the exact same issue:

```
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/jingxiangmo/Library/LaunchAgents/homebrew.mxcl.yabai.plist` exited with 5.
```

I tried running  `sudo chmod -R 777 /usr/local/var/log/yabai`, but it didn't help. :(

When I type `where yabai` it shows:
```
/opt/homebrew/bin/yabai
/usr/local/bin/yabai
```

What could be the problem? Thanks!

**Closed** 2022-04-21 14:45 UTC
