### ISSUE TITLE
Focus follows mouse set to autofocus sometimes fails to remove focus

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#35] opened 2019-06-11 10:18 UTC
To reproduce the bug: set ffm to autofocus, open two windows of the same application, move the cursor between them. Sometimes both will look like they're focused, but neither will receive keyboard inputs. 

I notice this very often with applications that take a while to gain focus when clicking on them, especially with Chrome. 

<img width="1280" alt="Screenshot 2019-06-11 at 12 10 32" src="https://user-images.githubusercontent.com/4488655/59263738-f2749400-8c41-11e9-9f79-5063ec8b3400.png">

**Comment by marcelja** [comment] 2019-06-14 10:51
`mouse_follows_focus` can be `on` or `off`, right?

Did you set mff `on` and ffm `autofocus`?

**Comment by dominiklohmann** [comment] 2019-06-14 11:20
Sorry—I must've mistyped mff instead of ffm when I opened this issue. Corrected the original post and title. Should've been obvious though as there's an ffm option named autofocus and mff only toggles on/off, just like you said.

**Comment by clevinson** [comment] 2019-06-20 22:34
I was having a very similar issue, but unfortunately have had a difficulty time making it fully reproducable.

This issue happens for me most often in chrome. For me the issue is:

Occasionally when moving quickly between two windows of the same application (most often Chrome, occasionally this has also happened between iTerm windows), a number of my shortcut keys (eg. `cmd+C`, `cmd+V`, `cmd+F`) stop working entirely. Whenever I notice this happening, I can still normally type in the window, but certain actions become frozen or do not appear to work.

Once I move my cursor into the other window, I see the "edit" menu button (in the top menubar) light up blew and start blinking several times, as if to batch process all of the `cmd+C` and `cmd+V` keypresses that were being frozen.

The result is that a bunch of text in the new window has been copied and pasted several times over, from my several failed attempts to copy and paste a different set of text in the previous window.

I will keep attempting to consistently reproduce this error, and will report back once I find anything.

**Comment by koekeishiya** [comment] 2019-06-22 14:40
I can no longer reproduce this after the latest changes. Closing.

**Closed by koekeishiya** 2019-06-22 14:40 UTC
