### ISSUE TITLE
Expecting wrong launch agent plist path

### ISSUE THREAD

**Issue by burhankhanzada** [koekeishiya/yabai#1742] opened 2023-05-11 20:52 UTC
I have customized my mac with a second partition where i have my user folder and set that folder as a home folder for my account from account advance settings but the yabai is expecting launch agent plist file in users which is incorrect

```shell
pwd
/Volumes/Burhan/burhankhanzada

yabai --start-service
yabai: service file '/Users/burhankhanzada/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
yabai: service file '/Users/burhankhanzada/Library/LaunchAgents/com.koekeishiya.yabai.plist' could not be installed! abort..
```

**Comment by koekeishiya** [comment] 2023-05-11 21:22
You are correct that is a problem in the current implementation. I didn't think that through properly and made an assumption when accessing said path.

A more correct way would be to do something like
```
    printf("home: %s\n", [[[[NSFileManager defaultManager] homeDirectoryForCurrentUser] path] UTF8String]);
```

**Comment by burhankhanzada** [comment] 2023-05-12 03:16
Yeah i try to fix that but i don't have command on C language, so kindly can you fix it

**Comment by GeckoSplinter** [comment] 2023-05-13 20:03
Oh nice I did not see that issue kind of duplicate of #1743

**Closed** 2023-05-21 18:02 UTC
Labels: bug, addressed not released
