### ISSUE TITLE
Yabai's tiling doesn't play nice with MacOS auto-tabs feature

### ISSUE THREAD

**Issue by alextremblay** [koekeishiya/yabai#516] opened 2020-05-09 14:26 UTC
Hello,

First off, thank you for making this amazing piece of software. It's totally changed how i think about using my mac

I have however noticed an issue: if a user has *System Preferences > Dock > Prefer tabs when opening documents* set to `Always` (which i think is the default), then yabai does something interesting.

When new windows of a given app are created in the same space as an already-running window of that app, yabai will shrink the existing window to make space for the new one, and then MacOS will insert that new window as a tab into the existing window, leading to this curious behaviour:
<img width="1022" alt="Screen Shot 2020-05-09 at 10 23 59 AM" src="https://user-images.githubusercontent.com/23367954/81476295-433c9600-91df-11ea-8e89-102ac3bc5075.png">
<img width="1022" alt="Screen Shot 2020-05-09 at 10 24 06 AM" src="https://user-images.githubusercontent.com/23367954/81476298-4768b380-91df-11ea-852e-e30f1da6c97f.png">
<img width="1022" alt="Screen Shot 2020-05-09 at 10 24 13 AM" src="https://user-images.githubusercontent.com/23367954/81476299-4d5e9480-91df-11ea-90bb-61b6025d9618.png">

The simplest workaround is to just set *System Preferences > Dock > Prefer tabs when opening documents* to anything other than `Always`

Maybe a note could be added to the README and wiki?

**Comment by koekeishiya** [comment] 2020-05-09 15:04
So this is a duplicate of #68. You can go there if you are interested in looking at it. The short version is that I don't plan on trying to support this functionality due to lack of API support in macOS. I agree that it should be mentioned somewhere in the wiki.

**Comment by alextremblay** [comment] 2020-05-09 21:05
Ok, thanks for letting me know! The workaround is fine for me. I'm not really a big fan of MacOS native tabs anyway.

I've added a note to https://github.com/koekeishiya/yabai/issues/5 regarding updating the wiki. If that request gets pushed through, I'd be happy to close this issue.

Cheers

**Comment by dominiklohmann** [comment] 2020-12-11 13:55
Closing as duplicate.

**Closed by dominiklohmann** 2020-12-11 13:55 UTC
Labels: documentation
