### ISSUE TITLE
Stops working after a while when using an external monitor

### ISSUE THREAD

**Issue by PaddiM8** [koekeishiya/yabai#1309] opened 2022-06-19 10:14 UTC
Yabai works perfectly when I'm just using one monitor, but when I connect another one, it stops working after a while. I need to restart yabai several times a day.

I'm on macOS 12.3.1 and yabai 4.0.1 on an M1 Macbook Air. I'm not sure how to find any error messages, but I know that it's basically unresponsive when it stops working? When I do`yabai -m ...` it just sits and waits indefinitely.

**Comment by koekeishiya** [comment] 2022-06-19 12:22
Can you post a sample of the yabai process when this happens? Open *Activity Monitor* and locate the yabai process, right-click and click *Sample Process*. (Alternatively, click the *i* (info button) after selecting the process, and there should be a button that says *Sample*.

**Comment by PaddiM8** [comment] 2022-06-20 15:51
@koekeishiya Alright, this should be it: [Sample of yabai.txt](https://github.com/koekeishiya/yabai/files/8942025/Sample.of.yabai.txt)

**Comment by koekeishiya** [comment] 2022-06-21 14:42
So it appears that the issue might be this loop here: https://github.com/koekeishiya/yabai/blob/master/src/space_manager.c#L648 which was added due to https://github.com/koekeishiya/yabai/issues/1053

**Comment by PaddiM8** [comment] 2022-06-30 16:28
I just tested it on 4.0.0 and get the problem there as well.

**Comment by ai212983** [comment] 2022-07-22 16:29
Same here on yabai 4.0.1 with macOS Monterey 12.4, Intel Core i7 MacBook Pro.

Problem appears after working a while in full screen mode. It is possible to "unfreeze" by selecting in the dock some app located in other space on same monitor. It will force space switching and yabai "unfreezes".

**Comment by mickaelperrin** [comment] 2022-08-04 13:59
Same here on yabai 4.0.1 with macOS 12.5, MacBook Pro m1
[Sample of yabai.txt](https://github.com/koekeishiya/yabai/files/9260291/Echantillon.de.yabai.txt)

I have to restart yabai regularly to keep it working.

**Comment by koekeishiya** [comment] 2022-08-04 14:23
I've already identified the cause of the issue in my comment above; I just don't know of another way to fix the issue that introduced this problem, so either way something breaks.

**Comment by ai212983** [comment] 2022-08-04 17:08
Maybe add some timeout to the loop?

**Comment by koekeishiya** [comment] 2022-08-14 18:39
I'll look into a proper fix at some point.

**Comment by koekeishiya** [comment] 2022-08-18 14:27
Fixed on master.

**Comment by mickaelperrin** [comment] 2022-08-19 17:18
I tried it all day, and didn't notice any issue.

Thanks !

**Closed** 2022-08-24 15:33 UTC
Labels: bug, addressed not released
