### ISSUE TITLE
Focus stops following mouse after using mission control

### ISSUE THREAD

**Issue by marcelja** [koekeishiya/yabai#319] opened 2019-11-20 13:35 UTC
I set the focus to follow the mouse
`yabai -m config focus_follows_mouse          autofocus`

When I open mission control, e.g. using `yabai -m space 1 --toggle mission-control`, and close it afterwards, the focus is not following the mouse anymore.

```
▶ yabai --version
yabai-v2.1.2
```

**Comment by marcelja** [comment] 2019-11-20 16:43
doesn't happen anymore

**Comment by marcelja** [comment] 2019-11-20 22:06
Ok, I guess that i found a way to reproduce this.

* Have multiple screens
* Make a window native-fullscreen
* Open mission control
* Close mission control
* Try to change focus to another window using the mouse

**Comment by ychnh** [comment] 2019-11-25 16:08
I am having a similar issue.
When I use mission control switch desktop spaces with multiple monitors, yabai will swap focus to the other monitor 2 when i switch desktop spaces on monitor 1.

**Comment by koekeishiya** [comment] 2020-01-19 16:10
> I am having a similar issue.
When I use mission control switch desktop spaces with multiple monitors, yabai will swap focus to the other monitor 2 when i switch desktop spaces on monitor 1.

I'm unable to reproduce this. Need clearer steps to reproduce. Also, please create a new issue for that as these are not similar issues at all.

> Ok, I guess that I found a way to reproduce this.

>Have multiple screens
Make a window native-fullscreen
Open mission control
Close mission control
Try to change focus to another window using the mouse

So the reason this is happening is that we disable mouse-tracking when mission-control is active.
There is no event triggered by macOS when mission-control is exited, but we poll to check whether the mission-control window exists. This check apparently does not work when a fullscreen app is in focus, causing the issue you've described here.

**Comment by koekeishiya** [comment] 2020-01-19 16:40
Fixed on master.

**Closed** 2020-01-19 17:02 UTC
Labels: addressed not released, bug
