### ISSUE TITLE
Mouse-trapping feedback loop between ffm & mff?

### ISSUE THREAD

**Issue by entrez** [koekeishiya/yabai#284] opened 2019-10-16 20:41 UTC
# Summary
The mouse can get stuck moving rapidly between two (or more) windows of the same application under certain circumstances, and it can be difficult to regain control of it.

# Detailed Description
With `focus_follows_mouse` set to `on` & `mouse_follows_focus` set to `autofocus`, when multiple windows of the same application are open I sometimes seem to fall into a loop where focus begins rapidly switching between multiple windows and I lose control of the mouse.

Based on how it appears visually, I think this might happen when yabai's focus (as indicated by the window borders) lags two windows behind the mouse's actual position. When focus then advances a window (1 -> 2), the mouse is warped back to that position (3 -> 2). By that time, yabai has already continued through the focus history `stack' to the mouse's original position (2 -> 3)—as a result, the mouse's new position (2) is still out of alignment with the current focus (3), and the whole thing starts over again. This is obviously just a guess though!

While this is happening, skhd shortcuts for moving focus to a particular window don't seem to work (or maybe are just immediately overridden by the mouse focus), but moving to a different workspace or monitor successfully breaks out of the behavior. Moving the mouse so that it's not in any window at all also stops it I think, but it's tough to do in the time between its position being set & it warping away again.

Here's a recording of the behavior I'm talking about:
![output](https://user-images.githubusercontent.com/40038830/66954846-2c5e0880-f02f-11e9-9c95-29101862ebfd.gif)

# To Reproduce
1. Set the following in your config file:
```
focus_follows_mouse = on
mouse_follows_focus = autofocus
```
2. Open three windows of the same application in one workspace/desktop (I've noticed this most often when using [kitty](https://sw.kovidgoyal.net/kitty/index.html))
3. Move the mouse quickly across the screen from another application or from a position outside of any windows, so that the pointer briefly crosses two of the windows and ends sitting on the third.
4. The mouse should begin swapping between the last two windows it touched.

If you instead make multiple `laps' of the windows in step 3, the mouse's position may loop between more than two windows.

# Additional Information
## Related issues
Maybe #35? It shares some features in common with this issue—having to do with issues moving focus between windows of the same application, happening with some apps more than others, etc. My bad if this is known behavior that I missed.

## Version Details
`yabai-v2.0.1` installed via Homebrew using the `--HEAD` option; the attached gif was recorded using a version compiled from commit [22d40df](../commit/22d40df99e377d7af00b6b8f64625377489e0145), but I also reproduced this problem with the latest version ([bf3a656](../commit/bf3a6569cd71260e34e3f7da037c4bdc30c03714)).

**Comment by koekeishiya** [comment] 2019-10-17 07:22
This is supposed to be solved, maybe a regression in one of the later versions.

**Comment by dominiklohmann** [comment] 2019-10-17 07:23
Do you happen to have a mouse with a very high sensitivity? (On a related note, very slight mouse movements should be ignored for ffm).

**Comment by koekeishiya** [comment] 2019-10-17 08:06
> very slight mouse movements should be ignored for ffm

This is not as simple to implement properly as it first may seem, due to mouse acceleration among other things. I did test this with various Microsoft Office appliactions, which are slow as frick to react in both changes to frame and focus, and that worked fine for me.

The solution that I implemented (that is likely broken now?) was to cache the last window that was focused by ffm, and only allow mouse-follows-focus to happen if the ffm window id was NOT set.

**Comment by entrez** [comment] 2019-10-17 16:03
Having looked at it again a bit more closely, I think the issue is actually related to an interaction/conflict between the ffm setting in kitty (& other apps like iterm2 with a similar option) and the ffm setting in yabai—when I disable ffm in a particular application, I stop being able to reproduce it.

So I guess it's not necessarily a bug with yabai specifically so much as an issue with running system-level and application-level ffm plugins simultaneously, though weirdly I don't remember this happening with chunkwm-ffm.

> Do you happen to have a mouse with a very high sensitivity? (On a related note, very slight mouse movements should be ignored for ffm).

Maybe this is irrelevant now, but I'm using [this trackball](https://www.trackballmouse.org/elecom-m-ht1drbk-huge-wireless-trackball/) with the hardware sensitivity switch set to 1000 DPI and \`\`tracking speed'' set relatively low in System Preferences; I wouldn't guess that's particularly high, but I'm not super familiar with the standard range of mouse sensitivities.

**Comment by koekeishiya** [comment] 2019-10-17 17:28
> Having looked at it again a bit more closely, I think the issue is actually related to an interaction/conflict between the ffm setting in kitty (& other apps like iterm2 with a similar option) and the ffm setting in yabai—when I disable ffm in a particular application, I stop being able to reproduce this behavior.

Seems reasonable. I can't reproduce this issue, but then agan, I don't use built-in ffm in any applications that I use. I don't really consider this a bug in *yabai* then.

**Comment by koekeishiya** [comment] 2019-10-29 07:40
Closing this for now. Feel free to create a new issue for the change in minimum distance between events.

**Closed by koekeishiya** 2019-10-29 07:40 UTC
