### ISSUE TITLE
Dialogs (pop up windows) showing behind app windows

### ISSUE THREAD

**Issue by AmkSk** [koekeishiya/yabai#1156] opened 2022-02-13 09:25 UTC
Hello, I am using the DEV version (HEAD) of yabai on a M1 Silicon Macbook.

I am encountering dialogs not being visible on a lot of apps (e.g. Brave, Preferences). It is basically the same issue as stated in https://github.com/koekeishiya/yabai/issues/987. But I am not using the `layer=above` setting anywhere.

**Comment by Chandru-B** [comment] 2022-02-16 17:45
I am having the same issue on macOS Monterey and **Intel**

**Comment by antoni-k** [comment] 2022-02-20 05:31
Same here, on Monterey 12.1 and M1 Pro.

**Comment by ShawnMcCool** [comment] 2022-02-24 17:18
I just commented out:

```

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on

# which display a windhow should become managed at when created
yabai -m config window_origin_display        default
# auto tile windows to the side
yabai -m config window_placement             second_child

# make floating windows stay on top
yabai -m config window_topmost               on
```

restarted and my dialogs worked again.. I uncommented them to try to figure out the cause.. and the dialogs still worked..

**Comment by AmkSk** [comment] 2022-03-18 13:22
Issues still persist in 4.0.0

**Comment by koekeishiya** [comment] 2022-03-18 13:35
Some application/windows appear to have trouble with child windows when made topmost. If you experience this a lot set `yabai -m config window_topmost off`.

**Comment by lgulich** [comment] 2022-08-17 23:10
Even with `window_topmost off` I am still experiencing the same issue. Namely when trying to download a file with Brave the pop-up to determine the save-to location is hidden.

**Comment by ucchiee** [comment] 2022-09-29 06:04
This workaround works fine for me:
```
alt - l : yabai -m window --toggle topmost; yabai -m window --toggle topmost
```

**Comment by evangelos-ch** [comment] 2022-09-29 09:18
> This workaround works fine for me:
> 
> ```
> alt - l : yabai -m window --toggle topmost; yabai -m window --toggle topmost
> ```

Can confirm this works for me too but you essentially have to use this bind every time you want to see the pop up window, very inconvenient

**Comment by ucchiee** [comment] 2022-09-29 12:14
This custom rules works perfectly fine for me:
```
# applications with custom rules
applications="(Calendar|Mail|Reminders|Notes|Microsoft Outlook|Discord|Messages|Slack|Firefox|Chrome|Code|Microsoft Word|Preview|Terminal|iTerm2|QuickTime|Player|Spotify|Music|Brave Browser|Kitty|Alacritty|Trello)"

# NOTE: you need to set the settings for the applications in the 
#       list first, or else they don't apply properly and you can end up with
#       some weird border/float/window behaviours

# everything listed gets sent to below layer to prevent 
# them from covering floating applications/popup windows
yabai -m rule --add app="^${applications}$"    manage=on layer=below
```

Ref) #1284

**Comment by evangelos-ch** [comment] 2022-09-29 13:01
That works for pop ups from those apps themselves but causes other problems such as system pop ups (spotlight / autocorrect + autocomplete suggestions / mail notifications) forcing a window resize and taking up an entire tile.

**Comment by ucchiee** [comment] 2022-09-29 14:16
Can you upload some images? Those behaviors can't be reproduced in my environment.

**Comment by george43g** [comment] 2023-03-05 22:45
This issue still hasn't been fixed in latest version. Started experiencing this with latest version on an M1 mac 13.0.1

**Comment by lokhmakov** [comment] 2023-04-25 07:52
Same on yabai-v5.0.3, Mac OS 13.3.1

**Comment by AdamDorwart** [comment] 2023-07-25 23:07
Unfortunately this issue is unresolved for me. Applying the above recommended fix

```
# applications with custom rules
applications="(Calendar|Mail|Reminders|Notes|Microsoft Outlook|Discord|Messages|Slack|Firefox|Chrome|Code|Microsoft Word|Preview|Terminal|iTerm2|QuickTime|Player|Spotify|Music|Brave Browser|Kitty|Alacritty|Trello)"

# NOTE: you need to set the settings for the applications in the 
#       list first, or else they don't apply properly and you can end up with
#       some weird border/float/window behaviours

# everything listed gets sent to below layer to prevent 
# them from covering floating applications/popup windows
yabai -m rule --add app="^${applications}$"    manage=on layer=below
```

Causes tooltips in Chrome to flicker and relayout. That issue was resolved here by using `manage=off` so these things seem in conflict? https://github.com/koekeishiya/yabai/issues/424

Agreed these issue make yabai unusable for beginners. Hoping I can figure it.

**Comment by AdamDorwart** [comment] 2023-08-02 20:01
For anyone looking for the answer this solved it for me: https://github.com/koekeishiya/yabai/issues/1798#issuecomment-1630965678

With the above fix I removed `manage=on layer=below` and pop up windows and tooltips both display correctly in Google Chrome.

**Comment by mickaelperrin** [comment] 2023-08-12 12:10
while the fix 
```
yabai -m rule --add app="^${applications}$"    manage=on layer=below
yabai -m config window_topmost off
```

allows me now to see completion of safari and other various menus, I am experiencing a random flicking of the window now :(

**Comment by AdamDorwart** [comment] 2023-08-12 13:59
@mickaelperrin did you try removing `manage=on layer=below` and only using `window_topmost off`? The flickering of the window I was seeing was a rapid relayout caused by hover over tooltips in chrome. I had the issue with your config but fixed all issues (dialog popups and tooltips display correctly, no rapid relayout) with just topmost off.

**Comment by mickaelperrin** [comment] 2023-08-13 10:19
@AdamDorwart mmm, strange, it looks like it's working now only with `window_topmost off`. But I am on my MacBook without external displays. I will update the issue, if I am encounter the issue again with external displays.

**Comment by AdamDorwart** [comment] 2023-08-26 18:37
Oh geez the issue appears state dependent somehow. Without any configuration change (only `window_topmost off`) pop up windows stopped working again in Chrome. I tried restarting yabai and the issue persisted. So then I revived the config `manage=on layer=below`, restarted yabai, and now it works again!

...then I reverted `manage=on layer=below`, restarted yabai, and it still works... I double checked that I didn't update yabai or anything else changed.

Hopefully I'm missing something but that interaction leads me to believe there is some bad state that causes this. I'm back to my `window_topmost off` change only and things are okay for now.

**Comment by Sulfyderz** [comment] 2023-09-22 19:29
Hello,

It's the same issue that #819. In that issue I provided a tempory solution. However, the problem persists with only an app ([Raycast](https://www.raycast.com)). The tempory solution for that app is to call yabai with skhd that way:
```
 fn - f : yabai -m window --toggle topmost;\
          yabai -m window --toggle zoom-fullscreen;\
          yabai -m window --toggle topmost
```
The author of Yabai already made a great work. If someone does have a better solution, I'm curious.

**Comment by koekeishiya** [comment] 2023-10-10 21:41
Window layers have been reworked in v6.0.0 , #1887

**Closed by koekeishiya** 2023-10-10 21:41 UTC
