### ISSUE TITLE
Chrome and Chrome Apps freeze when launch Chrome Apps on Big Sur beta 7

### ISSUE THREAD

**Issue by zxcvbn97** [koekeishiya/yabai#664] opened 2020-09-20 17:11 UTC
Chrome works normally. However,
when I launch any Chrome Apps then both Chrome and Chrome Apps freeze on Big Sur beta 7.

This only happens when yabai is running. Right click on chrome and chrome apps I saw spinning wheels.

yabai-v3.3.0
Big Sur beta 7 20A5374g. THe same issue on big sur beta 6.
Chrome 85 and 86 has the same issue

Chrome App is any web page created using the Tools \ Create Shortcut menu in CHrome that launches a tab in a window mode with no url bar.

**Comment by dominiklohmann** [comment] 2020-09-20 19:05
Duplicate of #204

This issue has existed for a long time and is not new in Big Sur.

**Closed** 2020-11-14 17:41 UTC
Labels: duplicate
