### ISSUE TITLE
Windows in a space reorder seemingly randomly

### ISSUE THREAD

**Issue by kyrisu** [koekeishiya/yabai#1049] opened 2021-11-16 11:05 UTC
Sometimes windows in a space change order. It can happen "randomly" (or I'm triggering it unknowingly).

One way I'm able to replicate it is:
1. Arrange windows in the following configuration:
```
+---------------++----------------+
|               ||                |
|               ||                |
|      1        ||                |
|               ||                |
|               ||                |
+---------------+|       3        |
+---------------+|                |
|               ||                |
|               ||                |
|      2        ||                |
|               ||                |
|               ||                |
+---------------++----------------+
```
2. Make the window 3 full-screen (using native functionality)
3. Exit full-screen
3. Window 3 will switch places with window 2

This also sometimes happens when:

-  I restart the yabai service with `brew services restart yabai`
- I'm just browsing the web and windows just jump

I've enabled `debug_output` but I've not seen anything while performing the above steps even with debug enabled.

My current config:
```
# global settings
yabai -m config debug_output on
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  04
yabai -m config bottom_padding               04
yabai -m config left_padding                 04
yabai -m config right_padding                04
yabai -m config window_gap                   04

# floating windows

yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="NordVPN" manage=off
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="Zoom" manage=off
yabai -m rule --add app="App Store" manage=off

echo "yabai configuration loaded.."
```

**Comment by DennisFeldbusch** [comment] 2021-11-16 11:19
It happens for me too.
I'm on Monterey and using the master branch or the-future branch. That doesn't matter
Also experience some random shuffle with only one window at a space. It seems it is snapping again in the appropriate place even though it was at the right place before.

**Comment by kyrisu** [comment] 2021-11-16 11:39
Should have mentioned it as well - I'm on Monterey (v12.0.1) as well.

**Comment by staccato-em** [comment] 2021-11-18 12:47
This only started happening to me once I upgraded to Monterey - v12.0.1

**Comment by odajay** [comment] 2021-11-19 16:34
I have a similar behavior happening, same settings as. I noticed that the following error message started to appear when reading the error log:

`unknown command 'window_origin_display' for domain 'config'`

I commented it out, but it still happens. 
Here is my `yabai -m query --windows --space` log just after such occurrence:
```
[{
	"id":492,
	"pid":1126,
	"app":"kitty",
	"title":"yabai -m query --windows --space",
	"frame":{
		"x":967.0000,
		"y":12.0000,
		"w":950.0000,
		"h":1576.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":1,
	"split":"none",
	"floating":1,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":217,
	"pid":1433,
	"app":"Safari",
	"title":"Virtual reality for surgical training 101: The ultimate guide to VR in healthcare | Osso VR Blog",
	"frame":{
		"x":12.0000,
		"y":12.0000,
		"w":949.0000,
		"h":1576.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":424,
	"pid":7853,
	"app":"Mail",
	"title":"All Inboxes – 19 messages, 4 unread",
	"frame":{
		"x":1923.0000,
		"y":12.0000,
		"w":1905.0000,
		"h":1576.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":348,
	"pid":6768,
	"app":"Nova",
	"title":"yabairc",
	"frame":{
		"x":967.0000,
		"y":12.0000,
		"w":950.0000,
		"h":1576.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":343,
	"pid":1126,
	"app":"kitty",
	"title":"tail -f /usr/local/var/log/yabai/yabai.err.log",
	"frame":{
		"x":489.0000,
		"y":12.0000,
		"w":472.0000,
		"h":1576.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":569,
	"pid":7247,
	"app":"Roam Research",
	"title":"gall - Yabai",
	"frame":{
		"x":489.0000,
		"y":12.0000,
		"w":472.0000,
		"h":1576.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":648,
	"pid":14253,
	"app":"iA Writer",
	"title":"Untitled",
	"frame":{
		"x":489.0000,
		"y":12.0000,
		"w":582.0000,
		"h":1576.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":191,
	"pid":542,
	"app":"Creative Cloud",
	"title":"",
	"frame":{
		"x":1288.0000,
		"y":19.0000,
		"w":1259.0000,
		"h":1560.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXDialog",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}]
```

**Comment by thechxsenone** [comment] 2021-11-22 07:00
Same problem

**Comment by vkorchagin** [comment] 2021-11-24 11:25
Same problem on Monterey (v12.0.1) as well.

I noticed that reshuffle is frequently (but not always) triggered by a notification.

**Comment by MPV** [comment] 2021-11-24 20:49
Have you looked at https://github.com/koekeishiya/yabai/issues/1054? This one feels like a duplicate of it.

**Comment by vkorchagin** [comment] 2021-11-26 15:28
Thank @MPV, I followed the instructions at #1054 and the issue is resolved for me.

**Comment by 4sito** [comment] 2022-02-12 17:34
@vkorchagin, I'm facing the same issue, I'have read all the thread at #1054, but what exactly did you do to fix your problem, sorry for bothering you but this issue is driving me insane

**Comment by vkorchagin** [comment] 2022-02-12 21:53
@4sito just follow the instructions from the first comment at #1054, the very top:

> You can use the pre-built version I have attached to this post or clone the repository and build from source. To build a universal binary from source, simply run: `make clean` followed by `make` for debug build or `make install` for an optimised build.

I didn't use pre-built binaries, but built them myself with `make clean && make install`, which fixed an issue for me.

**Comment by 4sito** [comment] 2022-02-14 15:57
oh okay, I thought there was a fix for that specific issue, thank you anyways

**Comment by lpil** [comment] 2022-03-10 10:23
Hello everyone! Is there a fix or workaround for this issue?

**Comment by koekeishiya** [comment] 2022-03-16 22:51
update to v4.0.0.

**Closed by koekeishiya** 2022-03-16 22:51 UTC

**Comment by jankkm** [comment] 2022-05-09 11:04
Is the supposedly resolved? I just started using yabai and when restarting yabai all the tiled windows always reorder completely. Is this intended? Is there a way to have a tiled configuration saved so after a reboot or yabai restart I don't have to arrange it manually?

**Comment by tjex** [comment] 2023-08-23 10:44
I'm on the latest build now and windows still reorder after exiting native full screen. 
i.e. The window that was full screen becomes window 1 (furthest to the left)

**Comment by mlorenc01** [comment] 2023-09-08 17:01
This is happening to me very often on `yabai-v5.0.7` and `macOS 13.5.1`.

I have configured yabai to create 10 spaces on startup so I can access them with `cmd+{0-9}` and have a consistent setup. I always send apps to the same spaces, e.g. Terminal to 1, Slack to 3, VPN to 9 etc.

It happens multiple daily that my windows are suddenly shifting or swapping spaces. I know the shift happens during native fullscreen, so I just stopped using it but the issue still happens without me ever entering the native fullscreen and I am not sure what triggers it. It indeed seems random as the OP said.

**Comment by tjex** [comment] 2023-09-08 19:16
> I'm on the latest build now and windows still reorder after exiting native full screen. i.e. The window that was full screen becomes window 1 (furthest to the left)

...now its not doing so. Perhaps I a) kooked it or b) pulled an update seemingly right after my original (quoted) reply (v5.0.7)

**Comment by AlJohri** [comment] 2023-09-26 07:29
Is there a common keybinding use to refresh yabai and skhd based on updates to yabairc and skhdrc files? Currently I use the following:

```
cmd + ctrl + alt + shift - r : yabai --restart-service && skhd --restart-service
```

However, it is a bit slow and also causes all of my windows to reshuffle non-deterministically.

**Comment by tjex** [comment] 2023-09-26 08:37
That's the correct and recommended command. The reshuffling is what I would think is an expected behaviour, as Yabai is presumably iterating through all open windows / apps, and reassigning ids, which may well change the ordering of each window on the screen - contrary to the way in which you had customised it.

**Comment by AlJohri** [comment] 2023-09-26 09:23
I noticed that even just executing `~/.yabairc` without restarting yabai seems to have this shuffling effect for me.

However, if I comment out `sudo yabai --load-sa` in the `~/.yabairc` file, I don't get the re-ordering anymore.

**Comment by tjex** [comment] 2023-09-27 08:15
I'm fairly sure that the `sudo yabai --load-sa` is the essential command that actually communicates to the underlying layers of the Mac OS to do the window management. 

So by commenting out that line, I'd expect that Yabai isn't actually being reinitalised at all.

**Comment by karimStekelenburg** [comment] 2024-05-26 21:19
In case anyone is still running into this: I accidentally but the `yabai load-sa` at the bottom of my `.yabairc`. Moving it to the top has solved it for me.

**Comment by tjex** [comment] 2024-05-27 22:51
yep, can confirm this is correct, as per the docs:

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
