### ISSUE TITLE
Space instructions failing since last MacOS update

### ISSUE THREAD

**Issue by probaton** [koekeishiya/yabai#913] opened 2021-05-27 20:35 UTC
Ever since a recent Mac update space manipulation through Yabai seems to have gone haywire. All instructions to move, create, or delete spaces are, as far as I can tell, being ignore entirely. Focusing a space without any windows doesn't seem to do anything either. 

I've tried updating and restarting Yabai, as well as restarting the laptop. 

Reproduction 1: 
1. `yabai -m space --display 2`
2. The space remains in place and nothing is printed to the console, unless the space is already located on the target display, in which case an error to that effect is thrown. 

Reproduction 2: 
1. Create a new (empty) workspace
2. `yabai -m space --focus <index-of-empty-space>`
3. Again, nothing happens and nothing is printed to the console.  

OS: Catalina 10.15.7
Yabai: 3.3.10

**Comment by peppy** [comment] 2021-05-28 06:36
I'm having similar issues, but only after updating yabai to the latest release and after a macOS restart (with no update applied). Was working fine previously (on 11.4 Beta (20F5065a)).

![20210528 153429 (iTerm2)](https://user-images.githubusercontent.com/191335/119940474-35180e00-bfca-11eb-924e-10314126ebbd.png)

HEAD: doesn't work
3.3.10: doesn't work
3.3.9: doesn't work
3.3.8: doesn't work
3.3.7: doesn't work

I uninstalled, reinstalled `yabai` and scripting additions each time, re-enabling accessibility access. I don't even know how this can happen, since on the surface it looks like nothing has changed. I've been tracking `HEAD` releases without issue for some weeks.

My usual workaround still works, which is targetting an application on the space rather than the space itself:

```csharp
yabai -m window --focus (yabai -m query --windows |jq '.[] | select (.app  == "Safari") | .id');
```

May be a useful temporary solution for others experiencing this issue.

**Comment by danymat** [comment] 2021-05-28 20:18
I'm currently on 11.5 (20G5023d) and the space focus works for me with version 3.3.10. It didn't work with version 3.3.9 thought

**Comment by peppy** [comment] 2021-05-29 05:51
Didn't even realise 11.5 was out - will try with that tomorrow when I get a chance to update!

**Comment by koekeishiya** [comment] 2021-05-29 07:36
v3.3.10 works just fine for me on macOS 11.4

Sent from my iPhone

On 29 May 2021, at 07:51, Dean Herbert ***@***.***> wrote:

﻿

Didn't even realise 11.5 was out - will try with that tomorrow when I get a chance to update!

**Comment by koekeishiya** [comment] 2021-05-30 11:57
Also fixed on 10.15.7 as confirmed in https://github.com/koekeishiya/yabai/issues/911

Make sure you reinstall the scripting-addition after updating to yabai v3.3.10, as explained in the wiki.

**Closed by koekeishiya** 2021-05-30 11:57 UTC

**Comment by peppy** [comment] 2021-05-31 02:20
My process for testing is:

- uninstall yabai
- remove from accessibility
- reinstall yabai

```csharp
 sudo yabai --uninstall-sa; sudo yabai --install-sa; sudo yabai --load-sa; brew services restart yabai
```

I can still reproduce failures; are there any further diagnostics I could provide to be more helpful?

**Comment by probaton** [comment] 2021-06-01 21:17
Reinstalling the scripting addition worked for me! Thanks.
