### ISSUE TITLE
[suggestion] Different modifiers for mouse actions

### ISSUE THREAD

**Issue by oleksii-haponiuk** [koekeishiya/yabai#635] opened 2020-08-07 09:39 UTC
Currently yabai has 2 mouse actions on left and right click. The thing is I don't want to leave the home row while using trackpad, so I don't want to use right click. I'd rather have 2 different modifiers, e.g. fn + left click is move and shift + left click is resize. Ctrl + click emulates right click, but it doesn't work for dragging.

**Comment by koekeishiya** [comment] 2020-08-08 00:01
duplicate of #601

**Closed** 2020-08-11 12:50 UTC
Labels: duplicate, suggestion
