### ISSUE TITLE
Windows overlapping when tiled

### ISSUE THREAD

**Issue by madkinsz** [koekeishiya/yabai#685] opened 2020-10-08 18:41 UTC
Hi!

I've just done an install of yabai on a new computer and am running into some issues I haven't seen before. Notably, when I spawn new Firefox windows they are layered on top of each other. The first 3 windows are fine but the fourth and subsequent are overlapped. This also happens with Safari so I don't believe it is isolated. Weirdly it takes more terminal windows for it to happen but eventually does still.

I've also noticed that my windows will tile off the bottom of my screen as well.

## Specs
I'm running Catalina 10.15.7 on a 13" MBP with the SIP disabled as in the install instructions.

```
% yabai --version
yabai-v3.3.0
```

```
% csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

I'm just using the .yabairc from the default install -- without the rc the same thing happens except there is no BSP management at all until I run `yabai -m config layout bsp`

## Attempted solutions
- Uninstall and reinstall yabai
- Reboot
- Disable and re-enable accessibility with reinstall
- Run `yabai --verbose` -- nothing weird in the logs
- Restarting yabai to retile windows

## Example

<img width="1440" alt="foo and bar windows are layered" src="https://user-images.githubusercontent.com/2586601/95499429-1c36eb80-095a-11eb-90ce-11cb3881bae2.png">

```
% yabai -m query --windows
[{
	"id":99,
	"pid":1499,
	"app":"Firefox",
	"title":"main at DuckDuckGo",
	"frame":{
		"x":12.0000,
		"y":34.0000,
		"w":705.0000,
		"h":854.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":0,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":803,
	"pid":1499,
	"app":"Firefox",
	"title":"top at DuckDuckGo",
	"frame":{
		"x":723.0000,
		"y":34.0000,
		"w":705.0000,
		"h":424.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":0,
	"focused":0,
	"split":"horizontal",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":811,
	"pid":1499,
	"app":"Firefox",
	"title":"bar at DuckDuckGo",
	"frame":{
		"x":1078.0000,
		"y":464.0000,
		"w":450.0000,
		"h":424.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":0,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":807,
	"pid":1499,
	"app":"Firefox",
	"title":"foo at DuckDuckGo",
	"frame":{
		"x":723.0000,
		"y":464.0000,
		"w":450.0000,
		"h":424.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":0,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},
...
```

Running the `balance` command actually fixes that case but with additional windows causes mayhem

<img width="1440" alt="Screen Shot 2020-10-08 at 11 43 05 AM" src="https://user-images.githubusercontent.com/2586601/95500357-8e5c0000-095b-11eb-9503-2dc6d1d6d843.png">

**Comment by Liquidmantis** [comment] 2020-10-08 18:58
What's happening is you're hitting the minimum width of those windows and they can't be any narrower.

**Comment by madkinsz** [comment] 2020-10-08 19:12
> What's happening is you're hitting the minimum width of those windows and they can't be any narrower.

Ah perhaps I've never seen the behavior before because my other yabai install is a 15" screen

**Comment by dominiklohmann** [comment] 2020-10-09 08:01
Related feature request: #235

**Comment by brorbw** [comment] 2020-10-13 01:44
Unless you patch firefox and remove the min width yourself I don't see a way to solve this issue.

**Comment by koekeishiya** [comment] 2020-10-17 10:48
There is no real fix for this issue. Closing as a dupe of #235 which is a reasonable proposal for how to improve the experience.

**Closed by koekeishiya** 2020-10-17 10:48 UTC
