### ISSUE TITLE
Window Movement

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#632] opened 2020-08-03 11:58 UTC
Would it be possible to change the move/resize feature?

Currently I use hyperDock for that.

I don't have to click the mouse. Pressing cmd moves the window under the cursor, alt resizes it.

It's nice without the additional mouse click when you are used to it for years.

**Comment by koekeishiya** [comment] 2020-08-03 12:52
Should be doable whenever #601 is resolved.

**Comment by 24unix** [comment] 2020-08-03 13:00
Thanks for the fast reply.

I begin to like Yabai :). Currently ist crashes about ever hours, but I'm on Big Sur beta 3 and Yabai HEAD Branch, so that is expected behaviour. Once I'll find a solution for fixing my space shifting I'll just wait till development settles a bit :-)

**Comment by koekeishiya** [comment] 2020-08-03 13:06
Big Sur is not supported at this moment in time. I don't actually have a separate machine, or free space to install it in a VM.
You can follow #589 for updates.

**Comment by 24unix** [comment] 2020-08-03 13:08
Thanks, I'm already following that thread.
I don't know if I have to download the attack Dock-Files, but I'l just wait, not too late in the year Big Sur will officially arrive :)

**Comment by koekeishiya** [comment] 2020-09-03 16:08
closing as duplicate of #601

**Closed** 2020-09-03 16:08 UTC
Labels: suggestion
