### ISSUE TITLE
Leftover inactive borders

### ISSUE THREAD

**Issue by alextes** [koekeishiya/yabai#201] opened 2019-08-08 07:13 UTC
I'm not sure if these borders stem from closed windows, moved windows, or resized windows but I occasionally get leftover borders on my desktop with no window inside. I can't focus or select these borders. I have tried before to close all windows to see if they were somehow tethered to an existing window that was moved or minimized but that does not seem to be the case.

I can take a screenshot if the above description is not clear enough.

**Comment by dominiklohmann** [comment] 2019-08-08 07:41
The usual:

- What's version of macOS are you running?
- When such a leftover border is present, does `yabai -m query --windows --space` show anything unusual (e.g. does yabai think there is window where the frame is)?
- What version are you running? Current master or 1.1.2?

**Comment by alextes** [comment] 2019-08-09 05:40
macOS 10.14.6
yabai does not think there's a window where the frame is. Leftover from resizing it looks like.
yabai version 1.1.2, upgrading to master now

**Comment by alextes** [comment] 2019-08-09 05:43
Hm, seems I'm already on master.
`HEAD is now at e7cda15`

**Comment by koekeishiya** [comment] 2019-09-03 17:55
I personally have never been hit by this issue. Can you confirm that this is issue is still present in v2.0.0 / current master? Thanks.

**Comment by dsawyer13** [comment] 2019-09-04 20:25
This is currently happening on my machine as well.  I'm running the latest master branch.

**Comment by midfm** [comment] 2019-09-05 07:41
I think I'm seeing this too, though (perhaps different to alextes' experience) the empty borders always seem to correspond with the position that a minimised window will occupy when restored. 

The empty borders appear immediately after I connect or disconnect an external monitor.

I see it most often with iTunes and Safari (though this might just be because I often have those apps minimised). 

Like the other posters, I don't see anything corresponding with the empty borders in the output of a query command for all windows on that space, i.e.:

`yabai -m query --windows --space 3`

I can reliably reproduce by opening iTunes, minimising it, then connecting or disconnecting an external monitor.

I just updated to master ("HEAD is now at 826b4a0 v2.0.1") and verified that this still occurs.

**Comment by koekeishiya** [comment] 2019-09-13 15:40
The issue mentioned by midfm is resolved in #250. I'd need more details regarding what kind of operations you are performing when these issue occur. There is simply too many possible reasons for what you are experiencing that I can not narrow it down to a potential source with the given information.

**Comment by koekeishiya** [comment] 2020-01-19 17:08
This issue is no longer really useful for me, as there have been quite some changes to borders since this. Closing this issue. If you still experience problems with borders on the latest version, please do create a new issue with as much useful information as you can.

**Closed by koekeishiya** 2020-01-19 17:08 UTC
Labels: bug
