### ISSUE TITLE
Illegal instruction: 4 on latest HEAD-f9cb03b (v2.1.2) on macOS 10.15.1

### ISSUE THREAD

**Issue by stephen-huan** [koekeishiya/yabai#318] opened 2019-11-19 14:21 UTC
Yabai crashes on creating a new space (`yabai -m space --create`) with the exception "Illegal instruction: 4". Strangely, it does not crash when destroying a new space.

Yabai also crashes on a transition from a fullscreen window in Chrome, e.g YouTube, and exiting.

I installed Yabai with 
`brew install yabai --HEAD`
`sudo yabai --install-sa`

I have also tried installing from source.
Neither crash occurs on [v2.0.1](https://github.com/koekeishiya/yabai/releases/tag/v2.0.1).

~/.yabairc is [here](https://github.com/stephen-huan/macos_dotfiles/blob/master/.yabairc).
Output of `yabai -V`  for both exceptions are [here](https://gist.github.com/stephen-huan/54e75bb7edd9b5d4fb466a682da56e56)

**Comment by koekeishiya** [comment] 2019-11-19 15:02
Can you provide the actual crash dump as well? Which version of macOS are you running?

**Comment by stephen-huan** [comment] 2019-11-19 18:43
macOS 10.15.1 (catalina)

[Crash dump](https://gist.github.com/stephen-huan/54e75bb7edd9b5d4fb466a682da56e56#file-yabai_2019-11-19-134046_macbook-pro-crash)

**Comment by koekeishiya** [comment] 2019-11-19 19:12
Seems to be a duplicate of #313

**Comment by koekeishiya** [comment] 2019-11-19 19:29
Resolved on master.

**Closed** 2019-11-20 02:22 UTC
Labels: addressed not released, bug, duplicate
