### ISSUE TITLE
Yabai always end up in a "Not Responding" state

### ISSUE THREAD

**Issue by gur111** [koekeishiya/yabai#1583] opened 2023-01-02 08:37 UTC
After an hour or so, yabai always stops responding.

[Sample of yabai.txt](https://github.com/koekeishiya/yabai/files/10330602/Sample.of.yabai.txt)

**Comment by koekeishiya** [comment] 2023-01-02 13:22
Something on your system is causing accessibility access to not work properly. Try to remove yabai from the accessibility permissions, reboot, and re-add it. If that doesn't help, maybe you have other software running that uses the accessibility API and is interfering in some way.

**Comment by bobsoppe** [comment] 2023-06-04 05:32
I seem to have the same kind of troubles, but only when I update yabai using homebrew. This is only happening on my M1 MacBook Air and not on a Intel MacBook

**Comment by bobsoppe** [comment] 2023-06-06 11:05
@koekeishiya, do I need to create a new ticket? What is the reason you closed this one?

**Comment by koekeishiya** [comment] 2023-06-06 11:13
The issue is described in my comment above. Permissions on macOS are finicky and not always respected depending on whether the binary is codesigned or not. If you use the prebuilt binaries that I ship they will be codesigned using the same certificate and should work fine. If you build from source go look at the wiki instructions to avoid this issue.

**Comment by bobsoppe** [comment] 2023-06-06 11:28
I am using the prebuilt binaries, so that should not be the problem, correct? Is there any way to debug what the issue exactly is?

**Comment by koekeishiya** [comment] 2023-06-06 11:35
Can you provide a log of the sample output when this "non responding" state occurs? The only thing that could theoretically be a problem is that we deadlock the AX API between two threads; as seen in the log posted by the OP

```    2647 Thread_13480509   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2647 start  (in dyld) + 2544  [0x1b2043e50]
    +   2647 main  (in yabai) + 2128  [0x102d3ba5c]
    +     2647 CFRunLoopRunSpecific  (in CoreFoundation) + 612  [0x1b244a878]
    +       2647 __CFRunLoopRun  (in CoreFoundation) + 2264  [0x1b244b8a4]
    +         2647 __CFRunLoopDoSource1  (in CoreFoundation) + 520  [0x1b244ceb8]
    +           2647 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__  (in CoreFoundation) + 60  [0x1b244cf98]
    +             2647 mshMIGPerform  (in HIServices) + 204  [0x1b7bd2ba8]
    +               2647 _XPostNotification  (in HIServices) + 392  [0x1b7c1b75c]
    +                 2647 _XXMIGPostNotification  (in HIServices) + 888  [0x1b7bf0b64]
    +                   2647 application_notification_handler  (in yabai) + 788  [0x102d2abc4]
    +                     2647 _AXUIElementGetWindow  (in HIServices) + 204  [0x1b7bf00fc]
    +                       2647 getServerPortFromCache  (in HIServices) + 44  [0x1b7beab0c]
    +                         2647 _os_nospin_lock_lock_slow  (in libsystem_platform.dylib) + 140  [0x1b239a87c]
    +                           2647 __ulock_wait  (in libsystem_kernel.dylib) + 8  [0x1b232fb24]
    2647 Thread_13480517
    + 2647 thread_start  (in libsystem_pthread.dylib) + 8  [0x1b2367e2c]
    +   2647 _pthread_start  (in libsystem_pthread.dylib) + 148  [0x1b236d06c]
    +     2647 event_loop_run  (in yabai) + 152  [0x102d175e8]
    +       2647 EVENT_HANDLER_APPLICATION_LAUNCHED  (in yabai) + 436  [0x102d3c1a8]
    +         2647 application_observe  (in yabai) + 168  [0x102d2a810]
    +           2647 _AXObserverAddNotificationAndCheckRemote  (in HIServices) + 56  [0x1b7bef5ec]
    +             2647 _AXObserverAddNotification  (in HIServices) + 556  [0x1b7bef35c]
    +               2647 getServerPortFromCache  (in HIServices) + 312  [0x1b7beac18]
    +                 2647 CFMachPortSetInvalidationCallBack  (in CoreFoundation) + 264  [0x1b2445acc]
    +                   2647 portInvalidationCallback  (in HIServices) + 32  [0x1b7bf1280]
    +                     2647 _os_nospin_lock_lock_slow  (in libsystem_platform.dylib) + 140  [0x1b239a87c]
    +                       2647 __ulock_wait  (in libsystem_kernel.dylib) + 8  [0x1b232fb24]
```

However I don't see why none of them would release the lock when they finish; there is no reason for it to just hang there. As you see in that stack trace it is deep into the AX API handling.

I have never since the development started like 5years ago had this issue on my machines, so I am not particularly convined that there is a bug here.

In any case, the fix to what I observed here would be to move the calls `ax_window_id` away from https://github.com/koekeishiya/yabai/blob/master/src/application.c#L3 and into the event handler itself, to avoid a potential threading issue.

**Closed** 2023-06-09 14:42 UTC
