### ISSUE TITLE
Autoreload sometimes

### ISSUE THREAD

**Issue by capitanBOBO** [koekeishiya/yabai#1395] opened 2022-09-07 07:12 UTC
Yabai reloading sometimes, reset all windows according rules in yabairc. It's happening after closing window or after changing space(not via yabai space focus). Maybe it's happening because fatass xcode just destroying my CPU. Monterey, Intel

**Comment by koekeishiya** [comment] 2022-09-23 01:25
Sounds like a crash, Check `Console.app` and `Crash Reports`.

**Comment by capitanBOBO** [comment] 2022-09-26 08:27
> Sounds like a crash, Check `Console.app` and `Crash Reports`.

Sorry can't understand what I should do. It's about yabai err log? It's empty, don't have any errors

**Comment by kpritam-tw** [comment] 2022-10-14 14:10
I seeing the same issue.

**Comment by kvndrsslr** [comment] 2022-10-14 15:06
@koekeishiya hope this helps

```json
{"app_name":"yabai","timestamp":"2022-10-14 16:58:02.00 +0200","app_version":"","slice_uuid":"0caeb122-a126-3c17-8a3d-8040c9654c77","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"D226025E-DA06-453B-BDA6-9A4F466B1FF6","name":"yabai"}
{
  "uptime" : 130000,
  "procLaunch" : "2022-10-13 12:23:49.1331 +0200",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac20,2",
  "procStartAbsTime" : 29449640186653,
  "coalitionID" : 679,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-14 16:58:01.9942 +0200",
  "incident" : "D226025E-DA06-453B-BDA6-9A4F466B1FF6",
  "bug_type" : "309",
  "pid" : 57898,
  "procExitAbsTime" : 132298880663858,
  "cpuType" : "X86-64",
  "procName" : "yabai",
  "procPath" : "\/usr\/local\/opt\/yabai\/bin\/yabai",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "homebrew.mxcl.yabai",
  "crashReporterKey" : "D70781EE-C5E8-7FD1-576B-7B4736DFDC69",
  "bridgeVersion" : {"build":"19P6067","train":"6.6"},
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":2,"thread_set_state":0,"task_for_pid":2},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 1,
  "threads" : [{"id":1687790,"queue":"com.apple.main-thread","frames":[{"imageOffset":6522,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":0},{"imageOffset":7400,"symbol":"mach_msg","symbolLocation":56,"imageIndex":0},{"imageOffset":525165,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":1},{"imageOffset":518648,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":1},{"imageOffset":515644,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":1},{"imageOffset":177924,"symbol":"main","symbolLocation":1972,"imageIndex":2},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":3}]},{"triggered":true,"id":1687818,"threadState":{"r13":{"value":105553169055760},"rax":{"value":0},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":6},"rsi":{"value":6},"r8":{"value":140703302058214,"symbolLocation":0,"symbol":"reset_window"},"cr2":{"value":140336918691896},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":70},"r15":{"value":22},"rbx":{"value":123145440854016},"trap":{"value":133},"err":{"value":33554760},"r11":{"value":582},"rip":{"value":140703216877582,"matchesCrashFrame":1},"rbp":{"value":123145440851152},"rsp":{"value":123145440851112},"r12":{"value":42759},"rcx":{"value":123145440851112},"flavor":"x86_THREAD_STATE","rdi":{"value":42759}},"frames":[{"imageOffset":32782,"symbol":"__pthread_kill","symbolLocation":10,"imageIndex":0},{"imageOffset":25087,"symbol":"pthread_kill","symbolLocation":263,"imageIndex":4},{"imageOffset":531748,"symbol":"abort","symbolLocation":123,"imageIndex":5},{"imageOffset":1290810,"symbol":"iterator_seek","symbolLocation":220,"imageIndex":6},{"imageOffset":1292168,"symbol":"SLSWindowIteratorGetTags","symbolLocation":32,"imageIndex":6},{"imageOffset":98532,"symbol":"window_tags","symbolLocation":132,"imageIndex":2},{"imageOffset":95707,"symbol":"window_serialize","symbolLocation":491,"imageIndex":2},{"imageOffset":127270,"symbol":"window_manager_query_windows_for_spaces","symbolLocation":470,"imageIndex":2},{"imageOffset":58688,"symbol":"handle_message","symbolLocation":29600,"imageIndex":2},{"imageOffset":206447,"symbol":"EVENT_HANDLER_DAEMON_MESSAGE","symbolLocation":319,"imageIndex":2},{"imageOffset":15630,"symbol":"event_loop_run","symbolLocation":158,"imageIndex":2},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":4},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":4}]},{"id":1687869,"frames":[{"imageOffset":32914,"symbol":"__accept","symbolLocation":10,"imageIndex":0},{"imageOffset":74380,"symbol":"message_loop_run","symbolLocation":60,"imageIndex":2},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":4},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":4}]},{"id":8494567,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":8495739,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":8497311,"frames":[{"imageOffset":8008,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703216844800,
    "size" : 229376,
    "uuid" : "8cc28466-fd2f-3c80-9834-9525b7beac19",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 140703217389568,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5255168,
    "uuid" : "93c48919-68af-367e-9a67-db4159bc962c",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4327485440,
    "size" : 245760,
    "uuid" : "0caeb122-a126-3c17-8a3d-8040c9654c77",
    "path" : "\/usr\/local\/Cellar\/yabai\/5.0.1\/bin\/yabai",
    "name" : "yabai"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4434374656,
    "size" : 442368,
    "uuid" : "71febccd-d9dc-3599-9971-2b3407c588a8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703217074176,
    "size" : 49152,
    "uuid" : "b5454e27-e8c7-3fdb-b77f-714f1e82e70b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703215828992,
    "size" : 561152,
    "uuid" : "e42e9d7a-03b4-340b-b61e-dcd45fd4acc0",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703300767744,
    "CFBundleShortVersionString" : "1.600.0",
    "CFBundleIdentifier" : "com.apple.SkyLight",
    "size" : 3796992,
    "uuid" : "6563e632-526d-3c88-8035-049fcca8ca93",
    "path" : "\/System\/Library\/PrivateFrameworks\/SkyLight.framework\/Versions\/A\/SkyLight",
    "name" : "SkyLight"
  }
],
  "sharedCache" : {
  "base" : 140703213817856,
  "size" : 19331678208,
  "uuid" : "73669942-bd8a-3e40-951f-7fbe07b51cb8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=846.6M resident=0K(0%) swapped_out_or_unallocated=846.6M(100%)\nWritable regions: Total=3.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=3.1G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG backing stores                317.9M        9 \nColorSync                          204K       23 \nCoreGraphics                         8K        2 \nKernel Alloc Once                    8K        1 \nMALLOC                           629.5M       91 \nMALLOC guard page                   24K        5 \nMALLOC_MEDIUM (reserved)           1.8G       16         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nObjC additional data                15K        1 \nSTACK GUARD                       56.0M        6 \nStack                             10.5M        6 \nVM_ALLOCATE                       4832K       27 \n__CTF                               756        1 \n__DATA                            17.4M      283 \n__DATA_CONST                      12.0M      167 \n__DATA_DIRTY                       534K       98 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       645.4M        8 \n__TEXT                           201.2M      303 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                       45.9M       11 \nshared memory                      776K       15 \n===========                     =======  ======= \nTOTAL                              4.0G     1078 \nTOTAL, minus reserved VM space     1.9G     1078 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000020
    }
  ],
  "experiments" : [

  ]
}
}

```

**Comment by koekeishiya** [comment] 2022-10-14 17:40
duplicate of #1475

**Closed** 2022-10-26 09:12 UTC
Labels: duplicate
