### ISSUE TITLE
"window_created" event won't automatically float windows

### ISSUE THREAD

**Issue by joshtwo** [koekeishiya/yabai#818] opened 2021-02-01 03:56 UTC
I have this code in my Yabai config:

```zsh
# float all non-resizable windows by default
float_script='if [ `yabai -m query --windows --window $YABAI_WINDOW_ID | jq ".resizable == 0"` = "true" ]; then yabai -m window $YABAI_WINDOW_ID --toggle float; fi'

yabai -m signal --add event=window_created label=autofloat_fixed_windows action="$float_script"
```

Here's the action in my signal list:
```
~ > yabai -m signal --list
[{
	"index":0,
	"label":"autofloat_fixed_windows",
	"app":"",
	"title":"",
	"event":"window_created",
	"action":"if [ `yabai -m query --windows --window $YABAI_WINDOW_ID | jq \".resizable == 0\"` = \"true\" ]; then yabai -m window $YABAI_WINDOW_ID --toggle float; fi"
},{
	"index":1,
	"label":"",
	"app":"",
	"title":"",
	"event":"dock_did_restart",
	"action":"sudo yabai --load-sa"
}]
```

If I run the action manually in sh after setting YABAI_WINDOW_ID, it works.
```
sh-3.2$ YABAI_WINDOW_ID=`sleep 2 && yabai -m query --windows --window mouse | jq .id`
sh-3.2$ echo $YABAI_WINDOW_ID
70576
sh-3.2$ if [ `yabai -m query --windows --window $YABAI_WINDOW_ID | jq ".resizable == 0"` = "true" ]; then yabai -m window $YABAI_WINDOW_ID --toggle float; fi
sh-3.2$
```

However, nothing seems to happen when I create a non-resizable window, which I test via the System Preferences app. Is there anything obvious I'm doing wrong here or is this not working correctly?

**Comment by koekeishiya** [comment] 2021-02-01 12:45
You need to also subscribe to the application_launched signal for the initial window event of the main window. This is resolved in the `the-future` branch, ref #581. The mentioned branch includes breaking changes and more breaking changes will come, hence the branch name. No ETA for when this will be finished as I have a lot of things I want to do there.

**Comment by joshtwo** [comment] 2021-02-02 04:17
Yeah, that fixed it. Thanks a lot! I held off 2 or 3 OS X updates just to be sure I could safely leave chunkwm for this, so I really value all the work that went into this.

**Comment by koekeishiya** [comment] 2021-05-06 18:28
Closing as duplicate of #581

**Closed by koekeishiya** 2021-05-06 18:28 UTC
