### ISSUE TITLE
Sluggish on Chromium-based browser (when immediately switching to another tab after opening a new tab)

### ISSUE THREAD

**Issue by yanzhang0219** [koekeishiya/yabai#469] opened 2020-04-03 03:23 UTC
Hi,
I have been experiencing this issue for a long time when using yabai. 

The thing is: in Chrome, open a new tab by clicking the "+" button and then **immediately** click the tab next to it on its left. There is a significant delay to switch to that tab (around 1\~2 seconds). Also, similarly, after I open a new tab, I immediately click the "x" button of the tab next to it instead of the tab itself, this tab will be closed after 1~2 seconds. 

However, if I stop the yabai service (by running `brew services stop yabai`), the issue I described above is gone and the smooth is back. 

Except for Chrome, I have tried other Chromium-based browsers such as Brave, and all of them have the same issue. I also tried Firefox and Safari but both of them performed very well as normal. 

I don't know how to investigate the source of this issue. Please do me a favor. Thank you very much.

yabai version: the latest
macOS: 10.15.3 (the latest)

**Comment by koekeishiya** [comment] 2020-04-03 14:59
So this appears to be happening because Chrome sends a ton of *window title changed* notification, which causes yabai to trigger a status bar update, which is a bit of an expensive operation:

```
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 5042
```

After disabling the status bar I could no longer reproduce this issue.

**Comment by koekeishiya** [comment] 2020-04-03 19:58
I mostly use Safari. Sometimes I'll use Chrome, but I interact mostly using keyboard shortcuts (for creating, closing and moving between tabs), so I don't really experience this slowdown.

**Comment by yanzhang0219** [comment] 2020-04-03 20:07
Got it. Thank you.

**Comment by koekeishiya** [comment] 2020-04-14 16:16
Think I found a way to solve this issue (ref #376). Please try the latest master.

**Comment by yanzhang0219** [comment] 2020-04-14 20:14
@koekeishiya Bingo!! It seems this issue is totally solved. I tested using Chrome and other Chromium-based browsers (Brave and Chromium). All of them were very smooth when I tried to reproduce this issue. Not sluggish at all when I open a new tab and immediately try to close a previous tab. Good job!

Thank you so much for your effort and make our life easier. :P

**Closed** 2020-04-14 21:18 UTC
Labels: addressed not released, performance, question
