### ISSUE TITLE
stack "flickers" after a new window is added to the stack and focus is moved back and forth

### ISSUE THREAD

**Issue by grozan** [koekeishiya/yabai#791] opened 2021-01-11 13:42 UTC
Hi,

I have a little problem with stacks, which I hope can be solved because it's quite annoying
Let me try to describe how to reproduce it.

Let's suppose a space, with only 3 terminal windows, side by side. 
Let's call them `w1`, `w2` and `w3`

1. go into `w1`, and stack it on top of `w2`, with (supposing 39410 is the id of `w2`)
```
yabai -m window 39410 --stack `yabai -m query --windows --window | jq '.id'`
```
The 2 windows are "merged", and the focus is in the new stack
So now we have one stack with `w1` (visible) and `w2` ("behind"), and a single `w3` window next to it 

2. from the same `w1` window (now in the stack), move the focus to the other window left (`w3`)
```
yabai -m window --focus east
``` 
The focus moves and you're now in `w3`. You see `w1` (unfocused) and `w3` on the screen

3. finally, move the focus back to the stack
```
yabai -m window --focus west
``` 
Here the problem happens. When the focus changes, back to the stack, `w1` disappears and `w2` is shown instead.
`w2` became the "front window of the stack", all by itself.
This is the 'flicker' effect I'm trying to describe here

Note that this does NOT happen if the focus is moved back and forth using the mouse
It happens only when the focus is moved using command-line calls (or keyboards bindings for the same commands in skhd)

is it only me, or can others reproduce it too?
Thanks!

**Comment by tshu-w** [comment] 2021-02-13 08:45
same issues here.

**Comment by mikalcallahan** [comment] 2021-02-17 17:14
I run into the same issue, but it seems to happen only with iTerm for me.

**Comment by koekeishiya** [comment] 2022-09-23 00:46
Duplicate of  #1311 and fixed on master.

**Closed by koekeishiya** 2022-09-23 00:46 UTC
