### ISSUE TITLE
Hiding an untiled window keeps the border visible

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/yabai#311] opened 2019-11-12 13:46 UTC
Hiding a program with CMD+H keeps the border visible, tried it with spotify and mail etc. Minimizing works like i would expect.

**Comment by koekeishiya** [comment] 2019-11-12 16:04
Works just fine for me; tested with Spotify also.

**Comment by brorbw** [comment] 2019-11-12 20:10
I have this rule for spotify
`yabai -m rule --add app=Spotify manage=off`

**Comment by brorbw** [comment] 2019-11-14 12:27
[Image of spotify open](https://imgur.com/k783w8m)
[Image of spotify closed](https://imgur.com/8fFeHB2)
I looked at the logs and they didn't really say anything. I can't remember if you have different log levels.

**Comment by koekeishiya** [comment] 2019-11-14 17:42
There is no concept of logging levels. You can enable logging by launching yabai with the `--verbose` argument. On master I've made it possible to enable/disable debug output at runtime using the command: `yabai -m config debug_output on | off`.

**Comment by brorbw** [comment] 2019-11-14 18:37
That pretty much the definition of two logging levels. I will check logs tomorrow. I believe it's an event that doesn't trigger the right action. I also happens with iTerm and they are tiled.

**Comment by koekeishiya** [comment] 2019-11-14 20:30
>That pretty much the definition of two logging levels.

I suppose you could say that. When levels are mentioned I associate that with systems that control the granularity of the available logging output instead of simply having it be on/off.

On another note I tried to reproduce the issue while using the rule you provided, and it still works just fine for me; having Spotify running while yabai is started, and vice versa, both turned out fine.

Maybe try resetting the accessibility permissions or something.

**Comment by koekeishiya** [comment] 2020-01-19 17:04
I still cannot reproduce this, closing.

**Closed by koekeishiya** 2020-01-19 17:04 UTC
Labels: help wanted, undetermined
