### ISSUE TITLE
Windows randomly get shrunk

### ISSUE THREAD

**Issue by eramdam** [koekeishiya/yabai#289] opened 2019-10-20 05:15 UTC
- yabai 2.0.1
- macOS 10.14.6

Sometimes (but it's not consistent and I can't make it what triggers it, nothing comes out in yabai's logs) the window that needs to be focused after another window is removed from a space gets shrunk to a very small size but the space it would take is still allocated. The only workaround I found when this happens is to swap another window with the shrunk one or, in the worst cases, reset the layout of the space.

![Screen Shot 2019-10-19 at 10 09 13 PM](https://user-images.githubusercontent.com/1409924/67155108-8411a380-f2bd-11e9-99d8-6aac81275af9.png)

Sorry for the non very descriptive issue but that's all I have 🙇

**Comment by synthetiv** [comment] 2019-10-20 14:57
I've had this happen a few times too. FWIW, I can only remember it happening to Firefox windows, and that looks like FF in your screenshot as well. Like you say, it seems to be a very temporary problem -- I think I've fixed it in the past by just toggling `zoom-parent` or `float` on the tiny window.

**Comment by eramdam** [comment] 2019-10-20 22:31
Hum, I've definitely seen this happen to other apps like VSCode so I don't think it's somehow specific to Firefox.

**Comment by koekeishiya** [comment] 2019-10-29 07:42
Sounds like a bug, but I'm going to need steps to reproduce before I can do anything about this, as I have not experienced this problem in my day to day usage.

**Comment by eramdam** [comment] 2019-10-29 17:54
I don't have real repro steps. I'll try to be cautious of what I'm doing/what situation I'm in when this happens and report back here.

**Comment by koekeishiya** [comment] 2019-10-29 20:30
If you are running with the `--verbose` launch argument you already have max logging output.

**Comment by eramdam** [comment] 2019-10-29 23:38
> If you are running with the `--verbose` launch argument you already have max logging output.

I didn't know about that flag! I'll run yabai with that flag and try to scoop the logs the next time this bug happens.

**Comment by eramdam** [comment] 2019-11-05 19:28
Okay, I _finally_ managed to catch that bug while having verbose logs. Here's a gist with the relevant logs https://gist.github.com/eramdam/9190489024613b4ae6a65ba8f773a93f

The log is a bit noisy because of my Ubersitch widgets requesting the spaces information every few seconds but hopefully that can help trace down what's happening exactly when that bug happens.

Weirdly enough, this time the window was shrunk only horizontally (very tall and narrow) instead of being shrunk to a small square? 🤷‍♂

**Comment by koekeishiya** [comment] 2019-11-12 16:44
I'm 96% certain this is caused by usage of parent/fullscreen zoom. What happens is that when a window in a nested tree is zoomed, and the upper-part of the tree is modified by adding or removing nodes, we end up in a situation where it is possible for the zoomed window' pointer to become invalid, yet it is not being reset.

**Comment by koekeishiya** [comment] 2019-11-12 17:05
The issue regarding zoom interaction has been fixed on master. I'll assume that was the issue in this case. If you could run from master for some time and let me know if this issue occur for you again, or stop occurring (after x amount of days/weeks).

**Comment by eramdam** [comment] 2019-11-12 17:43
@koekeishiya I'll try that and let you know how it goes!

**Comment by eramdam** [comment] 2019-11-12 18:01
Completely unrelated but I want to flag this so it doesn't fly above someone's head.

I had a pretty scary/weird issue where, if yabai 2.1.x doesn't have the Accessibility permission it...seems to completely freeze the window server and basically the whole macOS GUI stops responding to click/keyboard events? I can't tell yet if it's either yabai, skhd or a weird combination of the two but I had this happen on my home machine (2.1.0) on which I didn't do anything except upgrade yabai) and my laptop (master) on which I (stupidly :P ) removed the yabai binary from the accessibility permissions, not noticing that it tried to launch at the same time.

Maybe I was just unlucky and that report can be discarded but just wanted to flag this out just in case because it's kinda disturbing when it happens.

**Comment by eramdam** [comment] 2019-11-26 02:01
@koekeishiya I haven't seen the issue even since I started running off `master`. I think we can close it, thanks for investigating/fixing this issue 🙇

**Comment by koekeishiya** [comment] 2019-11-29 10:14
> I haven't seen the issue even since I started running off master. I think we can close it, thanks for investigating/fixing this issue 🙇

That's great.

> I had a pretty scary/weird issue where, if yabai 2.1.x doesn't have the Accessibility permission it...seems to completely freeze the window server and basically the whole macOS GUI stops responding to click/keyboard events?

I have actually not had this happen with yabai and/or skhd, but i have seen this with other applications that require accessibility access. The only fix I had was to force-shutdown my mac using the powerbutton.

I did however manage to reliably reproduce the problematic situation with the following steps:

1. Grant w/e application access to the accessibility API.
2. Launch application that requires accessibility access, and leave it running.
3. While the application is still running, uncheck the box in the accessbility permissions window.
4. Force-shutdown mac.

I don't know if these same steps will trigger this issue for every system or even every application, but it did happen every time with the application i was testing for.

I don't actually know what can be done to prevent this from happening.

**Closed** 2019-11-29 16:52 UTC
Labels: bug
