### ISSUE TITLE
Joining a Zoom meeting with someone screen sharing causes Zoom to hang

### ISSUE THREAD

**Issue by askreet** [koekeishiya/yabai#349] opened 2019-12-20 12:58 UTC
Steps to reproduce:

* Leave default setting General > Enter full screen when a participant shared their screen
* Join a [Zoom](https://zoom.us/) meeting in progress where a participant is sharing their screen.

Outcome:

* Window starts to enter native Mac OS X full-screen mode (by creating a new desktop and consuming the whole thing), but becomes unresponsive to input.
* You cannot interact with Zoom
* You can switch out of Zoom using Mission Control to select your previous desktop.

System Details:

* MacBook Pro 15" 2018, lid closed, two external displays via USB-C->DP and USB-C->Hub->HDMI.
* 2.2 GHz i7, 16 G RAM, Radeon Pro 555X + Intel HD
* SIP disabled, latest yabai from brew and extensions updated as of yesterday.

Workaround:

* Disable the configuration setting above and leave Zoom windowed.

This only happens when I am using yabai -- is there further debugging I can gather to see if it's fixable within yabai or an issue with Zoom? In general, I have no issues sending any window into native full-screen mode.

Personally, I am quite happy to leave this config set, but thought it might be a more general issue worth investigating.

**Comment by dominiklohmann** [comment] 2019-12-20 13:09
That's a pretty good bug report already.

What you can also do, and what I've done for a while now—which is why I haven't noticed this bug before—, is running `yabai -m rule --add app='^zoom\.us$' native-fullscreen=on` to always have Zoom in fullscreen mode.

If you want to investigate further, try looking at the output of window queries and look if anything's weird with Zoom when it's in the broken state:

```sh
# list all windows that yabai manages, and filter by app name
yabai -m query --windows | jq 'map(select(.app == "zoom.us"))'
```

You can also enable debug output for yabai and look at the log files (paths below shown as set when installed with Homebrew).

```sh
# enable verbose/debug logs
yabai -m config debug_output on

# monitor error log
tail -f /usr/local/var/log/yabai/yabai.err.log 

# monitor output log
tail -f /usr/local/var/log/yabai/yabai.out.log
```

**Comment by koekeishiya** [comment] 2019-12-20 13:14
>  latest yabai from brew

I assume this is release v2.1.3? This issue seems like it could be fairly similar to #339. Can you try to reproduce this when running from the master branch?

**Comment by askreet** [comment] 2019-12-20 13:22
> I assume this is release v2.1.3?

Correct.

> it could be fairly similar to #339

Hmm, one thing I did not mention in the report is that Zoom actually continues to _run_, I can see video updates (though the video is not yet fullscreen, it halts in the middle of that animation), and hear audio, I just get a beachball and cannot interact with the UI. I'm assuming pegged CPU would be more impactful, but maybe not.

I don't know if I'll have time to switch over to the master branch before work this morning -- does that require compiling locally?

> try looking at the output of window queries and look if anything's weird with Zoom when it's in the broken state

I'll see if I can reproduce it during any of this morning's meetings... :-)

**Comment by koekeishiya** [comment] 2019-12-20 13:25
There is a brew option to install from the master branch. It will compile for you, but there are no external dependencies except for the macOS frameworks themselves, so that should not be an issue.

Simply uninstall the brew version you have and install from head. Something like
```
brew services stop yabai
brew uninstall yabai
brew install --HEAD yabai
```

You probably need to reinstall the scripting-addition if you install from HEAD.
Changes can be found here: https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md

**Comment by askreet** [comment] 2019-12-23 12:37
You know it figures, I joined probably 4 meetings on Friday and could not reproduce it (without changing anything).

**Comment by dominiklohmann** [comment] 2019-12-23 15:12
Closing this as a duplicate then.

Duplicate of #339

**Closed** 2019-12-23 15:13 UTC
Labels: duplicate
