### ISSUE TITLE
[BUG] Change Focus in stacked windows does not work

### ISSUE THREAD

**Issue by cauliyang** [koekeishiya/yabai#1896] opened 2023-10-11 16:51 UTC
# Problem Description

When I use stacked mode for all windows in one desktop, `yabai -m windows --focus stack.prev` will change stacked windows. 
However, When I use bsp and stacked mode together,  `yabai -m windows --focus stack.prev` cannot change focus for stacked windows.

For example, 

![image](https://github.com/koekeishiya/yabai/assets/38903141/893c6c4b-d900-4d90-80ca-1450f83ecd4c)

Now I have two stacked windows on my right window, but I cannot change focus for the two stacked windows.

Thanks for your help in advance!

- Version: 6.0 
- System: Sonoma

- Configuration:
```

# global settings
yabai -m config \
	mouse_follows_focus on \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_topmost on \
	window_shadow float \
	window_animation_duration 0.0 \
	window_opacity_duration 0.3 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 06 \
	layout bsp mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action stack
```

**Comment by bigforcegun** [comment] 2023-10-12 06:56
Same thing for me 👋

I use universal command for navigate on different layouts (bsp + stack on different spaces)

```
ctrl - up : yabai -m window --focus north || yabai -m window --focus stack.next || yabai -m window --focus stack.first
ctrl - down : yabai -m window --focus south || yabai -m window --focus stack.prev || yabai -m window --focus stack.last
```

I have finder and alacritty at same stack, and after I call `yabai -m window --focus stack.prev` at alacritty - alacritty loses focus, but finder do not float up at front

<img width="1415" alt="image" src="https://github.com/koekeishiya/yabai/assets/264697/9fbce574-8513-406d-80a0-96c0f3a79a9d">

**Comment by koekeishiya** [comment] 2023-10-24 14:57
Duplicate of #1918

**Closed by koekeishiya** 2023-10-24 14:57 UTC
