### ISSUE TITLE
brew reinstall yabai wants full xcode

### ISSUE THREAD

**Issue by Bellavene** [koekeishiya/yabai#1130] opened 2022-01-19 21:29 UTC
Trying to reinstall HEAD version and getting this:
` brew reinstall koekeishiya/formulae/yabai
yabai: A full installation of Xcode.app 13.1 is required to compile
this software. Installing just the Command Line Tools is not sufficient.`

I don't want to install Xcode any advice?

**Comment by 24unix** [comment] 2022-01-19 21:31
Don’t use brew.
But why should one not want to have Xcode on his computer?
I even have it on my MacBook.

**Comment by Bellavene** [comment] 2022-01-19 21:43
Because I don't want another 50Gb used by mostly useless software for me. I am not a coder, do other stuff.

**Comment by 24unix** [comment] 2022-01-19 21:52
17G	/Applications/Xcode.app

**Comment by Bellavene** [comment] 2022-01-19 22:06
And bunch of other stuff around. Just take it that not everyone wants even 17Gb to be used for a software that you use one time in a decade.

**Comment by ywwry66** [comment] 2022-01-20 03:34
See the following comments:
https://github.com/koekeishiya/yabai/issues/1054#issuecomment-1014859787
https://github.com/koekeishiya/yabai/issues/1054#issuecomment-1015872654

**Comment by koekeishiya** [comment] 2022-01-21 16:33
I have tried looking into this, but honestly the Homebrew formula documentation is a mess and I can't be bothered spending more hours on this. If someone knows the appropriate way to say that a specific version of the macOS SDK/CLT must be installed for the `--HEAD` option to work, please let me know.

**Comment by typkrft** [comment] 2022-01-21 18:09
Bear in mind I'm not a developer, but I also looked through that documentation and couldn't figure out much about how work with dependencies, but maybe something hacky like this would suffice? Just an example.

```RUBY
  def clt_check
    clt = `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version | cut -c 10-13`.to_f
    puts clt
    if clt <= 13.1
      onoe "Yabai HEAD requires Command Line Tools >= 13.1"
    else 
      puts "CLT Up-To-Date Continuing..."
      system "make", "-j1", "install"
    end
  end

  def install
    (var/"log/yabai").mkpath
    man.mkpath

    if build.head?
      clt_check()
    end

    bin.install "#{buildpath}/bin/yabai"
    (pkgshare/"examples").install "#{buildpath}/examples/yabairc"
    (pkgshare/"examples").install "#{buildpath}/examples/skhdrc"
    man1.install "#{buildpath}/doc/yabai.1"
  end
```

**Comment by typkrft** [comment] 2022-01-21 20:36
Maybe [fails_with](https://docs.brew.sh/Formula-Cookbook#compiler-selection) would be useful?  

> fails_with declarations can be used with any of :gcc, :llvm, and :clang. Homebrew will use this information to select a working compiler (if one is available).

```RUBY
## Failing with a certain compiler?

# If it is failing for certain compiler:
fails_with :llvm do # :llvm is really llvm-gcc
  build 2334
  cause "Segmentation fault during linking."
end

fails_with :clang do
  build 425
  cause "multiple configure and compile errors"
end
```

**Comment by neerajklite** [comment] 2022-01-22 14:10
How to get around this issue ? I am not able to install yabai :/

**Comment by typkrft** [comment] 2022-01-22 14:57
> How to get around this issue ? I am not able to install yabai :/

First, this is probably a bad idea for a number of reasons, but namely because I may be misunderstanding the requirements and/or the formula may change in the future. If you try this your mileage may vary. This is a temporary work around at best, do not use it to update. When this issue is resolved or you need to update. Completely uninstall and update from the repo again.

1. Update your command line tools. I believe this is done with `softwareupdate --install -a`
2. Check that the version of CLT is 13.1 or greater with `brew config`. I believe if it's greater than `13.1` you should be good to proceed. 
3. Download the homebrew formula from the repo [here](https://github.com/koekeishiya/homebrew-formulae/blob/master/yabai.rb)
4. Comment out [this](https://github.com/koekeishiya/homebrew-formulae/blob/f56bd0140ab595cd3bded5f9b97ce06a3864bdee/yabai.rb#L9) line.
5. `brew install yabai yabai.rb  --head`

**Comment by neerajklite** [comment] 2022-01-22 15:30
Its contradictory , is it not ? the minimum os version is High_sierra, but it does not even support xcode 13

**Comment by typkrft** [comment] 2022-01-22 16:05
I think the XCode req was added for the latest version(s) of HEAD. Though where it's at in the formula would indicate it's required for every version. So I am not sure. I believe if not building in HEAD in general before the latest commit you would not need Xcode.

**Comment by Ndrocchietto** [comment] 2022-01-22 17:01
I have installed xcode, but still does not work and give the same error message

**Comment by koekeishiya** [comment] 2022-01-22 17:36
You need CLT 13.1 to compile from source, because of the addition of `NSScreen safeAreaInset` or whatever it is called. A precompiled binary should still run on High Sierra.

**Comment by koekeishiya** [comment] 2022-01-22 18:17
Likely fixed now in https://github.com/koekeishiya/yabai/commit/fe86f24a21772810cd186d1b5bd2eff84b2701a9 and https://github.com/koekeishiya/homebrew-formulae/commit/50f8b3528d5f66b9ec3a163bcd0fb9cc6a74e5c1

**Comment by Bellavene** [comment] 2022-01-22 18:23
Thank you. This thread was awesome to watch

**Comment by neerajklite** [comment] 2022-01-23 01:55
Thanks !!

**Comment by koekeishiya** [comment] 2022-01-23 14:16
You need an XCode or CLT version that is capable of building a universal binary, if you want to build from source with the provided makefile. If that is not possible on Catalina, you need to edit the makefile or somehow force brew to build an x86_64 image only.

**Comment by koekeishiya** [comment] 2022-01-26 16:47
Reverted whatever changes were made as it seems to cause problems for some configurations (that I cannot reproduce).I give up. Brew --HEAD will just remain fucked for people not running Monterey.

**Comment by FelixKratz** [comment] 2022-01-26 17:17
If the safe inset line is the only problem, why don't you wrap it in a pre-compiler check to see if monterey is used to compile:
```c
#if __MAC_OS_X_VERSION_MAX_ALLOWED >= 120000
  if (__builtin_available(macOS 12.0, *)) ...
#endif
```

**Comment by koekeishiya** [comment] 2022-01-26 17:21
Because I want the actual build to work on all macOS the specified versions regardless of which version it was compiled on; so I want brew to use the correct SDK instead.

**Comment by FelixKratz** [comment] 2022-01-26 17:49
In that case you could
```c
#if defined DEV || __MAC_OS_X_VERSION_MAX_ALLOWED >= 120000
  if (__builtin_available(macOS 12.0, *)) ...
#endif
```
and pass `-DDEV` to your development c flags. This way the people compiling from brew will be protected from this error and you can still compile the appropriate binary on all platforms when you do dev. But this is a hack at best till someone fixes brew.

**Closed** 2022-03-16 22:47 UTC
