### ISSUE TITLE
Creating new Finder tab tiles window in half

### ISSUE THREAD

**Issue by nfrankmai** [koekeishiya/yabai#389] opened 2020-01-27 19:26 UTC
When creating a new tab in a Finder window, Yabai partitions the existing window as if a new window has been created. This leave a window sized hole. 
 Example: 
<img width="1680" alt="Screen Shot 2020-01-27 at 2 25 14 PM" src="https://user-images.githubusercontent.com/56654617/73206403-d9591e80-4110-11ea-9632-16bfbe185104.png">

**Comment by koekeishiya** [comment] 2020-01-28 06:38
Duplicate of #68

**Closed by koekeishiya** 2020-01-28 06:38 UTC
