### ISSUE TITLE
`window_border_color` not rerendering(?) correctly

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#246] opened 2019-09-12 02:44 UTC
Demonstration (imgur, .mp4, **no** download): https://i.imgur.com/gT3WECU.mp4

I added a blue border to all windows for demonstration purposes, you can see that there is an artefact running through both VSCode windows (this happened over Firefox too so it's nothing to do with VSCode, therefore leading me to believe this is yabai based). Clicking into the window causes a repaint(?) and thus clears the blue line running over it (this is why I couldn't also show it over Firefox as I clicked into the window before recording this). I've noticed this a few times before with regards to hiding windows either with `COMMAND + H` or minimising with `COMMAND + M` and just general moving and swapping.

You can also see in-between the windows (look in-between Firefox and the bottom-left VSCode) you can see that even though the lines within the VSCode window are gone the line between in the `window_gap` is still there, which is clearly visible when I show the desktop as outlining some phantom window that doesn't exist/is minimised/hidden.

Additionally, showing the desktop leaves the `window_border_color` instead of hiding it.

**Comment by dominiklohmann** [comment] 2019-09-12 04:16
Likely duplicate of #201

In a situation like this, always query for all windows on the space and check for any invisible windows. 

```sh
# list all windows on the current soace
yabai -m query --windows --space
```

> Additionally, showing the desktop leaves the `window_border_color` instead of hiding it.

The Show Desktop function of Mission Control is just a transformation applied to all windows. It doesn't actually change the windows' frame, and I don't think there's a callback available for it, unless we were to subscribe to whatever `CoreDockSendNotification` writes to.

**Comment by koekeishiya** [comment] 2019-10-09 08:33
Duplicate of #201 or #250 

I have yet to find a way to detect when "show desktop" is activated/deactivated, so there is not much we can do there. Closing this as part duplicate, part unfixable.

**Closed by koekeishiya** 2019-10-09 08:33 UTC

**Comment by tsujp** [comment] 2019-10-09 08:37
@koekeishiya would a check for all windows on this current space being within the bounds of the edge of the screen be a good check?

**Comment by dominiklohmann** [comment] 2019-10-09 08:40
> would a check for all windows on this current space or all spaces being within the bounds of the edge of the screen be a good check? All windows are moved into that little buffer zone indicated by an inset.

All of the Mission Control features (including Show Desktop) are a visual transformation that's applied to all visible windows. It doesn't actually change any coordinates.

**Comment by tsujp** [comment] 2019-10-09 08:42
Ah yes whoops, I forgot you mentioned that.
