### ISSUE TITLE
MacOS Ventura remove space animation

### ISSUE THREAD

**Issue by xbladesub** [koekeishiya/yabai#1527] opened 2022-11-17 02:56 UTC
I just upgraded to macOS Ventura and realized that default macOS animation appeared again when I switch between apps which are on different spaces using skhd. Tried to update yabai - didn't help. csrutil status is disabled. Is there any way to completely remove space animation like it was on Monterey?

**Comment by rheaSPK** [comment] 2022-11-28 16:16
Are the scripting additions correctly installed? Maybe you need to reinstall them

**Comment by xbladesub** [comment] 2022-11-28 16:50
> Are the scripting additions correctly installed? Maybe you need to reinstall them

Tried already

**Comment by timhradil** [comment] 2022-12-01 23:30
You can check the 'Reduce Motion' option in Accessibility options which will create a fade animation that is slightly faster than the sliding animation.

**Comment by xbladesub** [comment] 2022-12-02 03:21
> You can check the 'Reduce Motion' option in Accessibility options which will create a fade animation that is slightly faster than the sliding animation.

'Reduce motion' it is not what Yabai does on macOS Monterey and older versions. Expected behavior - switch between spaces without any animation and delay at all. Now it doesn't work and I don't know how to fix it by myself

**Comment by timhradil** [comment] 2022-12-02 05:10
This is caused by the script addition injecting being broken on Ventura. This issue has been fixed and merged into master, but not released: https://github.com/koekeishiya/yabai/commit/206c0d6968210f48363f206526760e5750810a61.

You can install from HEAD using these steps from wiki: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

I found my yabai at this path: /opt/homebrew/Cellar/yabai/HEAD-206c0d6/bin/yabai. Rather than at /usr/local/bin/yabai as noted in the wiki.

**Closed** 2022-12-06 03:15 UTC
