### ISSUE TITLE
Getting Emacs to tile

### ISSUE THREAD

**Issue by karrot42** [koekeishiya/yabai#86] opened 2019-07-02 04:27 UTC
From a straight install Emacs won't tile with the rest of the windows, so I figured out that if I run

'yabai -m rule --add app=Emacs manage=on' after starting emacs it will tile with the other windows but I have 2 problems

1. How do I make this change permanent and consistent even after I restart yabai so I don't have to run the command every time
2. Although the Emacs window tiles, it when I navigate around the open windows (alt - h, alt - l) the Emacs window won't get selected, I must use the mouse to highlight it.

**Comment by dominiklohmann** [comment] 2019-07-02 04:53
> 1\. How do I make this change permanent and consistent even after I restart yabai so I don't have to run the command every time

Just put the rule in your yabairc—it's just an executable shell script after all. 



> 2\. Although the Emacs window tiles, it when I navigate around the open windows (alt - h, alt - l) the Emacs window won't get selected, I must use the mouse to highlight it.

Assuming you installed via brew, do you have anything possibly relevant in your log files when doing this? stderr gets redirected to ` /usr/local/var/log/yabai/yabai.err.log` (and similarly replace err with out for stdout). You can monitor this file using `tail -f /usr/local/var/log/yabai/yabai.err.log`.

An alternative would be to run `yabai --verbose` instead of the brew service to get a more detailed output, which should print why your windows cannot be selected.

Emacs has always been an issue, sadly.

**Comment by pcr910303** [comment] 2019-07-02 06:23
> Emacs has always been an issue, sadly.

Try using [emacs-mac](https://bitbucket.org/mituharu/emacs-mac) from the tap [emacsmacport](https://github.com/railwaycat/homebrew-emacsmacport).

It has **much** more better GUI support than the original, and a few additional features you might appreciate.

All this is due to GNU Emacs's main role being an AXTextField instead of AXWindow mentioned https://github.com/koekeishiya/chunkwm/issues/105#issuecomment-312619814. :-(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koekeishiya** [comment] 2019-07-02 11:16
Does *Emacs* not provide a good CLI alternative to its GUI version?

**Comment by karrot42** [comment] 2019-07-02 12:43
> Assuming you installed via brew, do you have anything possibly relevant in your log files when doing this? stderr gets redirected to ` /usr/local/var/log/yabai/yabai.err.log` (and similarly replace err with out for stdout). You can monitor this file using `tail -f /usr/local/var/log/yabai/yabai.err.log`.
> 
> An alternative would be to run `yabai --verbose` instead of the brew service to get a more detailed output, which should print why your windows cannot be selected.

There was no log file in `/usr/local/var/log/yabai/` and the --verbose didn't show anything unusual that I could notice

> Try using [emacs-mac](https://bitbucket.org/mituharu/emacs-mac) from the tap [emacsmacport](https://github.com/railwaycat/homebrew-emacsmacport).
> 
> It has **much** more better GUI support than the original, and a few additional features you might appreciate.

this will probably be my solution especially because there have always been some glitchiness with my emacs install with window resizing and what not, I'll give a try tomorrow.

> Does _Emacs_ not provide a good CLI alternative to its GUI version?

It has a CLI alternative but I think it lacks things like following links to open files and URLs in orgmode files, which I use pretty heavily.  I could be wrong about that though because I've only used CLI on a headless server in a pinch.

**Comment by qhuyduong** [comment] 2019-07-03 04:33
@karrot42 I'm using emacs-mac and still have the same problem. The simple fix is to add
```el
(menu-bar-mode t)
```
to configuration file. Hope it help!

**Comment by koekeishiya** [comment] 2019-07-03 09:49
Closing this then.

**Closed by koekeishiya** 2019-07-03 09:49 UTC
Labels: help wanted, question

**Comment by dominiklohmann** [comment] 2019-07-04 11:24
I added this information to the tips and tricks section of the wiki: https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#tiling-emacs

I have not tested whether this works as I don't use Emacs myself, but maybe this will help some [real programmers (xkcd)](https://xkcd.com/378/).

**Comment by jack836** [comment] 2019-07-31 09:16
Works on High Sierra when the following command was used to install
` ./configure --without-makeinfo --with-pop --with-mailutils --with-mac --enable-mac-app=/Applications`
I still have the following set   ` (menu-bar-mode -1)`

**Comment by mattsawyer77** [comment] 2019-08-08 18:56
I'm using emacs-mac with menu-bar-mode on. Yabai mostly works, but if I try to do `cmd+tab` to switch to emacs from another space, it moves emacs into the current space instead of switching. I haven't seen any other app do this.

**Comment by webframp** [comment] 2019-09-10 13:29
On macOS I use an emacs config based on [doom emacs](https://github.com/hlissner/doom-emacs) with [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) installed with these options: 
`brew install emacs-plus --with-no-titlebar --with-modern-icon --without-spacemacs-icon` and this has `(menu-bar-mode t)` set

I use this rule to contain emacs windows: `yabai -m rule --add app=Emacs manage=on space=2`

With this setup emacs tiles just fine using yabai and seems well behaved.

**Comment by oguzserbetci** [comment] 2019-09-19 21:55
@webframp your comment helped me tile emacs but I still can't get it to focus by using commands. I get `could not locate a southward managed window.` although I set

```
yabai -m rule --add app=Emacs manage=on
```

**Comment by brorbw** [comment] 2019-10-09 21:39
Hi, I have been a user of chunkwm and Emacs tiled just as all other programs. Today I installed yabai because a macOS update bricked my chunkwm installation. And everything works as before except Emacs.
Now i have installed a version of emacs called emacs-plus, which has a --with-no-titlebar option that removes the window decoration. The option `(menu-bar-mode t)` is stil set in emacs which means that what worked for everybody else have not worked for me.
I have also added a tiling rule for Emacs in .yabairc with no effect.
I digged a little bit and it seems like Emacs will tile when it is launched. It even reacts on resizing regardless which application is in focus. I can swap and move commands, but only Emacs is in focus, not when another application is in focus. The same applies for moving focus. I can use commands to move focus away from Emacs, but not to Emacs.

Below is my Emacs installation
```
brew tap d12frosted/emacs-plus
brew install emacs-plus --with-no-titlebar
```

**Comment by pcr910303** [comment] 2019-10-09 23:02
@brorbw 
Quoting the wiki... (emphasis mine)

> Emacs is not a well-behaved citizen of macOS. **Try using [&rightarrow;&nbsp;emacs-mac](https://bitbucket.org/mituharu/emacs-mac) from the Homebrew tap [&rightarrow;&nbsp;emacsmacport](https://github.com/railwaycat/homebrew-emacsmacport).**
>
> If Emacs is still not recognized by yabai, try enabling menu-bar-mode.

If you're using emacs-plus, you should set up a custom rule for it (which actually creates lots of problems relating to tooltips).

Please see [this](https://github.com/koekeishiya/yabai/issues/86#issuecomment-507537023), [this](https://github.com/koekeishiya/chunkwm/issues/105#issuecomment-312619814), [this](https://github.com/koekeishiya/chunkwm/issues/372), [this](https://github.com/koekeishiya/chunkwm/issues/270) for more info.

**Comment by webframp** [comment] 2019-10-10 03:44
@brorbw can you provide any more info on your emacs config? I use emacs-plus as I mentioned and have no tiling issues with it. It may be worth trying emacs-mac just to eliminate the cause of the issue

**Comment by pcr910303** [comment] 2019-10-10 08:32
> @pcr910303 I appreciate your answer but all of the above mentioned methods does not work for me. I like having the `--with-no-titlebar` option and i have been using it for age with chunkwm and i have had no problem.
> I had a custom rule for emacs before and i remember having a workaround for tooltips

Well, then I don't understand the question, why would you not add a custom rule for Emacs in your yabai init file?

> I will add that the official Homebrew install of emacs and emacs-plus does not work either.

Yes, as said, the official emacs and emacs-plus don't work without custom rules.

Try something like this (this doesn't consider tooltips): have checked working on macOS 10.15 Catalina with Emacs built on master.

```shell
yabai -m rule --add label=emacs app=Emacs manage=on
```

**Comment by d12frosted** [comment] 2019-12-30 06:36
Since `emacs-plus` is mentioned here several times, let me share a special option that should fix the window role:

```
$ brew install emacs-plus --with-window-role-fix
```

It's in 'experimental' state. And if it works reliably, I will make it on by default. Using it for several days (with yabai) and can confirm that doesn't require any special rules.

**Comment by brorbw** [comment] 2019-12-31 18:03
Does it also work with the `--no-title-bar` option?

**Comment by d12frosted** [comment] 2019-12-31 18:04
Yes, it works with `--with-no-titlebar` (please make sure that you use the right option 😸 ).

**Comment by brorbw** [comment] 2019-12-31 18:55
Yeah, I just wrote what was on the top of my head. Of course it's `--woth-no-titlebar`. 
Happy new year 🎉

**Comment by brorbw** [comment] 2020-01-03 01:15
> Well, then I don't understand the question, why would you not add a custom rule for Emacs in your yabai init file?

For completeness I will answer your question. I tried adding a custom rule for emacs-plus but it simply wouldn't work hence why I kept asking.

**Comment by picaschaf** [comment] 2020-01-03 12:35
> Since `emacs-plus` is mentioned here several times, let me share a special option that should fix the window role:
> 
> ```
> $ brew install emacs-plus --with-window-role-fix
> ```
> 
> It's in 'experimental' state. And if it works reliably, I will make it on by default. Using it for several days (with yabai) and can confirm that doesn't require any special rules.

Thank you for adding the option!
But one thing I observed is, that it only works when I start emacs from the commandline. If I start it from the finder or spotlight, it behaves broken as before. Do you have any idea what is influencing that?

**Comment by d12frosted** [comment] 2020-01-04 13:24
That option was merged and is not required anymore. Have fun :)

**Comment by picaschaf** [comment] 2020-01-04 17:21
> That option was merged and is not required anymore. Have fun :)

Was it recently merged? Yesterday I still had to add it for brew install.

**Comment by d12frosted** [comment] 2020-01-04 17:22
@picaschaf it was merged just minutes before I posted about it here. Here is relevant commit: https://github.com/d12frosted/homebrew-emacs-plus/commit/0017af1e7710ff833dfb2c061fe56660207ad0b7

**Comment by TomFaulkner** [comment] 2020-05-26 20:39
I know this is closed, but I still have this issue. I installed the Emacs plus from @d12frosted above, and have the rule, `yabai -m rule --add label=emacs app=Emacs manage=on`. However, I `yabai -m window --focus [direction]` skips over Emacs as if it wasn't there. Thankfully, it is tiling, however.

**Comment by brorbw** [comment] 2020-05-27 00:03
I do not have `lable=emacs` in my rule and it works fine. Could it be the flavour of emacs? I have installed `emacs-plus`

**Comment by TomFaulkner** [comment] 2020-05-28 18:34
That is the same Emacs I am using.

> I installed the Emacs plus from @d12frosted above

**Comment by d12frosted** [comment] 2020-05-29 07:31
@TomFaulkner I also use `emacs-plus` and I don't have any special rules for Emacs. And still it works well with `--focus` commands. AFAIR, it works regardless of Emacs version, but just for the sake of completeness, I am using Emacs 28. This is how I got my version:

```
$ brew install emacs-plus --without-spacemacs-icon --with-jansson --HEAD
```

**Comment by TomFaulkner** [comment] 2020-05-29 13:22
I was on 26.3, then tried 28 with the `--HEAD` option, but it couldn't read the Spacemacs `init.el` file for some reason. 27 works and Yabai treats it like other windows now. Thanks for the help.

**Comment by larionov** [comment] 2021-12-20 19:53
I installed emacs-plus `--with-no-titlebar`, 27, 28, 29 versions, but it still didn't want to tile.
What I found is that when I remove some package's initialization from the `.emacs` it tiles, but not every time. 
And what worked every time is when I restart the yabai service after starting Emacs. This way it always tiles.

**Comment by choco** [comment] 2021-12-23 11:56
I've also started using emacs recently, and even with proper accessibility attributes on the window tiling sometimes fails. From a brief investigation this is what happens:
1. emacs starts, Yabai gets notification, notices that app has not finished launching, listens for application finished launching notification
2. once Yabai gets that notification it tries to register for the common notifications, but sometimes we get back `kAXErrorCannotComplete`
3. app is not registered, not tiles :(

This is mainly caused by the fact the Emacs actually takes a while to properly startup and properly responding to ax requests.
The fix in my case is changing the value here https://github.com/koekeishiya/yabai/blob/4848ec028b60c29f3edb869f07e9e78834f3733a/src/window_manager.c#L1623

@koekeishiya  I think it would be worth to make that value a little higher or at least configurable, I've seen the same failure described above for other apps like Safari, especially when the system is under load.

**Comment by behaghel** [comment] 2021-12-23 16:19
@choco nice catch. Most likely what's happening with me. It explains also why `emacs -Q` (skip config, starts in a flash) always get tiled.

**Comment by koekeishiya** [comment] 2021-12-23 20:57
@choco Just a regression in the changes that were made on the-future branch. Should be back to working as before on the master branch now.

**Comment by noctuid** [comment] 2023-06-30 20:22
A lot of the suggestions here will cause problems.  For anyone confused, you should not use rules.  All you need is to use emacs-plus or apply its fix-window-role patch.

Here is a more detailed summary of what currently works to get Emacs tiled correctly without messing up e.g. completion popups:

- I'm using Emacs installed with emacs-plus's fix-window-role and undecorated-round patches.  The fix-window-role patch is all you need to get it working (default if you're using emacs-plus; I'm installing through nix and using the patch).  You don't need to use a title bar or manage rule.
- If you want to use the daemon and emacsclient, run `open -a Emacs --args --daemon` first or the windows created with emacsclient won't be managed/tiled
- *Do not* use any `manage=on` rules related to Emacs; Emacs.app will already be managed correctly by default, and if you add a manage rule, it will tile child frames (e.g. completion popups); maybe you can use title exclusions to get things working correctly in all cases, but this is unnecessarily complicated (it's not as simple as ignoring empty titles as suggested in #587)
- *Do not* set `yabai -m config window_topmost on`; leave it as the default (off) (or completion popups can appear behind Emacs - #1657)

**Comment by saucoide** [comment] 2023-11-19 21:56
@noctuid can I ask, to which emacs version in nixpkgs are you applying the patches to? 

I've tried applying the same patches from emacs-plus to get this to work with emacs29 emacs29-pgtk (fails to build) and emacs29-gtk3 but they dont tile correctly, or only tile when the titlebar is enabled, while the version from emacs-plus works without just fine :/

**Comment by brorbw** [comment] 2023-11-19 22:19
@saucoide I'm using `emacs@29` installed with 
```sh
brew install emacs-plus@29 --with-no-titlebar --with-native-comp
```
Removing all rules for emacs. That works great. Sometimes when I reboot and emacs opens before yabai loads it wont tile. In that case I have to toggle tiling for the emacs window and then it works.

**Comment by noctuid** [comment] 2023-11-20 13:09
@saucoide I'm using emacs-git from [emacs-overlay](https://github.com/nix-community/emacs-overlay/tree/master). See [here](https://github.com/noctuid/dotfiles/blob/master/nix/overlays/emacs.nix).

Why are you trying to use pgtk or gtk on mac?  I would not try to use pgtk unless on Wayland or WSL with Wayland.

**Comment by saucoide** [comment] 2023-11-20 17:19
@noctuid thanks! I wasnt planing on using pgtk, but since the standard one was not working I wanted to try if different ones would behave differently, but thanks will try with that one :)

@brorbw thanks, yes the brew version also works for me, but i've switched everything to nix and emacs is the last straggler that's why i asked noctiud since he mentioned he uses nix as well

**Comment by noctuid** [comment] 2023-11-21 13:00
Yeah, I found `undecorated-round` to be too buggy with yabai (for other reasons I think, but I can't remember) and ended up removing the setting from my early-init.  You don't have any issues with it in emacs-plus?

The other issue is probably solvable by just explicitly setting `mac-command-modifier` and `mac-option-modifier`.

**Comment by saucoide** [comment] 2023-11-21 20:21
yes, with emacs-plus i dont have any issues, everything works mostly, sometimes if i run `emacsclient -c -a ''` from keybinding it won't tile, but it's rare and most times it does tile correctly, so i don't worry about it. Could be that it's a race between removing the decoration and naming the frame or something, but for now i'm ok with leaving emacs on homebrew

**Comment by noctuid** [comment] 2023-11-21 20:29
I take back what I said about undecorated-round. I've been using it for months without issue.  Not sure what your setup is, but I don't have any issues with skhd.

**Comment by g-simmons** [comment] 2024-02-21 22:19
I recently switched from "regular" brew emacs to https://github.com/railwaycat/homebrew-emacsmacport. 

Using spacemacs, tiling would not work until I changed the following line in `.spacemacs`:

```
   ;; dotspacemacs-maximized-at-startup t
   dotspacemacs-maximized-at-startup nil
```

---

To check whether spacemacs is the problem, you can break your .spacemacs with a syntax error (or maybe rename it? didn't try). 

Broken .spacemacs will open in recovery mode which looks like:

![image](https://github.com/koekeishiya/yabai/assets/28633482/36859e74-71af-4c3f-8170-c0f52c7cd790)

Try tiling this window. For me it worked, which pointed to spacemacs as the issue.

**Comment by tshu-w** [comment] 2025-01-07 03:08
Has anyone encountered the issue where `M-x restart-emacs` fails to get tiled? A fresh Emacs launch works normally.

Steps to reproduce:
1. `emacs -Q`
2. `M-x restart-emacs`

**Comment by cyrialize** [comment] 2025-07-13 00:22
To add onto this conversation, I am using https://github.com/railwaycat/homebrew-emacsmacport. 

Specifically version 29.4.

I wasn't able to get the `rule` to work for me. Turning the tool bar on does work, but I hate the look of it. 

To get around this, I have tool bar turned on when Emacs starts up, and then turned off when Emacs is done starting. Yabai continues to recognize Emacs without the tool bar.

Here's an abridged version of my configuration. You can find my full configuration in my Github.

```elisp
(use-package emacs
  :custom
  ;; tool-bar-mode used to be nil here, instead we turn it on so that Emacs
  ;; could correctly be recognized by Yabai. We turn it off after startup -
  ;; see :hook below.
  ;;
  ;; Idea for this setup from:
  ;; https://github.com/koekeishiya/yabai/issues/86
  (tool-bar-mode t)

  :hook
  (
   ;; Turn the tool bar off. Yabai continues to recognize Emacs after, it is
   ;; only needed at startup.
   (emacs-startup . (lambda () (tool-bar-mode -1)))))
```
