### ISSUE TITLE
yabai -m query --windows not listing all windows

### ISSUE THREAD

**Issue by tophee** [koekeishiya/yabai#1367] opened 2022-08-20 14:26 UTC
I just rebooted my mac and was surprised to find that my script that moves certain windows to certain spaces didn't work anymore. Well, it worked, except that it left one window behind. First I though that this was due to that window floating above the others so I tried to toggle its float status but nothing happend. So I wanted to check what state it actually was in using `yabai -m query --windows` and to my surprise, that window wasn't even on the list. 

How is this possible?

When I quit the app and started it again, the window showed up in the query and behaves as expected.

**Comment by DiegoGuidaF** [comment] 2022-08-23 07:58
I am also having issues the same issues. I have started seeing them when connecting my second monitor.

**Comment by koekeishiya** [comment] 2022-08-23 13:24
Are you using the latest release or did you build from the master branch?

**Comment by tophee** [comment] 2022-08-23 15:13
I also use two monitors but they are both always connected so I didn't connect it to the dual screen setup, but it is possible that there is a connection. For example, one of the screens tends to take a bit longer to wake up.

> Are you using the latest release or did you build from the master branch?

I'm using the latest release.

**Comment by nikita-orca** [comment] 2022-08-25 12:23
I am having a similar issue. After QuickTerminal is hidden by some osascript, it's not queryable until I manually open it
```
#!/usr/bin/env zsh

QuickTerminal=$(yabai -m query --windows | jq -r 'map(select(.title=="QuickTerminal")) | .[0]')

if [[ $(echo $QuickTerminal) == 'null' ]]; then
	open -n /Applications/Alacritty.app --args --title QuickTerminal
elif [[ $(echo $QuickTerminal | jq -r '."is-visible"') == 'true' ]]; then
	QuickTerminal_PID=$(echo $QuickTerminal | jq -r '.pid')
	osascript -e "tell application \"System Events\" to set visible of first process ¬" \
		-e "whose unix id = ${QuickTerminal_PID} to false"
else
	QuickTerminal_ID=$(echo $QuickTerminal | jq -r '.id')
	yabai -m window $QuickTerminal_ID --focus
fi
```

**Comment by hahuang65** [comment] 2022-08-29 17:44
Looks like hidden windows are no longer being returned by query.

**Comment by tophee** [comment] 2022-09-05 12:23
> Looks like hidden windows are no longer being returned by query.

No, it has nothing to do with hidden vs not hidden. I have a BusyCal window visible right in front of me and yet it's not in the output of `yabai -m query --windows `

Is there any way of trouble shooting this? yabai has become pretty much unusable for me because it's unpredictable which window it will ignore next...

**Comment by nikita-orca** [comment] 2022-09-09 10:30
up :)

**Comment by nikita-orca** [comment] 2022-09-19 08:15
Thanks for the fix

**Comment by F1orian** [comment] 2022-09-25 14:39
I'm having the same issue.

When starting applications, sometimes they are simply ignored by yabai, and the querry doesn't return the windows at all, as mentioned previously.

To fix this, I have to manually quit the application and re-open it, hoping that this time yabai will register the application /window.

This has been going on for well over a few months now for me.
If there's a way to debug this, I_d be happy to help.

**Comment by tophee** [comment] 2022-10-04 08:15
I can confirm that this issue persists. Also in v 5.0.1 `yabai -m query --windows` does misses some windows. I see no patterns in which windows are forgotten but after quitting the application and re-opening it, yabai usually sees the windows. 

Has anyone found a way of handling this? With windows randomly vanishing from yabai's radar, it has become pretty much unusable for me so I'm considering switching back to Amethyst (which I left because it was unreliable/unpredictable at times. So I'm not sure switching back is a wise idea).

It seems that not many of us are affected by this issue so I'm wondering whether some other app/setting might interfere with which windows yabai can see. But I have no knowledge of where the query command gets its information from...

**Comment by tophee** [comment] 2022-10-08 20:20
This is really puzzling me. What might be interfering with the query? Could someone outline how a query like `yabai -m query --windows` works? Like: where does it get the information about the windows? Does macOS have a list of them that yabai just calls? My guess is that this is not the case, because there would be very little room for error in that case. So where/how is yabai gathering which windows exist and what might be some of the pitfalls in this process?

I just had a situation where two windows were missing from the list, Busycal and Microsoft Outlook (possibly others too, but I was looking for those two). 30 minutes later, when I return to my mac and unlock the screen, they are suddenly there (i.e. on the query list). I didn't do anything with either of these windows, in fact, I just used the web browser to navigate to this page before I left the computer. What might have changed during those 30 minutes that brought those windows to yabai's attention (or allowed yabai to access them, or prevented yabai from accessing them the first time?

**Comment by occludedpixel** [comment] 2022-10-10 05:15
I think I may be encountering a related issue which I have recorded in the attached video. 

In the video, I have set up two spaces. Space 1 (the one in focus) has a single iTerm2 window while space 2 has a single Vivaldi web browser window.  After restarting yabai, `yabai -m query --windows --space 2` doesn't show the Vivaldi window and returns an empty list. Meanwhile, `yabai -m query --spaces --space 2` does indicate that there is a single window on the space in the `windows` field but the `first-window` and `last-window` fields are `0` instead of `87`. Next, I repeat the previous two queries for space 1 and this time both return the expected results.

https://user-images.githubusercontent.com/97084099/194800006-58a79413-18ce-4162-837d-c264c2852ff9.mp4

To get the expected results for the first two queries, space 2 needs to have been brought in focus after the restart. 

I believe this behaviour is the reason why the status bar I use ([simple-bar](https://github.com/Jean-Tinland/simple-bar)) does not show the windows on the unfocused spaces after restarting yabai, requiring me to switch to the other spaces before for their windows to show up in the status bar. My current workaround is to include a command to cycle through all the spaces as part of the script to restart yabai.

I briefly dug into the code that handles `yabai -m query --windows` and I it looks like `window_manager_find_windows_for_spaces` is the function that returns results to be printed. That function in turn makes calls to `window_manager_find_window` to get the info for each window. In `window_manager_find_window`, there's just a call to `table_find`. I think the windows on the unfocused spaces are only inserted after those spaces are brought in focus after restarting so `table_find` is not returning anything prior.

**Comment by tophee** [comment] 2022-10-10 21:24
Okay, this is useful information. It might explain some of the randomness in which windows are listed and which aren't. 

But in my case, there must be more. Restarting yabai cannot be the reason for windows getting "lost" because I don't usually restart yabai. The typical situation where the problem is most noticeable is when I log back in after the displays turned off due to inactivity. This causes the Mac to move (at least some of) the windows that were on the secondary display over to the primary display. In this situation, I'd like to use a script to move at least some of the windows back to their respective spaces on the secondary display... So unless yabai restarts when I log back in, restarting cannot be the reason why yabai doesn't see some of the windows.

In addition, it is also clear that visiting all spaces would not solve the issue for me because, as I [reported above](https://github.com/koekeishiya/yabai/issues/1367#issuecomment-1236937097), yabai also misses windows that are not hidden at all but on the currently active desktop.

Any other suggestions what might cause [yabai](url) to lose some of the windows?

**Comment by occludedpixel** [comment] 2022-10-11 09:12
@tophee do the windows that you mentioned here:

> I can confirm that this issue persists. Also in v 5.0.1 `yabai -m query --windows` does misses some windows. 

appear in the results of `yabai -m query --spaces` under the `windows` field?

**Comment by noperator** [comment] 2023-02-02 02:54
> my script that moves certain windows to certain spaces

@tophee, this issue was causing a [similar problem for me](https://github.com/koekeishiya/yabai/issues/1615#issuecomment-1413068787). I worked around it by using AppleScript to locate the desired window and focus on it—at that point, yabai is able to "see" it and manipulate it as usual.

**Comment by tophee** [comment] 2023-02-02 07:37
> AppleScript to locate the desired window and focus on it—at that point, yabai is able to "see" it and manipulate it as usual.

@noperator are you saying that once you focused on the window once, yabai will see it from there on or only as long as is om focus?

My [previous test](https://github.com/koekeishiya/yabai/issues/1367#issuecomment-1275195560) indicates the latter as I had at least one window that yabai wouldn't see even after I foregrounded it.

**Comment by noperator** [comment] 2023-02-02 08:39
Correct, the latter: yabai will see it as long as it's in focus.

**Comment by rwijtvliet** [comment] 2023-11-03 14:24
Same here.

**Comment by ear7h** [comment] 2023-12-30 23:30
I ran into this with a GUI program I'm writing (using the `winit` rust crate). When I start it, it is often not visible by `window --toggle float` or `query --windows` messages. Here's the logs:

```
EVENT_HANDLER_APPLICATION_LAUNCHED: photo-editor (11009) is not observable, subscribing to a
ctivationPolicy changes
-[workspace_context observeValueForKeyPath:ofObject:change:context:]: activation policy changed for photo-editor (11009)
EVENT_HANDLER_APPLICATION_LAUNCHED: photo-editor (11009) is not finished launching, subscribing to finishedLaunching changes
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 30052
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float

```
Putting a 500ms `sleep` before `EventLoop::run` (ends up calling `NSApplication.run` which then runs `NSApplication.finishLaunching`, relevant https://github.com/rust-windowing/winit/pull/1902), causes `yabai` to recognize it. Here's the logs for that:

```
EVENT_HANDLER_APPLICATION_LAUNCHED: photo-editor (12558) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 30052
-[workspace_context observeValueForKeyPath:ofObject:change:context:]: activation policy changed for photo-editor (12558)
EVENT_HANDLER_APPLICATION_LAUNCHED: photo-editor (12558)
window_manager_create_and_add_window:35312 photo-editor - winit window
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: photo-editor (12558)
EVENT_HANDLER_SLS_SPACE_ADD_WINDOW: 35312 added to 4
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_WINDOW_RESIZED: Firefox 33168
EVENT_HANDLER_WINDOW_RESIZED: photo-editor 35312
EVENT_HANDLER_WINDOW_MOVED:DEBOUNCED photo-editor 35312
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_WINDOW_RESIZED: Firefox 33168
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle float
EVENT_HANDLER_WINDOW_RESIZED: Firefox 33168
```

---

My first thought was a race condition in `yabai`, so I tested that with the following patch. I don't know the specifics of the APIs, so idk if it really is a race (what if the application finishes launching before `yabai` sets the listener?). Anyways, this didn't fix anything. And looking at the logs backs up that the problem isn't there, the code with a `sleep` never actually listens to `finishedLaunching`, the application is finished launching right after the activation policy changes. Additionally, increasing the `sleep` to 10s shows that `EventLoop::run` is also what triggers `activation policy changed`.

<details>
<summary>patch</summary>

 ```
diff --git a/src/event_loop.c b/src/event_loop.c
index ac3eb9d..2b58472 100644
--- a/src/event_loop.c
+++ b/src/event_loop.c
@@ -65,7 +65,10 @@ static EVENT_HANDLER(APPLICATION_LAUNCHED)
     if (!workspace_application_is_finished_launching(process)) {
         debug("%s: %s (%d) is not finished launching, subscribing to finishedLaunching changes\n", __FUNCTION__, process->name, process->pid);
         workspace_application_observe_finished_launching(g_workspace_context, process);
-        return;
+        if (!workspace_application_is_finished_launching(process)) {
+            debug("%s: %s (%d) is still not finished launching, returning\n", __FUNCTION__, process->name, process->pid);
+            return;
+        }
     }
 
     struct application *application = application_create(process);
```

</details>

**Comment by koekeishiya** [comment] 2024-02-04 14:43
Might be fixed on master.

**Closed** 2024-02-04 15:30 UTC
Labels: bug

**Comment by ear7h** [comment] 2024-02-05 11:16
My issue with `winit` is still happening. Yabai still doesn't capture the  [`window.rs` example](https://github.com/rust-windowing/winit/blob/v0.29.10/examples/window.rs). But, I created a minimal windowed application in objective-c with cocoa and yabai has no problems finding it.

Some interesting bits:
* removing the `return` after `workspace_application_observe_finished_launching` lets yabai capture the gui window
* the objective-c example gets a `[workspace_context observeValueForKeyPath:ofObject:change:context:]: a.out (3680) finished launching` message
* the `winit` example with a `sleep(500)` (is visible to yabai) does not get the `finished launching message`, just a `-[workspace_context observeValueForKeyPath:ofObject:change:context:]: activation policy changed for window (4082)`

So, maybe the `finishedLaunching` isn't being called. I'll open an issue on the `winit` repo.

**Comment by koekeishiya** [comment] 2024-02-05 12:55
I have no idea how these NSRunningApplication observation-properties work, so I have tried to eliminate any potential for timing issues on the latest master. Can you test there?

**Comment by ivester** [comment] 2024-02-13 11:43
I just upgraded to `yabai-v6.0.12` and I get now all the windows returned when running `yabai -m query --windows`. Btw, thank you @koekeishiya for sharing this amazing app, I love it!

**Comment by ear7h** [comment] 2024-04-04 13:01
Upgraded to 7.0.4 today and am no longer having issues with my `winit` app. The last time I checked the issue was a 6.x version. Thank you @koekeishiya 🎉
