### ISSUE TITLE
Right Click Issue - On Context Menus and the Dock

### ISSUE THREAD

**Issue by Serubin** [koekeishiya/yabai#704] opened 2020-11-04 15:54 UTC
In certain contexts, such as when right clicking into a context menu or on the Dock - the right click action auto fires on hover.

This seems to occur only when yabai is running. This occurs in 10.15 and 10.16/11.0.

**Comment by acmcelwee** [comment] 2020-11-04 17:20
This sounds a lot like the discussion going on in #660.

**Comment by koekeishiya** [comment] 2020-11-14 17:18
Closing as duplicate of #660

**Closed by koekeishiya** 2020-11-14 17:18 UTC
