### ISSUE TITLE
Window floats after exiting fullscreen video

### ISSUE THREAD

**Issue by ahan98** [koekeishiya/yabai#619] opened 2020-07-21 11:41 UTC
Hi, first time posting an issue, so sorry if I'm doing something against etiquette.

This issue is minor, but has some interesting side effects. I have only noticed it through the following reproduction:

0. Begin with a bsp layout
1. Open up a YouTube video (I used Google Chrome, but browser shouldn't matter)
2. Press `f` to fullscreen the video, moving it to a new space
3. Press `f` to exit out of fullscreen, exiting the space

Now the window is floating (although, strangely, if you run `yabai -m query --windows`, the window of that video will output `"floating":0`) and the borders are gone (to fix this issue, the windows would need to be re-managed back to bsp). Another interesting effect is that if you exit the video by closing the space with a skhd hotkey, or by using `esc`, rather than `f`, to exit the video, no issues occur.

[Link to gif](https://user-images.githubusercontent.com/12192567/88050821-699a7e00-cb0c-11ea-8452-c6f5314f6543.gif) (sorry for the low quality)

In the screencast, I first reproduce the issue by pressing `f` to exit fullscreen and show that layout has been changed to `float`. Then, after re-managing the windows back to bsp, I exit fullscreen by pressing `esc` to show the non-problematic behavior.

In the screencast, we can see that when `f` is used to exit the video, the layout for only that window changes to float (the other window is still bsp). Next, though this was hard to see in the gif, the border for only that window disappears as well. But when using `esc`, neither of these two issues occur, and layout/border behavior works as expected.

Note that my `.yabairc` is basically empty/stock.

<ins>What I tried:</ins> Added to `.yabairc` a function to set layout to bsp and borders on when signaled by `space_changed`, but I couldn't get that to work.

Thanks!

**Comment by koekeishiya** [comment] 2020-07-21 12:16
Sounds like a duplicate of https://github.com/koekeishiya/yabai/issues/586, you can confirm this by opening some other application/window on the same space that your browser initially on, before you make the video fullscreen.

**Closed** 2020-07-21 12:20 UTC
