### ISSUE TITLE
'display  --focus' not working when windows stacked

### ISSUE THREAD

**Issue by workcomplete** [koekeishiya/yabai#1198] opened 2022-03-17 17:15 UTC
Hey really appreciate the updates - I have been having an nagging issue I was hoping would be resolved with this release but doesn't seem to be. I use the following config to move my focus between windows and monitors (displays):

` shift + ctrl + alt + cmd - a : yabai -m window --focus west || yabai -m display --focus west`
 `alt + shift - s : yabai -m window --focus south`
` shift + ctrl + alt + cmd - d : yabai -m window --focus east || yabai -m display --focus east`
` alt + shift - w : yabai -m window --focus north`

This works fine when windows are not stacked. When windows are stacked, I am still able to move focus between windows, but when I try to switch focus between monitors I lose focus (ie. no window is in focus and the focus stays on the current monitor/display).

Hopefully this is a fixable issue with my config but I thought I would open here in case anyone is having the same issue.

Thanks!

**Comment by pierclgr** [comment] 2022-03-18 12:20
I have a similar problem. I have an external display connected which is set to be the main display, so it is N.1 display in yabai. It happens that the command `yabai -m display --focus` only works when I'm focusing display 2, so the display of my MacBook, when I'm focusing display 1 (the external display) it doesn't work.
The same happens when I focus a space on the external display from a space in MacBook's display: it doesn't actually get focused because the menu bar is still darken and no window in the target space is focused.
Yesterday I reinstalled yabai and the problem went away, but now I have it again, don't know why.

**Comment by danymat** [comment] 2022-03-27 20:38
Hello, i have the same problem.
I use this skhd macro to toggle between stack and bsp mode:
```
hyper - z : yabai -m space --layout $(yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "stack" else "bsp" end')

```

**Comment by restfuladi** [comment] 2022-04-16 23:17
I also have this issue, if the destination display of `yabai -m display --focus` has a stack, all focus goes away and you have to click on a window.

**Comment by koekeishiya** [comment] 2022-04-18 15:14
Hm I am unable to reproduce this using yabai v4.0.0 on macOS 12.3.1 (Apple Silicon).

I have tested using bsp layout with stacked nodes on the destination display, and the window is focused correctly.
I also tested using the stack layout on the destination display, and the window is focused correctly.

The above tests worked using both `yabai -m display --focus next` and `yabai -m display --focus 2`.

Is this happening with specific applications? Are you running Hammerspoon or other accessibility software that could interfere in some way?

**Comment by restfuladi** [comment] 2022-04-18 15:22
I just quit Hammerspoon, which I was using only for Stackline, and focus now works correctly. My focus command is `yabai -m window --focus west || yabai -m display --focus west`.

**Comment by koekeishiya** [comment] 2022-04-18 15:26
I think this is a problem with Stackline, the Hammerspoon window "steals" focus for whatever reason. What yabai is doing is simply sending focus to the window that macOS says is the "front-most" window on the destination display.

I'd like to make something like Stackline built-in to yabai itself in the future. There are tons of things that can be improved regarding the stack-system.

**Comment by restfuladi** [comment] 2022-04-18 16:53
It's a shame because the workflow with these commands was getting really good:
```
ctrl - left : yabai -m window --focus west || \
                  yabai -m display --focus west

ctrl - right: yabai -m window --focus east || \
                   yabai -m display --focus east

ctrl - down : yabai -m window --focus south || \
                     yabai -m window --focus stack.next || \
                     yabai -m window --focus stack.first

ctrl - up : yabai -m window --focus north || \
                yabai -m window --focus stack.prev || \
                yabai -m window --focus stack.last
```

**Comment by koekeishiya** [comment] 2022-04-18 17:05
I believe this is the relevant issue: https://github.com/AdamWagner/stackline/issues/67

A possible workaround that would let you keep Stackline running could be the following:

Instead of `yabai -m focus --display west`, you could run `yabai -m query --spaces --display west` and select the one with `is-visible` true (using `jq`), then run a `yabai -m window --focus <id>` command on the first window listed in the `windows` array.

**Comment by restfuladi** [comment] 2022-04-18 17:59
I got it working, thank you!!

```
ctrl - left : yabai -m window --focus west || \
              yabai -m window --focus \
              $(yabai -m query --spaces --display west | jq '.[0]' | jq '.["last-window"]')

ctrl - right: yabai -m window --focus east || \
              yabai -m window --focus \
              $(yabai -m query --spaces --display east | jq '.[0]' | jq '.["first-window"]')
```

**Comment by restfuladi** [comment] 2022-04-18 18:18
I can also stack across displays now:
```
meh - left  : yabai -m window west --stack $(yabai -m query --windows --window | jq -r '.id') || \
              yabai -m window $(yabai -m query --spaces --display west | jq '.[0]' | jq '.["last-window"]') \
                    --stack $(yabai -m query --windows --window | jq -r '.id')
meh - right : yabai -m window east --stack $(yabai -m query --windows --window | jq -r '.id') || \
              yabai -m window $(yabai -m query --spaces --display east | jq '.[0]' | jq '.["first-window"]') \
                    --stack $(yabai -m query --windows --window | jq -r '.id')
meh - up    : yabai -m window north --stack $(yabai -m query --windows --window | jq -r '.id')
meh - down  : yabai -m window south --stack $(yabai -m query --windows --window | jq -r '.id')
```

**Comment by koekeishiya** [comment] 2022-04-21 13:57
Closing this as there isn't really anything yabai can do about this, use the workaround mentioned above if Stackline is unable to fix the issue on their end.

**Closed by koekeishiya** 2022-04-21 13:57 UTC

**Comment by pierclgr** [comment] 2022-04-26 12:02
I don't have stackline and hammerspoon, I had them in the past but now I removed them, however I still have the same issue.

**Comment by dmitrym0** [comment] 2024-04-09 21:33
Having the same problem where switching to a desktop doesn't focus any windows. With or without Hammerspoon. I have never used stack line. 

Any advice?
