### ISSUE TITLE
Tabs in macOS builtin applications are handled as if a window is added

### ISSUE THREAD

**Issue by toinehartman** [koekeishiya/yabai#579] opened 2020-06-17 07:33 UTC
When adding a "native" macOS tab (e.g. Finder, Pages), it seems to be handled as if it's a window, and an empty tree node is added.

After going in and out of Mission Control, the windows are rebalanced to the expected tree/layout.

A [screen grab](https://gfycat.com/animatedsamegrebe) as an example.

**Expected behaviour**
The tree/layout which is created after the Mission Control should have been there in the first place.

**Comment by dominiklohmann** [comment] 2020-06-17 07:43
Duplicate of #68

**Closed** 2020-06-17 16:23 UTC
Labels: duplicate
