### ISSUE TITLE
Moving windows to spaces no longer works after Sonoma 14.5

### ISSUE THREAD

**Issue by jordan-da** [koekeishiya/yabai#2275] opened 2024-05-15 14:12 UTC
related: https://github.com/koekeishiya/skhd/issues/355

```
yabai -m window --space 1
```
Doesn't seem to move windows to spaces anymore after the Sonoma 14.5 update

yabai config: https://github.com/hypergig/workstation/blob/master/config/yabairc
skhd config: https://github.com/hypergig/workstation/blob/master/config/skhdrc

**Comment by OneComputerGuy** [comment] 2024-05-15 15:01
Taking a closer look at this, it seems is the same issue reported a few weeks back here: https://github.com/koekeishiya/yabai/issues/2240

**Comment by mrala** [comment] 2024-05-15 18:53
Duplicate of 
- #2240 
- #2273

**Comment by koekeishiya** [comment] 2024-05-16 22:54
See #2240

**Closed by koekeishiya** 2024-05-16 22:54 UTC
