### ISSUE TITLE
macOS native fullscreen (Command - Return) breaks zoom-fullscreen

### ISSUE THREAD

**Issue by Sayrus** [koekeishiya/yabai#440] opened 2020-03-11 11:41 UTC
Hello,

When using Command + Return instead of `yabai -m window --toggle native-fullscreen` on a `zoom-fullscreen` Window, leaving the native fullscreen mode will not resize the window or consider it as `zoom-fullscreen`.
This means you end up with a Window over the others, with the same size as a `zoom-fullscreen` but you can't unzoom it.

Steps to reproduce:
- Open two windows
- Maximize one of them (`yabai -m window --toggle zoom-fullscreen`)
- Use native fullscreen (not with Yabai but with Command - Return)
- Leave native fullscreen (not with Yabai but with Command - Return)

The window is not maximized without a way to toggle `zoom-fullscreen` again.
This does not happen when using the yabai command.

Expected behavior: the behavior should be the same as the yabai command (`yabai -m window --toggle native-fullscreen`)

Best regards,

**Comment by dominiklohmann** [comment] 2020-03-11 12:07
> * Use native fullscreen (not with Yabai but with Command - Return)

The system-default way to enter native-fullscreen mode is by pressing <kbd>ctrl</kbd> + <kbd>cmd</kbd> + <kbd>return</kbd>

That being said, I cannot reproduce this with the steps you posted.

What application are you encountering this issue with? Can you reproduce it with other applications?

**Comment by Sayrus** [comment] 2020-03-11 14:20
Strange, when using Control I do not get the native-fullscreen mode.

The glitch works at least on Firefox and iTerm2. I can test any application you want me to try.

I can also reproduce with:
Control-Command-F: Use the app in full screen, if supported by the app.

It seems that the application is not managed by Yabai anymore when coming back from native fullscreen. When coming back from native-fullscreen, I can open other windows and they'll get resized. However, the window who came back from native-fullscreen won't be resized, it'll just stay in the background (or foreground, depending on the situation).

Here is the GIF (Note: iTerm2 does not support the fullscreen this way so I can't use Control-Command-F):
![fullscreen](https://user-images.githubusercontent.com/22404472/76426001-5deebc00-63a2-11ea-8261-fe36f24d5f8a.gif)

As the quality is a little low here is what happens:
- I native-fullscreen the right iTerm2 and exit native-fullscreen
- Now the window is not managed by Yabai anymore (You can see that the other terminal now takes the whole space as the title bar is in the middle)
- I focus the other iTerm2 to show it is taking the whole space
- I open a new window to show that the old iTerm2 is effectively not managed by Yabai anymore
- Close both iTerm2, the only remaining is the one that was in native-fullscreen, it does not resize showing it is not managed by yabai anymore

Note:
- Once the window is not managed by Yabai anymore, typing `yabai -m window --toggle zoom-fullscreen` does not do anything
- The window has no prev or next:
```console
$ yabai -m window --toggle zoom-fullscreen # Exit code 0
$ yabai -m window --focus prev # Exit code 1
could not locate the prev managed window.
$ yabai -m window --focus next # Exit code 1
could not locate the next managed window.
```
- If using the MacOS controls (Cmd + Tab) to get focus, the window is managed again by Yabai
- After changing Space and coming back, the window is managed again by Yabai

**Comment by dominiklohmann** [comment] 2020-03-11 14:26
- Can you reproduce this with an empty configuration (I cannot)?
- What version of yabai and macOS are you running?
- You can enable verbose output with `yabai -m config debug_output on`. That should show when yabai loses track of a window.

**Comment by Sayrus** [comment] 2020-03-11 14:37
I can. With my configuration and debug on:
```
EVENT_HANDLER_WINDOW_CREATED: ignoring window iTerm2 28641
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28635
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28635
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28638
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28638
EVENT_HANDLER_SPACE_CHANGED: 522
window_manager_add_application_windows: ignoring window iTerm2 28641
event_signal_transmit: transmitting space_changed to 1 subscriber(s)
process_is_observable: osascript was marked as background only! ignoring..
EVENT_HANDLER_DAEMON_MESSAGE: query --spaces
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28638
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28635
EVENT_HANDLER_WINDOW_CREATED: ignoring window iTerm2 28649
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28635
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28635
EVENT_HANDLER_SPACE_CHANGED: 6
window_manager_add_application_windows: ignoring window iTerm2 28649
event_signal_transmit: transmitting space_changed to 1 subscriber(s)
process_is_observable: osascript was marked as background only! ignoring..
EVENT_HANDLER_DAEMON_MESSAGE: query --spaces
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28635
```


With no configuration:
```
yabai -m config bsp
yabai -m config debug_output on
```

```
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28725
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28725
EVENT_HANDLER_WINDOW_CREATED: ignoring window iTerm2 28727
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28725
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28725
EVENT_HANDLER_WINDOW_MOVED: iTerm2 28638
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28638
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28638
EVENT_HANDLER_SPACE_CHANGED: 560
window_manager_add_application_windows: ignoring window iTerm2 28727
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28638
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28725
EVENT_HANDLER_WINDOW_CREATED: ignoring window iTerm2 28735
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28725
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28725
EVENT_HANDLER_SPACE_CHANGED: 6
window_manager_add_application_windows: ignoring window iTerm2 28735
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28725
EVENT_HANDLER_WINDOW_FOCUSED: iTerm2 28638
EVENT_HANDLER_WINDOW_DESTROYED: iTerm2 28725
```
and a second time (this time i focus windows to know which is which):
28763 is the window getting native-fullscreen
```
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28763
EVENT_HANDLER_MOUSE_DOWN: 940.45, 528.78
EVENT_HANDLER_WINDOW_FOCUSED: iTerm2 28766
EVENT_HANDLER_MOUSE_UP: 940.45, 528.78
EVENT_HANDLER_MOUSE_DOWN: 477.80, 306.38
EVENT_HANDLER_WINDOW_FOCUSED: iTerm2 28763
EVENT_HANDLER_MOUSE_UP: 477.58, 306.38
EVENT_HANDLER_WINDOW_CREATED: ignoring window iTerm2 28777
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28763
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28763
EVENT_HANDLER_WINDOW_MOVED: iTerm2 28766
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28766
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28766
EVENT_HANDLER_SPACE_CHANGED: 568
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28766
EVENT_HANDLER_WINDOW_CREATED: ignoring window iTerm2 28785
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28763
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 28763
EVENT_HANDLER_SPACE_CHANGED: 6
window_manager_add_application_windows: ignoring window iTerm2 28785
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 28763
EVENT_HANDLER_WINDOW_FOCUSED: iTerm2 28766
EVENT_HANDLER_WINDOW_DESTROYED: iTerm2 28763
```

**Comment by Sayrus** [comment] 2020-03-11 14:54
Found what Cmd + Return was: it is a shortcut iTerm2 set up to trigger fullscreen. It does not appear in existing keys but it does exists and is active 🤔 (https://superuser.com/questions/600573/disable-cmdenter-on-iterm-2)

**Comment by dominiklohmann** [comment] 2020-03-11 15:03
> It does not trigger a `EVENT_HANDLER_DAEMON_MESSAGE: window --toggle native-fullscreen`

That's expected, as that's the internal event handler for messages sent to the yabai daemon.

This is the line that's really weird:

> ```
> window_manager_add_application_windows: ignoring window iTerm2 28785
> ```

Can you reproduce this with other applications as well? If not, maybe this boils down to some weird iTerm2 setting.

**Comment by Sayrus** [comment] 2020-03-11 15:08
Oh, makes sense now. Firefox too has a custom logic for handling fullscreen (Option - Shift - F).

**Comment by koekeishiya** [comment] 2020-03-11 15:11
The `ignoring window` thing only happen for windows that report an AX role of AXPopover or AXUnknown: https://github.com/koekeishiya/yabai/blob/99f4305b850ad68b69276ebb3ad336e60d5d53db/src/event.c#L554

**Comment by Sayrus** [comment] 2020-03-11 15:14
```
EVENT_HANDLER_WINDOW_CREATED: ignoring window Firefox 30440
```
Oh so the window become a floating window and is not in the default bsp layout. I think I get it.
Do you consider this a Firefox/iTerm2/... bug as they should not report this role?

**Comment by dominiklohmann** [comment] 2020-03-11 15:25
The real question if whether the window role _stays_ AXUnknown after the transition from fullscreen. Can you use Accessibility Inspector.app to find that out?

<img width="460" alt="image" src="https://user-images.githubusercontent.com/4488655/76433645-e5452b00-63b4-11ea-8782-b73e5958d276.png">

**Comment by Sayrus** [comment] 2020-03-11 15:45
It seems that the Role is `AXWindow` and SubRole `AXStandardWindow` as it was before being native-fullscreen. (I do have an old version of the Inspector as I don't have XCode or a linked app store account to download it and I am not used to using it. You might want to double-check this)

**Comment by koekeishiya** [comment] 2020-03-11 17:18
I don't think I would call this a bug in yabai. I am unable to reproduce this with either iTerm (v3.3.9) or Firefox (v73.0.1) that I have installed on my system. I don't really use these applications so I do not know if those are the latest versions. I don't recall having this problem with any applications I use.

I also am not sure what I could even try to do differently to handle that situation better; the current implementation is fairly reasonable in my opinion.

**Comment by Sayrus** [comment] 2020-03-12 07:53
I am using the same versions.
I tried disabling both `Karabiner` and `skhd` but I still have the same result. Funnily enough, I can reproduce when using the mouse (Statusbar > (iTerm2) > View > Toggle Fullscreen View)
Is there anything I can do to help?

**Comment by Sayrus** [comment] 2020-03-12 08:10
Oh wow, you are going to hate me now:
- Setting `window_topmost` to `on` instead of `off` fix the issue

Which does not make sense to me anymore. I am not familiar enough with the internals of the project to take a guess.

**Comment by koekeishiya** [comment] 2020-03-23 12:15
Changing the value of `window_topmost` does not affect the codepath that is ran when a window transitions between being a normal window and/or a fullscreen window. This just strengthens my theory that this is happening for reasons outside of yabai's control.

**Comment by koekeishiya** [comment] 2020-05-22 12:21
I am going to close this. I am unable to reproduce by using the listed steps with Firefox and so I don't consider this a bug with yabai.

**Closed by koekeishiya** 2020-05-22 12:21 UTC
Labels: help wanted, obscure
