### ISSUE TITLE
Prevent app from being focused when switching space

### ISSUE THREAD

**Issue by oddnugget** [koekeishiya/yabai#1957] opened 2023-11-06 16:05 UTC
Greetings, ever since upgrading to MacOs Sonoma i have a strange issue. When i am screensharing in [tuple](https://tuple.app/) and i do a `yabai -m space --focus <space-id>`, the tuple app popup in the menu bar opens up and takes focus as the frontmost application. 

I have a rule already set up to not manage tuple: 
`yabai -m rule --add app="^Tuple$" manage=off`

And querying for windows in the space does not return a tuple window. Most probably because it is not a window but a popover or whatever they are called. 

I'm unsure if this is an issue on yabai side or on tuple itself, but i have confirmed that the issue is not present when yabai is not running (switching spaces natively with mission control).

Is there a way to prevent the app from being focused when switching spaces?

**Comment by Mmasson-01** [comment] 2023-11-07 11:55
This look like same problem with Microsoft Teams. Refer to https://github.com/koekeishiya/yabai/issues/74

**Comment by oddnugget** [comment] 2023-11-10 08:34
It looks yabai is ignoring windows with the AXPopover role by default, see #162. This means that window events are not reported and a signal like the one described in #74 doesn't work. Yabai just outputs `ignoring AXPopover window Tuple`.

**Comment by koekeishiya** [comment] 2024-03-12 22:40
Popover windows are not ignored in the latest version of yabai. Closing this as duplicate of #2041

**Closed by koekeishiya** 2024-03-12 22:40 UTC
