### ISSUE TITLE
Window partitioning is broken with new Intellij project windows

### ISSUE THREAD

**Issue by grandmasteri** [koekeishiya/yabai#2108] opened 2024-02-22 17:37 UTC
Since the term *window* is overloaded here I'll refer to windows in the context of yabai as a *yabai window* and windows in the context of Intellij as an *Intellij window*.

Recent Intellij versions introduced the ability to have multiple projects (each in its own project window) in the same yabai window. When I switch Intellij windows, yabai erroneously binary partitions the yabai window as though another yabai window was in the space. The end result is that the yabai window occupies half the space instead of the full space. I cannot attach a video unfortunately since my setup is on my work laptop and I don't want to risk revealing confidential information.

Intellij specs (some info redacted):
```IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 12, 2024


Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 20000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Kotlin: 233.14475.28-IJ
```

My yabairc for reference:
```
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 & sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config split_ratio                  0.50

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10
```

**Comment by koekeishiya** [comment] 2024-02-22 17:44
Same as #68 probably?

**Comment by koekeishiya** [comment] 2024-03-12 22:06
Closing as duplicate of #68. If you think this is not the same issue, feel free to leave a comment and we can reopen.
To confirm, basically open a Finder window and open a tab (cmd+t) and if the observed effects are the same, this is considered the same issue.

The fact is that the API does not provide enough information for yabai to handle this situtation.
The best solution I can offer is to make these applications floating by using window rules (`yabai -m rule --add app="MyApp" manage=off`). Use the query system (`yabai -m query --windows`) and use the `app` property to identify the correct name to use in these rules.

**Closed by koekeishiya** 2024-03-12 22:06 UTC
