### ISSUE TITLE
Moving between spaces, across monitors, does not work as intended

### ISSUE THREAD

**Issue by booherbg** [koekeishiya/yabai#477] opened 2020-04-16 03:39 UTC
Hi there! Love the project. This is the closest I've felt to home coming from i3wm on linux. I'm trying to replicate some very simple behavior:

- alt + 1,2,3,4... etc brings the space to focus (works)
- alt + shift + 1,2,3,4... etc moves the focused window to the space (works)

The issue is that I have 1-6 on my mac screen, and spaces 7-8 on an external monitor. Everything works fine if I move windows on the same "display", but if I try to move across the display (from laptop to monitor, or monitor to laptop), the window DOES move but it only goes to the space that is active on the other display, not the correct space.

For example
If I have space 8 open on monitor, and space 5 open on laptop, and issue the following (via skhd) against a window that is focused on space 8 (monitor):
`yabai -m space --focus 3`
The result is that the window ends up on space 5, instead of space 3. If I issue the exact same command again, it does go to space 3.

I hope this is helpful! Love yabai so far, amazing work! Everything else seems to be working great so far.

My skhd config is about as bare as you'd expect (just getting started):
```
alt - 1 : yabai -m space --focus 1
shift + alt - 1 : yabai -m window --space 1
alt - 2 : yabai -m space --focus 2
shift + alt - 2 : yabai -m window --space 2
alt - 3 : yabai -m space --focus 3
shift + alt - 3 : yabai -m window --space 3
alt - 4 : yabai -m space --focus 4
shift + alt - 4 : yabai -m window --space 4
alt - 5 : yabai -m space --focus 5
shift + alt - 5 : yabai -m window --space 5
alt - 6 : yabai -m space --focus 6
shift + alt - 6 : yabai -m window --space 6
alt - 7 : yabai -m space --focus 7
shift + alt - 7 : yabai -m window --space 7
alt - 8 : yabai -m space --focus 8
shift + alt - 8 : yabai -m window --space 8
```

**Comment by koekeishiya** [comment] 2020-04-16 17:52
I can't reproduce this. Moving window between spaces work just fine across multiple displays - all combinations of source/dest space being active or inactive.

**Comment by booherbg** [comment] 2020-04-17 16:05
Since writing this, I see now that moving from my laptop to external monitor *does* work as expected, but moving from external monitor to laptop always puts it on my focused space.

Hmm. How can I be more helpful in diagnosing this?

**Comment by dominiklohmann** [comment] 2020-04-18 13:07
Open two spaces each on two displays (so you have 4 spaces in total). Now open just a single terminal on space 1. Have space 1 focused on display 1, and space 3 active on display 2. Run these commands and paste their output:

```sh
yabai -m query --spaces
yabai -m window --space 4
yabai -m query --spaces
```

**Comment by booherbg** [comment] 2020-04-20 17:06
Sure. Great idea. See below. I went a step further and re-ran the `yabai -m window --space 4` a second time (once it was on the external monitor) to show the point.
```
MacBook-Pro:~ blaine$ yabai -m query --spaces
[{
	"id":1,
	"label":"web",
	"index":1,
	"display":1,
	"windows":[2657],
	"type":"bsp",
	"visible":1,
	"focused":1,
	"native-fullscreen":0,
	"first-window":2657,
	"last-window":2657
},{
	"id":6,
	"label":"term",
	"index":2,
	"display":1,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":37,
	"label":"external1",
	"index":3,
	"display":2,
	"windows":[],
	"type":"bsp",
	"visible":1,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":90,
	"label":"",
	"index":4,
	"display":2,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
}]
MacBook-Pro:~ blaine$ yabai -m window --space 4
MacBook-Pro:~ blaine$ yabai -m query --spaces
[{
	"id":1,
	"label":"web",
	"index":1,
	"display":1,
	"windows":[],
	"type":"bsp",
	"visible":1,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":6,
	"label":"term",
	"index":2,
	"display":1,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":37,
	"label":"external1",
	"index":3,
	"display":2,
	"windows":[2657],
	"type":"bsp",
	"visible":1,
	"focused":1,
	"native-fullscreen":0,
	"first-window":2657,
	"last-window":2657
},{
	"id":90,
	"label":"",
	"index":4,
	"display":2,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
}]
Amandas-MacBook-Pro-5:~ blaine$ yabai -m query --spaces
[{
	"id":1,
	"label":"web",
	"index":1,
	"display":1,
	"windows":[],
	"type":"bsp",
	"visible":1,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":6,
	"label":"term",
	"index":2,
	"display":1,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":37,
	"label":"external1",
	"index":3,
	"display":2,
	"windows":[2657],
	"type":"bsp",
	"visible":1,
	"focused":1,
	"native-fullscreen":0,
	"first-window":2657,
	"last-window":2657
},{
	"id":90,
	"label":"",
	"index":4,
	"display":2,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
}]
MacBook-Pro:~ blaine$ yabai -m window --space 4
MacBook-Pro:~ blaine$ yabai -m query --spaces
[{
	"id":1,
	"label":"web",
	"index":1,
	"display":1,
	"windows":[2909],
	"type":"bsp",
	"visible":1,
	"focused":0,
	"native-fullscreen":0,
	"first-window":2909,
	"last-window":2909
},{
	"id":6,
	"label":"term",
	"index":2,
	"display":1,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":37,
	"label":"external1",
	"index":3,
	"display":2,
	"windows":[],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":90,
	"label":"",
	"index":4,
	"display":2,
	"windows":[2657],
	"type":"bsp",
	"visible":1,
	"focused":1,
	"native-fullscreen":0,
	"first-window":2657,
	"last-window":2657
}]
```

**Comment by booherbg** [comment] 2020-04-20 17:41
Update: Moving from laptop to external monitor *does not* work any more. This seems to imply that the behavior is inconsistent. Sometimes it works, sometimes it doesn't, but so far it has never worked correctly across all displays.

**Comment by dominiklohmann** [comment] 2020-04-20 19:53
I fail to reproduce this.

- Are you running a current version of yabai?
- Do you have any possibly interfering software installed (e.g., TotalSpaces)?

**Comment by booherbg** [comment] 2020-04-20 20:03
> I fail to reproduce this.
> 
> * Are you running a current version of yabai?
> * Do you have any possibly interfering software installed (e.g., TotalSpaces)?

```
blaine$ yabai --version
yabai-v2.4.3
```

No other software is running, other than a fan control software. I can try upgrading yabai, although I don't have an up to date XCode environment so I'm not sure when I can do that (assuming XCode is a requirement).

**Comment by dominiklohmann** [comment] 2020-04-20 20:05
Nah 2.4.3 is current (except for some totally unrelated commits). Just wanted to make sure you're not running a months-old version.

**Comment by koekeishiya** [comment] 2020-05-22 12:23
I still cannot reproduce this issue.

**Comment by booherbg** [comment] 2020-05-25 22:36
Thanks for checking in! Still happens from time to time but I just work around it, no worries.

**Comment by koekeishiya** [comment] 2020-08-11 13:22
Closing this as I still can't seem to reproduce the issue.

**Closed by koekeishiya** 2020-08-11 13:22 UTC
Labels: help wanted, question
