### ISSUE TITLE
Chrome extension focus issue

### ISSUE THREAD

**Issue by jbharat** [koekeishiya/yabai#218] opened 2019-08-20 00:50 UTC
When I try to click on chrome extension like vimium, extension manager, the extension window is killed immediately and the focus moves back to the main chrome window. Similar thing happens with zoom app as well. 

I am attaching the logs here. In it I tried clicking on the two extensions multiple times. 

[yabairc.txt](https://github.com/koekeishiya/yabai/files/3518176/yabairc.txt)
[yabai.log](https://github.com/koekeishiya/yabai/files/3518177/yabai.log)

I tried focus_follows_mouse with autofocus as well. It had the same issue. This seems to happen only with chrome and zoom.

In zoom you cant select a meeting from the dropdown because the dropdown gets killed immediately.

**Comment by dominiklohmann** [comment] 2019-08-20 05:38
Are you running 1.1.2 or current master? That's likely caused by some `subrole=AXUnknown` windows from Chrome and has been fixed on master for a few weeks. There just hasn't been a new release yet.

**Comment by jbharat** [comment] 2019-08-20 06:03
Yep sorry. I am running v1.1.2. I  will upgrade to master test again.

**Closed** 2019-08-20 06:07 UTC
