### ISSUE TITLE
Unable to focus on other spaces

### ISSUE THREAD

**Issue by guanyilun** [koekeishiya/yabai#1549] opened 2022-12-02 19:44 UTC
I notice that the change in the latest [commit](https://github.com/koekeishiya/yabai/commit/206c0d6968210f48363f206526760e5750810a61) breaks space switching for me on Mac 12.6. I think this is caused by the `OSAX_VERSION` upgrade from 2.0.15 to 2.0.16. The problem disappeared for me when I manually downgrade the version.

**Comment by timhradil** [comment] 2022-12-03 00:09
This is because the latest commit fixes an issue with focusing spaces in OS 13. Unfortunately, due to a change in script injection in Ventura, this is a breaking change and you will need to upgrade to 13.x to focus on other spaces with the latest and future commits.

**Comment by koekeishiya** [comment] 2022-12-03 00:37
Probably just a bug in `get_page_address(..)`: https://github.com/koekeishiya/yabai/commit/206c0d6968210f48363f206526760e5750810a61#diff-c1309aa0e349c7eb2332343fe092875c76abac29a2e30a1432a39f632482be61R206

**Comment by guanyilun** [comment] 2022-12-06 04:35
Thank you for replying! I couldn't figure out what the bug is in that function. Could you elaborate more? I tried changing `PAGE_SIZE` to `getpagesize()` but that didn't seem to help.

**Comment by koekeishiya** [comment] 2022-12-07 10:41
Should be fixed on latest master now.

**Comment by declantsien** [comment] 2022-12-09 02:13
> Should be fixed on latest master now.

I can confirm that the latest master works for me.

**Closed** 2022-12-09 07:57 UTC
