### ISSUE TITLE
Programs exit from tiling-mode when short mouse clicks

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#16] opened 2019-06-02 14:32 UTC
I'm not sure how to explain this, but when I click the title bar in short mouse clicks, yabai loses control to the windows, and the window remains untiled.
Please see the GIF below.
![yabai-error-longer-then-shorter](https://user-images.githubusercontent.com/37990858/58762787-50dcab00-858e-11e9-8bf0-fb43c8153d4e.gif)

**Comment by koekeishiya** [comment] 2019-06-03 15:38
This happens when you click the mouse, drag and release all in a quick motion. When this happens macOS reports the events in the following order:

```
EVENT_HANDLER_MOUSE_DOWN: 828.10, 76.50
EVENT_HANDLER_MOUSE_DRAGGED: 830.28, 77.38
EVENT_HANDLER_MOUSE_DRAGGED: 855.17, 95.77
EVENT_HANDLER_MOUSE_UP: 855.17, 95.77
EVENT_HANDLER_WINDOW_MOVED: Finder 23230
```

As you can see, by the time we receive the *mouse up* event, and do our logic to calculate the dx and dy values of the window frame, the window itself has not actually been updated with the new coordinates. To fix this we would have to support out-of-order events somehow, based on a timing threshold? I'm not a fan of having to rely on something as brittle as that though..

**Comment by koekeishiya** [comment] 2020-06-06 01:02
Figured out a way to resolve this issue. Fixed on the latest master.

**Closed** 2020-06-08 21:39 UTC
Labels: bug

**Comment by koekeishiya** [comment] 2020-06-08 23:16
Had to undo these changes because macOS is garbage and there is no way to opt out of of otherwise track that accessibility notifications are the result of an operation caused by our own process, and so we can end up in an infinite loop in some circumstances.

**Comment by peppy** [comment] 2020-06-10 02:08
aha, so that was the feedback loop i was seeing!
