### ISSUE TITLE
Xcode New Tab

### ISSUE THREAD

**Issue by nuynait** [koekeishiya/yabai#137] opened 2019-07-15 18:05 UTC
Press `cmd-t` to create a new tab for Xcode will make *yabai* thought a new window has opened and shink Xcode size to half.

**Comment by dominiklohmann** [comment] 2019-07-15 18:18
Duplicate of #68.

**Comment by koekeishiya** [comment] 2019-07-15 18:57
Unlikely to be fixed for a long time because it is currently not possible to implement a fully robust solution to this problem. See my various comments in #68 and code changes made on the *tabbed-windows* branch.

**Closed by koekeishiya** 2019-07-15 18:57 UTC
