### ISSUE TITLE
12.5.1 Autofocus does not "click" focused window

### ISSUE THREAD

**Issue by ericsong** [koekeishiya/yabai#1413] opened 2022-09-14 04:01 UTC
I upgraded to 12.5.1 recently and noticed that autofocus isn't quite working anymore. I can still focus on the windows and send keystrokes but the cursor is inactive. The behavior is like hovering over an application before clicking on it.

Things I've tried
- Upgrade to latest yabai v4.0.4
- Reinstall SA
- Reinstall SIP -> Reinstall yabai

One thing I noticed is that the logs are emitting an `EVENT_HANDLER_MOUSE_DOWN: 0 0.00, 0.00` every time I focus on a new window. I'm not sure if that event was always being emitted but I know that it's not being emitted on my other mac setup that is working correctly.

https://user-images.githubusercontent.com/2770197/190057076-3d43c317-225b-4481-b7a3-d96e3eaaa77a.mov

**Comment by peterjbachman** [comment] 2022-09-20 14:17
Maybe this is related, but the Dock appears to stick as well when it's set to autohide and autofocus is enabled in yabai. Is this happening for you as well @ericsong?

https://user-images.githubusercontent.com/46987067/191282041-e6a3b322-c5b7-46d8-a31c-11c0bdde18a0.mov

**Comment by ericsong** [comment] 2022-09-20 15:02
yes! I have noticed this as well. Maybe there's a mac setting to turn this off that will restore the yabai behavior that I want.

**Comment by ericsong** [comment] 2022-09-20 22:06
I played around with the dock settings but couldn't find a configuration that makes the dock less.. "sticky".

**Comment by koekeishiya** [comment] 2022-12-28 13:11
Probably a duplicate of #1551 which is fixed on master.

**Closed** 2023-06-06 10:57 UTC
Labels: duplicate
