### ISSUE TITLE
Kitty is not always tiled

### ISSUE THREAD

**Issue by notquitedante** [koekeishiya/yabai#179] opened 2019-07-31 13:25 UTC
As you can see, Kitty is not always being tiled.

![screenshot](https://0x0.st/zfwE.png)

I have not been able to observe a pattern. If closing all the Kitty windows and then opening more, proper tiling resumes.

**Comment by pcr910303** [comment] 2019-07-31 16:38
@danteissaias Have you run `yabai -m query --windows --space` to analyze the problem?

**Comment by danteissaias** [comment] 2019-07-31 16:41
This is the value of one of the non-tiled windows:

```
{
        "id":31133,
        "pid":50498,
        "app":"kitty",
        "title":"htop /Users/dante",
        "frame":{
                "x":692.0000,
                "y":287.0000,
                "w":100.0000,
                "h":100.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":1,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":1,
        "sticky":0,
        "border":1,
        "shadow":0,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}
```

**Comment by pcr910303** [comment] 2019-07-31 16:44
@danteissaias I'm not sure why that happens (maybe a config messed it up? or it's a bug?) but you can use the signal system to manually make the `floating` values to 0 :-)
I haven't touched the signal system for a while, but there are events that are triggered when new windows are created.

**Comment by danteissaias** [comment] 2019-07-31 16:47
@pcr910303 This issue occurs with the example configuration, could this issue possible be a relative of #174, since maybe the Kitty windows are not always defloated?

**Comment by danteissaias** [comment] 2019-07-31 16:54
If its any help I discovered the trigger of this issue. If you open 4 Kitty windows tiled as so:

![screenshot](https://0x0.st/zfxC.png)

If you then create another Kitty window, and close it using <kbd>CMD+W</kbd>, the next Kitty window that is opened will suffer from this issue.

![screenshot 2](https://0x0.st/zf3o.png)

**Comment by koekeishiya** [comment] 2019-08-01 14:44
Unable to reproduce using your steps. This may be a duplicate of #183 (?) which has been fixed on master.

In any case, can you reproduce this issue on the latest stable version (v1.1.2)?

**Comment by danteissaias** [comment] 2019-08-01 17:46
It's not a duplicate of #183 as I am still able to produce this on master.

**Comment by danteissaias** [comment] 2019-08-01 17:50
[Here](https://0x0.st/zf0A.mp4) is a more detailed instruction on how to reproduce this issue, in case there was any confusion.

**Comment by koekeishiya** [comment] 2019-08-02 12:10
I still can't reproduce this issue doing the exact steps shown in that video.

**Comment by koekeishiya** [comment] 2020-02-11 20:27
So this is actually happening because there is a check for minimum window size upon creation, and if the window is smaller than the given dimensions, it will float instead: https://github.com/koekeishiya/yabai/blob/master/src/window.c#L263

I'm a bit reluctant to calling this a bug, but this is a sideeffect I had not considered..

**Comment by koekeishiya** [comment] 2020-02-11 20:35
I think this should be considered a bug. We should only float small windows that are *NOT* resizable.

**Closed** 2020-02-12 15:29 UTC
Labels: bug
