### ISSUE TITLE
window rules not working

### ISSUE THREAD

**Issue by MuhammadcodR** [koekeishiya/yabai#2201] opened 2024-04-02 20:09 UTC
This window rule is not working after past updates

yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off

I even change to this

yabai -m rule --add --apply app="^System Settings$" sticky=on layer=above manage=off

still not working!

anyone have a solution please?

**Comment by koekeishiya** [comment] 2024-04-03 01:56
Note changes to window rules in v7.0.0: 
> Add a new rule. Rules apply to windows that spawn after said rule has been added.

For rules to apply to windows that are already opened **before** yabai is launched or this rule is added, you need to also run `yabai -m rule --apply`

> --add [--one-shot] [<ARGUMENT>]
>>Add a new rule. Rules apply to windows that spawn after said rule has been added.
If --one-shot is present it will apply once and automatically remove itself.

>--apply [<RULE_SEL> | <ARGUMENT>]
>>Apply a rule to currently known windows.
If no argument is given, all existing rules will apply.
If an index or label is given, that particular rule will apply.
Arguments can also be provided directly, just like in the --add command.
Existing --one-shot rules that have yet to apply will be ignored by this command.


If you always want the old behavior when adding new rules, see this comment https://github.com/koekeishiya/yabai/issues/2199#issuecomment-2031528636

**Comment by mickaelperrin** [comment] 2024-04-03 08:17
I just migrated to v7 and have some issues with rules.

I would like that the main windows of my IDE are managed and associated with specific spaces depending on their name.
I would like that subwindows remains floating except some defined by their name, and some floating subwindows defined by their name are assigned to specific size and positions.

I ended with the following code:

```sh
JB_Apps='^(PyCharm|PhpStorm)$'
#
# Sub windows
# --------------
# Generic subwindows are floating
yabai -m rule --add app="${JB_Apps}" manage=off display="$CENTRAL_MONITOR"
# Specific subwindows rules
yabai -m rule --add app="^PhpStorm$" title="^(Preferences|Settings)$" manage=off grid=100:100:5:5:90:90 sub-layer=normal display=$CENTRAL_MONITOR
yabai -m rule --add app="^PhpStorm$" title="^Debug$" manage=on display=$LAPTOP_MONITOR # Specific subwindow
#
# Main windows
# --------------
# Generic
yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on display=$CENTRAL_MONITOR
# Specific
yabai -m rule --add app="^PhpStorm$" title="^Dotfiles.*\[.*\].*" space=dotfiles manage=on
yabai -m rule --add app="^PhpStorm$" title="^Ansible.*\[.*\].*" space=ansible manage=on
yabai -m rule --add app="^PhpStorm$" title="^Docker.*\[.*\].*" space=docker manage=on
yabai -m rule --add app="^PhpStorm$" title="^Yeoman.*\[.*\].*" space=yeoman manage=on
```

The problem is that all main windows are not moved to their spaces. The spaces exists and are well displayed in the command: `yabai -m query --spaces | jq '.[].label'

If I want that the main windows move to their spaces I have to remove all rules marked as "generic in the comments".

Any idea of what I am doing wrong ?

**Comment by koekeishiya** [comment] 2024-04-03 10:01
@mickaelperrin Your issue is that the display property incorrectly overrides the space property; it should be the other way around #2206

**Closed** 2024-04-03 11:17 UTC
Labels: question
